feat(iam): add support for iam/v2/ service
googleapis/google-cloud-cpp pull request #10393
Opened 2022-12-07 15:59 UTC by coryan

Fixes #9753 

----

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10393)

2022-12-07 16:28 UTC, dbolduc requested changes
The v2/ samples are not built or run. Was that intentional?

I think you want to remove the `iam/samples/{BUILD.bazel,CMakeLists.txt}` and add the following:

https://github.com/googleapis/google-cloud-cpp/blob/fed5b08ef56078067f21e5bb365980acaae00342/google/cloud/speech/BUILD.bazel#L63-L72

https://github.com/googleapis/google-cloud-cpp/blob/fed5b08ef56078067f21e5bb365980acaae00342/google/cloud/speech/CMakeLists.txt#L197-L203

2022-12-07 16:28 UTC, dbolduc commented on google/cloud/iam/CMakeLists.txt
> +    list(APPEND DOXYGEN_EXCLUDE_SYMBOLS "speech_${ns}internal")
s/speech/iam/

2022-12-07 16:55 UTC, dbolduc commented on google/cloud/iam/samples/BUILD.bazel
> -        "//:iam_mocks",
oops, I think I gave you bad advice w.r.t. the samples.......  🆂🅾🆁🆁🆈

2022-12-07 20:21 UTC, dbolduc commented on google/cloud/iam/CMakeLists.txt
>      if (BUILD_TESTING AND GOOGLE_CLOUD_CPP_ENABLE_CXX_EXCEPTIONS)
nit: we should probably do the `if` outside, instead of calling `target_link_libraries` from within the `foreach` loop.

2022-12-07 22:07 UTC, coryan commented
It all compiles now. :sweat:

2022-12-08 00:15 UTC, dbolduc approved these changes

2022-12-08 00:18 UTC, merged