impl(generator): functions for formatting comments
googleapis/google-cloud-cpp pull request #11010
Opened 2023-03-07 23:12 UTC by scotthart

part of the work for #10980 

The Discovery docs have a variety of description fields that we need to turn into comments to document the protos being created.

2023-03-09 20:23 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @dbolduc)

___
*[`generator/internal/codegen_utils.cc` line 322 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010#-NPyLK3NBuNORkf-YLev-r1-322:-NQ70ZvX6ffMBxErnD87:bjffibs) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b2daa005ae5c89645db0fa35b551d9d1791ce168/generator/internal/codegen_utils.cc#L322)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

I think it would be simpler to just include the space in the introducer. as in `std::string const& comment_introducer = "// "`
</blockquote></details>

Perhaps, left as is for now.
___
*[`generator/internal/codegen_utils.cc` line 323 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010#-NPyLK3NBuNORkf-YLev-r1-323:-NQ70fmd7uErJ73br2oo:b-p6b6sg) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b2daa005ae5c89645db0fa35b551d9d1791ce168/generator/internal/codegen_utils.cc#L323)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

should this fail?
</blockquote></details>

I want to keep this function return type as just `std::string`
___
*[`generator/internal/codegen_utils.cc` line 325 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010#-NPyLK3NBuNORkf-YLev-r1-325:-NQ70v_V7m1k91ou3Fqh:b-txjia5) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b2daa005ae5c89645db0fa35b551d9d1791ce168/generator/internal/codegen_utils.cc#L325)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

why? A comment cannot be one word without a space?

I think you are trying to account for the case where a word in a comment is super long (e.g. a hyperlink). I think we would rather include it in a line that goes over the limit, than drop it entirely. WDYT?
</blockquote></details>

Good catch. I added more test cases that exercise this scenario and adjusted to code accordingly.
___
*[`generator/internal/codegen_utils.cc` line 336 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010#-NPyLK3NBuNORkf-YLev-r1-336:-NQ710tA03HI8-e5ze2z:balnqn7) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b2daa005ae5c89645db0fa35b551d9d1791ce168/generator/internal/codegen_utils.cc#L336)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

I think this can get into an infinite loop if we encounter a word whose length is greater than the comment width.

```cc
// `start_pos` and `end_pos` will get stuck on 4.
FormatCommentBlock("foo wordthatiswaytoolong", 0, "", 0, 5);
```
</blockquote></details>

Added this test case. Works fine with this version of the function.
___
*[`generator/internal/codegen_utils.cc` line 344 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010#-NPyLK3NBuNORkf-YLev-r1-344:-NQ71AfxBTKezl-Sb1n4:b-w5mwex) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b2daa005ae5c89645db0fa35b551d9d1791ce168/generator/internal/codegen_utils.cc#L344)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

Consider the following, or some modification

```cc
    std::vector<std::string> lines;
    std::size_t start_pos = 0;
    while (start_pos != std::string::npos) {
        std::size_t boundary = start_pos + comment_width;
        std::size_t end_pos = boundary;
        if (boundary < comment.length()) {
          // Look backward from the boundary for the last word
          end_pos = comment.rfind(' ', boundary);
          // If there is only one word, find and use its boundary
          if (end_pos < start_pos) {
              end_pos = comment.find(' ', boundary);
          }
        }
        lines.push_back(comment.substr(start_pos, end_pos - start_pos));
        start_pos = comment.find_first_not_of(' ', end_pos);
    }
```

Aside: some people like to draw pretty pictures in their comments. e.g. [this monstrosity](https://github.com/googleapis/googleapis/blob/55445032240dc9cc20f656d45113c76fccad71c2/google/bigtable/v2/data.proto#L305-L336). The thing I proposed would strip the leading whitespace in between lines, effectively ruining the comment.

I am assuming that there are only spaces in the comments. Not `\n` or `\r` or whatever. But stripping the whitespace is something to think about.

Aside 2: I also don't strip the leading whitespace for the first line of the comment. eh, idc.
</blockquote></details>

re: the ascii art monstrosity, I don't think this function should try and handle every possible input. 
I foresee this function iterating over time as we encounter inputs that we would like to see a slightly better output for and look forward to see how others improve it.
___
*[`generator/internal/codegen_utils_test.cc` line 417 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010#-NPyLK3NBuNORkf-YLex-r1-417:-NQ716zF6nPELlLg_KLI:b-7vybwr) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b2daa005ae5c89645db0fa35b551d9d1791ce168/generator/internal/codegen_utils_test.cc#L417)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

can we s/1/80/ ?

I think we will find that nothing prints, which is a problem.
</blockquote></details>

Added test case.
___
*[`generator/internal/codegen_utils_test.cc` line 443 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010#-NPyLK3NBuNORkf-YLex-r1-443:-NQ718NjBjvgS9CZnHEZ:b-7vybwr) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b2daa005ae5c89645db0fa35b551d9d1791ce168/generator/internal/codegen_utils_test.cc#L443)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

I think we also want a test case for:

```cc
FormatCommentBlockTestParams{"line1 uhoh", 0, "", 0, 5, kExpected}
```

I think it might have a leading space on the second line that we do not want:
```
line1
 uhoh
```
</blockquote></details>

Added test case.


<!-- Sent from Reviewable.io -->

2023-03-09 22:12 UTC, dbolduc requested changes
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @scotthart)

___
*[`generator/internal/codegen_utils.cc` line 322 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010#-NPyLK3NBuNORkf-YLev-r1-322:-NQ7OGz1BKubUahLcfYc:b-33zf5x) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b2daa005ae5c89645db0fa35b551d9d1791ce168/generator/internal/codegen_utils.cc#L322)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Perhaps, left as is for now.
</blockquote></details>

Please change. The code will be prettier.
___
*[`generator/internal/codegen_utils.cc` line 323 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010#-NPyLK3NBuNORkf-YLev-r1-323:-NQ7OO8I0IzSPXM2GNNg:b-hcccel) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b2daa005ae5c89645db0fa35b551d9d1791ce168/generator/internal/codegen_utils.cc#L323)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

I want to keep this function return type as just `std::string`
</blockquote></details>

`GCP_LOG(FATAL)` ?

I don't think we expect this to get hit, so I don't really care.
___
*[`generator/internal/codegen_utils.cc` line 344 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010#-NPyLK3NBuNORkf-YLev-r1-344:-NQ7P60H7faU88LI-hdF:b-i4v9un) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b2daa005ae5c89645db0fa35b551d9d1791ce168/generator/internal/codegen_utils.cc#L344)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

re: the ascii art monstrosity, I don't think this function should try and handle every possible input. 
I foresee this function iterating over time as we encounter inputs that we would like to see a slightly better output for and look forward to see how others improve it.
</blockquote></details>

Surely the code I proposed is simpler to read? (assuming it worked... if not, egg on my face.)

Maybe you don't like how I am loosey-goosey with the `std::string::npos` arithmetic?
___
*[`generator/internal/codegen_utils.cc` line 339 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010#-NQ7QHTJ7wG8OCPgH5yy:-NQ7QHTJ7wG8OCPgH5yz:bqfhm6r) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b946a662774bc99225334b68b37048fc79d3a9dc/generator/internal/codegen_utils.cc#L339)):*
> ```cpp
>       end_pos = start_pos + comment_width;
>       space_before_width = comment.rfind(' ', end_pos);
>       space_after_width = comment.find(' ', end_pos);
> ```

why do 2 finds when one may be sufficient?



_Code quote:_
```cpp
      space_before_width = comment.rfind(' ', end_pos);
      space_after_width = comment.find(' ', end_pos);
```


<!-- Sent from Reviewable.io -->

2023-03-09 23:29 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @dbolduc)

___
*[`generator/internal/codegen_utils.cc` line 322 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010#-NPyLK3NBuNORkf-YLev-r1-322:-NQ7Uo_d5mN3g5GZPWcf:b-4wy8lm) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b2daa005ae5c89645db0fa35b551d9d1791ce168/generator/internal/codegen_utils.cc#L322)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

Please change. The code will be prettier.
</blockquote></details>

I'm more concerned with how it's invoked. I don't want the caller to have to remember to put a space.
___
*[`generator/internal/codegen_utils.cc` line 323 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010#-NPyLK3NBuNORkf-YLev-r1-323:-NQ7UnwDAXtoAJKrf5jG:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b2daa005ae5c89645db0fa35b551d9d1791ce168/generator/internal/codegen_utils.cc#L323)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

`GCP_LOG(FATAL)` ?

I don't think we expect this to get hit, so I don't really care.
</blockquote></details>

Done.
___
*[`generator/internal/codegen_utils.cc` line 344 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010#-NPyLK3NBuNORkf-YLev-r1-344:-NQ7VJsi0PkL8dW7zekC:b-6nzz2f) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b2daa005ae5c89645db0fa35b551d9d1791ce168/generator/internal/codegen_utils.cc#L344)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

Surely the code I proposed is simpler to read? (assuming it worked... if not, egg on my face.)

Maybe you don't like how I am loosey-goosey with the `std::string::npos` arithmetic?
</blockquote></details>

I didn't get this far in the review before I finished making changes to handle long urls, and I don't feel like coding/testing a third implementation of this function. I'm fine with additional PRs to iterate on the implementation, but this works for what I need it to do right now.
___
*[`generator/internal/codegen_utils.cc` line 339 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010#-NQ7QHTJ7wG8OCPgH5yy:-NQ7V40PDlTfqe89Mv4P:b-uszurb) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b946a662774bc99225334b68b37048fc79d3a9dc/generator/internal/codegen_utils.cc#L339)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

why do 2 finds when one may be sufficient?
</blockquote></details>

Because this is how I got it to satisfy all the test cases. At this point in time, I'm fine with sometimes performing an extra `find`.


<!-- Sent from Reviewable.io -->

2023-03-10 17:22 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @dbolduc)

___
*[`generator/internal/codegen_utils.cc` line 322 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010#-NPyLK3NBuNORkf-YLev-r1-322:-NQBXSsa8OqqwP7HSVzX:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b2daa005ae5c89645db0fa35b551d9d1791ce168/generator/internal/codegen_utils.cc#L322)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

I'm more concerned with how it's invoked. I don't want the caller to have to remember to put a space.
</blockquote></details>

Done.
___
*[`generator/internal/codegen_utils.cc` line 344 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11010#-NPyLK3NBuNORkf-YLev-r1-344:-NQBXVbw802xbAKz8bfY:bi98uws) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b2daa005ae5c89645db0fa35b551d9d1791ce168/generator/internal/codegen_utils.cc#L344)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

I didn't get this far in the review before I finished making changes to handle long urls, and I don't feel like coding/testing a third implementation of this function. I'm fine with additional PRs to iterate on the implementation, but this works for what I need it to do right now.
</blockquote></details>

I tried your version. It fails to insert a newline in the "supercalifragilisticexpialidocious wsupercalifragilisticexpialidocious" test case. Left the implementation as is for now.


<!-- Sent from Reviewable.io -->

2023-03-10 17:48 UTC, dbolduc approved these changes
> I tried your version.

That's fair. Thanks.

2023-03-10 18:00 UTC, merged