feat(compute): generate library
googleapis/google-cloud-cpp pull request #11734
Opened 2023-05-26 17:30 UTC by scotthart

I broke up the changes into multiple commits for ease of reviewing.

This PR adds:
- a single resource/service for compute (disks)
- its LRO supporting service (zone_operations)
- integration tests for the disks service (hits production)
- the usual supporting documentation and build infrastructure for a new service

2023-05-26 18:08 UTC, coryan reviewed
> Reviewed 81 of 81 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734)* status: all files reviewed, 14 unresolved discussions (waiting on @scotthart)

___
*[`.typos.toml` line 3 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWO8ZWy1c_NEDPM6NuL:-NWO8ZWy1c_NEDPM6NuM:b-yib5p1) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/.typos.toml#L3)):*
> ```TOML
> [default.extend-words]
> # These typos appear in the compute discovery json
> "chosing"="chosing"
> ```

nit: can we send fixes upstream for these?
___
*[`generator/discovery-compute_public_google_rest_v1.json` line 0 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWO8pNH5HumJUG6h7L8:-NWO8pNH5HumJUG6h7L9:b-gxl7y6) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/generator/discovery-compute_public_google_rest_v1.json#L0)):*
nit: are these files automatically updated as part of ??? Please remember to send a separate PR to update the right how-to guide.
___
*[`generator/generator_config.textproto` line 437 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWO9IpzCjq1isIJz4kr:-NWO9IpzCjq1isIJz4ks:bl8vocr) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/generator/generator_config.textproto#L437)):*
> ```
> # Compute
> discovery_products {
>   discovery_document_url: "file:///workspace/generator/discovery-compute_public_google_rest_v1.json"
> ```

Can we use `/' as a separator between `discovery` and `compute_public_google_rest_v1.json`?  If not, can we use a `-` for consistency?  Would it be worthwhile to name this file `generator/discovery/compute/public_google_rest_v1.json`?
___
*[`google/cloud/compute/BUILD.bazel` line 57 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWO9pW44kT5YyRPdXIP:-NWO9pW44kT5YyRPdXIQ:b-fv2xhe) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/BUILD.bazel#L57)):*
> ```Starlark
> )
> 
> cc_grpc_library(
> ```

Do we need this library?
___
*[`google/cloud/compute/README.md` line 7 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOA8g96FrraLkCeIm4:-NWOA8gA-PpxbxdemKSP:bn08nf0) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/README.md#L7)):*
> ```Markdown
> and verify attestation responses.
> 
> While this library is **GA**, please note that the Google Cloud C++ client
> ```

Is this GA?  I thought it was experimental...
___
*[`google/cloud/compute/disks/v1/disks.proto` line 202 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOAQ4P0e1ulUZ4bAWp:-NWOAQ4P0e1ulUZ4bAWq:bk2t4xu) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/disks/v1/disks.proto#L202)):*
> ```protobuf
>   // exception that zero UUID is not supported (
>   // 00000000-0000-0000-0000-000000000000).
>   optional string request_id = 4;
> ```

FYI: this is a very neat .proto file.  
___
*[`google/cloud/compute/disks/v1/disks.proto` line 221 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOAaHI6Fxg_6OrTv2E:-NWOAaHI6Fxg_6OrTv2F:b-cfgjzh) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/disks/v1/disks.proto#L221)):*
> ```protobuf
>   // operator can be used with string fields to match substrings. For non-string
>   // fields it is equivalent to the `=` operator. The `:*` comparison can be
>   // used to test whether a key has been defined. For example, to find all
> ```

FYI: Looks like some formatting got lost.  Please open a PR to preserve the newlines, we will need them to make the documentation readable.
___
*[`google/cloud/compute/doc/main.dox` line 8 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOCM0v9mpVonv_Fo1-:-NWOCM0v9mpVonv_Fo10:b-87nhsm) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/doc/main.dox#L8)):*
> ```
> and manage cloud computing resources.
> 
> While this library is **GA**, please note that the Google Cloud C++ client libraries do **not** follow
> ```

I think you want to change this.
___
*[`google/cloud/compute/doc/main.dox` line 18 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOCUaiBjrac7sb9eWy:-NWOCUaiBjrac7sb9eWz:bp128ln) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/doc/main.dox#L18)):*
> ```
> @tableofcontents{HTML:2}
> 
> ## Setting up your repo
> ```

you probably generated this with an older version.  Newer versions will not have the "Setting up your repo" section (and some other sections below).
___
*[`google/cloud/compute/doc/main.dox` line 41 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOCh5dBmXmMiYhKOCp:-NWOCh5dBmXmMiYhKOCq:bf1jf4o) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/doc/main.dox#L41)):*
> ```
> 
> @snippet quickstart.cc all
> ```

There is now a section listing the key client classes.
___
*[`google/cloud/compute/doc/main.dox` line 42 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOCdDU8M64pGWJSnA3:-NWOCdDU8M64pGWJSnA4:b-t64u4q) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/doc/main.dox#L42)):*
> ```
> @snippet quickstart.cc all
> 
> ## Error Handling
> ```

This got refactored to its own page.
___
*[`google/cloud/compute/doc/main.dox` line 61 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOCft68ghtREpxkQ6D:-NWOCft68ghtREpxkQ6E:bs4q9op) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/doc/main.dox#L61)):*
> ```
> `google::cloud::Status`.
> 
> ## Override the default endpoint
> ```

Ditto.
___
*[`google/cloud/compute/doc/main.dox` line 111 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOClz7D3-24v_R00PV:-NWOClz7D3-24v_R00PW:b-7e3hji) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/doc/main.dox#L111)):*
> ```
> */
> 
> // <!-- inject-endpoint-pages-start -->
> ```

I think this is all moved.
___
*[`google/cloud/compute/integration_tests/CMakeLists.txt` line 17 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOCuCu-Xyc_1uU3S2U:-NWOCuCu-Xyc_1uU3S2V:bazaw6i) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/integration_tests/CMakeLists.txt#L17)):*
> ```CMake
> # ~~~
> 
> function (google_cloud_cpp_compute_define_integration_tests)
> ```

Skip this function, we used to do that but it was a bad idea. 
___
*[`google/cloud/compute/integration_tests/compute_integration_test.cc` line 42 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOD49i7jI4hXU8P-xj:-NWOD49i7jI4hXU8P-xk:b-e5aiea) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/integration_tests/compute_integration_test.cc#L42)):*
> ```cpp
>         google::cloud::internal::GetEnv("GOOGLE_CLOUD_PROJECT").value_or("");
>     ASSERT_FALSE(project_id_.empty());
>     zone_ = google::cloud::internal::GetEnv("GOOGLE_CLOUD_CPP_TEST_ZONE")
> ```

FYI, we will need to think about this because zones are not very reliable (by design).  Just open a tracking bug or something.
___
*[`google/cloud/compute/quickstart/WORKSPACE. [...]

2023-05-26 19:02 UTC, dbolduc reviewed
> Reviewed 81 of 81 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734)* status: all files reviewed, 23 unresolved discussions (waiting on @scotthart)

___
*[`.typos.toml` line 2 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOAiBf31tUk4QnLfGk:-NWOAiBf31tUk4QnLfGl:b-vxy4yq) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/.typos.toml#L2)):*
> ```TOML
> [default.extend-words]
> # These typos appear in the compute discovery json
> ```

Ideally, we would ignore the files that have misspellings. We still want `typos` to catch when we make these mistakes.
___
*[`.typos.toml` line 12 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOBHIIBgEv7dLxqdN-:-NWOBHIIBgEv7dLxqdN0:b-7e1ppn) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/.typos.toml#L12)):*
> ```TOML
> [files]
> extend-exclude = [
>     # discovery json
> ```

"The discovery docs have one or more typos in their comments"
___
*[`generator/generator_config.textproto` line 459 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOBwJzBC0x7qJqbacs:-NWOBwJzBC0x7qJqbact:by6fkfu) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/generator/generator_config.textproto#L459)):*
> ```
>     generate_grpc_transport: false
>   }
> }
> ```

nit: newline
___
*[`google/cloud/compute/README.md` line 4 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOMis82aEN84jGoi0I:-NWOMis82aEN84jGoi0J:b-5z4oeh) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/README.md#L4)):*
> ```Markdown
> 
> This directory contains an idiomatic C++ client library for the
> [Compute Engine API][cloud-service-docs], a service to create challenges
> ```

"a service that lets you create and run virtual machines on Google’s infrastructure."
___
*[`google/cloud/compute/doc/environment-variables.dox` line 15 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWONJ2O5D-0WQDxtQ9I:-NWONJ2O5D-0WQDxtQ9J:b-66zxf0) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/doc/environment-variables.dox#L15)):*
> ```
> - `GOOGLE_CLOUD_CPP_COMPUTE_ENDPOINT=...` overrides the
>   `EndpointOption` (which defaults to "compute.googleapis.com")
>   used by `MakeConfidentialComputingConnection()`.
> ```

Do we need script updates here?

https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/disks/v1/internal/disks_option_defaults.cc#L37
___
*[`google/cloud/compute/doc/main.dox` line 6 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOOVUsBcViGksZeLDQ:-NWOOVUsBcViGksZeLDR:b-5v1dmx) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/doc/main.dox#L6)):*
> ```
> 
> An idiomatic C++ client library for the [Compute API][cloud-service-docs], a service to create 
> and manage cloud computing resources.
> ```

Ah. This should probably match `compute/README.md`.

nit: It looks like "Compute Engine API" > "Compute API"
___
*[`google/cloud/compute/integration_tests/CMakeLists.txt` line 49 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOPTnR78jgHXovMdvI:-NWOPTnR78jgHXovMdvJ:b6chihw) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/integration_tests/CMakeLists.txt#L49)):*
> ```CMake
>         set_tests_properties(
>             ${target} PROPERTIES LABELS
>                                  "integration-test;integration-test-emulator")
> ```

drop the emulator label
___
*[`google/cloud/compute/integration_tests/CMakeLists.txt` line 53 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOP_OB5b8O8QdzFidu:-NWOP_OB5b8O8QdzFidv:bvcjq1e) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/integration_tests/CMakeLists.txt#L53)):*
> ```CMake
>     endforeach ()
> 
>     if (NOT GOOGLE_CLOUD_CPP_ENABLE_CXX_EXCEPTIONS)
> ```

remove dead code
___
*[`google/cloud/compute/integration_tests/compute_integration_test.cc` line 77 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOQUyK0iMJBQYe6Kl8:-NWOQUyLBaRqmjm9YY_d:bx8o3q3) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/integration_tests/compute_integration_test.cc#L77)):*
> ```cpp
>     if (d->labels().contains("test")) {
>       auto delete_disk =
>           client.DeleteDisks(project_id_, zone_, d->name()).get();
> ```

should clean up happen in `~ComputeIntegrationTest()` ? otherwise we will leak disks.
___
*[`google/cloud/compute/integration_tests/compute_integration_test.cc` line 83 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOQbjZ7KeSjcG2IAAg:-NWOQbjZ7KeSjcG2IAAh:b-atnbzx) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/integration_tests/compute_integration_test.cc#L83)):*
> ```cpp
> 
>   google::cloud::cpp::compute::v1::Disk disk;
>   disk.set_name("int-test-disk");
> ```

should this name be unique across runs?


<!-- Sent from Reviewable.io -->

2023-05-26 20:12 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734)* status: 23 of 83 files reviewed, 23 unresolved discussions (waiting on @coryan and @dbolduc)

___
*[`.typos.toml` line 3 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWO8ZWy1c_NEDPM6NuL:-NWOeMglCVEZpPHO6ap5:bf1tr1x) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/.typos.toml#L3)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: can we send fixes upstream for these?
</blockquote></details>

Created https://github.com/googleapis/google-cloud-cpp/issues/11736 to track.
___
*[`generator/generator_config.textproto` line 437 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWO9IpzCjq1isIJz4kr:-NWOeenj0sFYGWlakUmW:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/generator/generator_config.textproto#L437)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Can we use `/' as a separator between `discovery` and `compute_public_google_rest_v1.json`?  If not, can we use a `-` for consistency?  Would it be worthwhile to name this file `generator/discovery/compute/public_google_rest_v1.json`?
</blockquote></details>

Done.
___
*[`google/cloud/compute/BUILD.bazel` line 57 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWO9pW44kT5YyRPdXIP:-NWOeq1NAioEwb3wp3Nz:b-lqa0xs) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/BUILD.bazel#L57)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Do we need this library?
</blockquote></details>

For now we do as the generator emits codes that includes the grpc.pb.h files, but we can likely fix that too.
Created https://github.com/googleapis/google-cloud-cpp/issues/11738 to track.
___
*[`google/cloud/compute/README.md` line 7 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOA8g96FrraLkCeIm4:-NWOf-5UDT06eZJetKVu:b62olse) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/README.md#L7)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Is this GA?  I thought it was experimental...
</blockquote></details>

Removed this sentence.
___
*[`google/cloud/compute/disks/v1/disks.proto` line 221 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOAaHI6Fxg_6OrTv2E:-NWOf4mCAoKkLf3PZr2j:b-494uxj) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/disks/v1/disks.proto#L221)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

FYI: Looks like some formatting got lost.  Please open a PR to preserve the newlines, we will need them to make the documentation readable.
</blockquote></details>

These comments are read from a description field in the json that does not contain formatting.
___
*[`google/cloud/compute/doc/main.dox` line 8 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOCM0v9mpVonv_Fo1-:-NWOfQ6r1pToSnuwaBvL:b62olse) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/doc/main.dox#L8)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think you want to change this.
</blockquote></details>

Removed this sentence.
___
*[`google/cloud/compute/doc/main.dox` line 18 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOCUaiBjrac7sb9eWy:-NWOfTV6ANIoB_MPgqnh:b-o5dn6r) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/doc/main.dox#L18)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

you probably generated this with an older version.  Newer versions will not have the "Setting up your repo" section (and some other sections below).
</blockquote></details>

Updated the main.dox file to the latest format.
___
*[`google/cloud/compute/doc/main.dox` line 41 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOCh5dBmXmMiYhKOCp:-NWOf_Wh10AC3Q_K2b4X:b-o5dn6r) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/doc/main.dox#L41)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

There is now a section listing the key client classes.
</blockquote></details>

Updated the main.dox file to the latest format.
___
*[`google/cloud/compute/doc/main.dox` line 42 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOCdDU8M64pGWJSnA3:-NWOfa2L7iih2kHe8-WZ:b-o5dn6r) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/doc/main.dox#L42)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This got refactored to its own page.
</blockquote></details>

Updated the main.dox file to the latest format.
___
*[`google/cloud/compute/doc/main.dox` line 61 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOCft68ghtREpxkQ6D:-NWOfau02FZ0hTyndxng:b-o5dn6r) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/doc/main.dox#L61)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Updated the main.dox file to the latest format.
___
*[`google/cloud/compute/doc/main.dox` line 111 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOClz7D3-24v_R00PV:-NWOfcNl9z8sE1Bp5oLo:buolzka) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/doc/main.dox#L111)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think this is all moved.
</blockquote></details>

Added the override dox files.
___
*[`google/cloud/compute/integration_tests/CMakeLists.txt` line 17 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOCuCu-Xyc_1uU3S2U:-NWOffnNDEDuRzO-kS99:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/integration_tests/CMakeLists.txt#L17)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Skip this function, we used to do that but it was a bad idea. 
</blockquote></details>

Done.
___
*[`google/cloud/compute/integration_tests/compute_integration_test.cc` line 42 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOD49i7jI4hXU8P-xj:-NWOfhmI1SIJxhu-7OBw:bb9zv44) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/integration_tests/compute_integration_test.cc#L42)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

FYI, we will need to think about this because zones are not very reliable (by design).  Just open a tracking bug or something.
</blockquote></details>

We can pick a new region or global scoped service to test with after all the services have been added.
Created https://github.com/googleapis/google-cloud-cpp/issues/11739
___
*[`google/cloud/compute/quickstart/WORKSPACE.bazel` line 27 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWODs18DFaOxUmdzggO:-NWOgDIPAy-bAC20Z2E3:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/ [...]

2023-05-26 21:14 UTC, coryan reviewed
> Reviewed 60 of 60 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734)* status: all files reviewed, 9 unresolved discussions (waiting on @dbolduc and @scotthart)

___
*[`google/cloud/compute/disks/v1/disks.proto` line 221 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOAaHI6Fxg_6OrTv2E:-NWOqhcuEOKyRVGmNALr:b-oasi7l) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/disks/v1/disks.proto#L221)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

These comments are read from a description field in the json that does not contain formatting.
</blockquote></details>

Ugh.  In most cases we do not care.  The fields are not relevant for the C++ code.  Maybe we can magically point developers to this:

https://cloud.google.com/compute/docs/reference/rest/v1/disks/aggregatedList#query-parameters

I mean we could ignore the comments in the discovery doc.  Just create a link based on the name of the request?
___
*[`google/cloud/compute/integration_tests/compute_integration_test.cc` line 77 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOQUyK0iMJBQYe6Kl8:-NWOu-lR9-raHs5bH92i:b20mcob) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/integration_tests/compute_integration_test.cc#L77)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

should clean up happen in `~ComputeIntegrationTest()` ? otherwise we will leak disks.
</blockquote></details>

We will probably want the usual garbage collection at the beginning of these integration tests, i.e., remove (after a couple of days) any resources leaked by previous runs.
___
*[`google/cloud/compute/integration_tests/compute_integration_test.cc` line 83 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOQbjZ7KeSjcG2IAAg:-NWOuDguCaCPs8T7l2TD:b-azti0d) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/integration_tests/compute_integration_test.cc#L83)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

should this name be unique across runs?
</blockquote></details>

What @dbolduc said.
___
*[`google/cloud/compute/zone_operations/v1/zone_operations_client.h` line 229 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOE6v2DqKNV6Ss8SVG:-NWOtfAGC4RD6MBq3hdf:be1tnca) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/zone_operations/v1/zone_operations_client.h#L229)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Created issue https://github.com/googleapis/google-cloud-cpp/issues/11735.
</blockquote></details>

Thanks. Added some comments there.


<!-- Sent from Reviewable.io -->

2023-05-26 21:48 UTC, coryan requested changes
I think this is really close.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-:-NWOy--05hjPEPqpFGWs:bntsfn1)* status: all files reviewed, 10 unresolved discussions (waiting on @dbolduc and @scotthart)

___
*[`google/cloud/compute/integration_tests/compute_integration_test.cc` line 73 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWP-hSh4rf_gQGIqGRm:-NWP-hSh4rf_gQGIqGRn:bgf0ern) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f4d7538e60d89ba0b6b385bcb51ca83a3f81e502/google/cloud/compute/integration_tests/compute_integration_test.cc#L73)):*
> ```cpp
>       disks::MakeDisksConnectionRest(google::cloud::ExperimentalTag{}));
> 
>   for (auto const& d : client.ListDisks(project_id_, zone_)) {
> ```

Consider something like this:

```cc
auto const random_name = RandomDiskName();

  google::cloud::cpp::compute::v1::Disk disk;
  disk.set_name(random_name);
  disk.set_size_gb("10");
  (*disk.mutable_labels())["test"] = "test";
  auto result = client.InsertDisks(project_id_, zone_, disk).get();
  ASSERT_THAT(result, testing_util::IsOk());

  auto get_disk = client.GetDisks(project_id_, zone_, random_name);
  ASSERT_THAT(get_disk, IsOk());

  google::cloud::cpp::compute::v1::ZoneSetLabelsRequest request;
  request.set_label_fingerprint(get_disk->label_fingerprint());
  (*request.mutable_labels())["test"] = "test";
  auto set_label =
      client.SetLabels(project_id_, zone_, random_name, request).get();
  EXPECT_THAT(set_label, IsOk());

  auto const create_threshold = std::chrono::system_clock::now() - std::chrono::hours(48);
  for (auto const& d : client.ListDisks(project_id_, zone_)) {
    ASSERT_STATUS_OK(d);
    // Delete the disk we just created, we expect this to succeed.
    if (d->name() == random_name) {
        // Can you create a client that retries delete operations? Otherwise this can flake...
        auto delete_disk = client.DeleteDisk(project_id_, zone_, d->name()).get();
        EXPECT_THAT(delete_disk, IsOk());
    } 
    // Garbage collect old disks, ignore errors.
    if (d->labels().contains("test") && d->creation_timestamp() < create_threshold) {
      (void)client.DeleteDisks(project_id_, zone_, d->name()).get();
    }
  }
```




_Code snippet:_
```cpp
  for (auto const& d : client.ListDisks(project_id_, zone_)) {
    ASSERT_STATUS_OK(d);
    if (d->labels().contains("test")) {
      auto delete_disk =
          client.DeleteDisks(project_id_, zone_, d->name()).get();
      EXPECT_THAT(delete_disk, IsOk());
    }
  }

  google::cloud::cpp::compute::v1::Disk disk;
  disk.set_name("int-test-disk");
  disk.set_size_gb("10");
  (*disk.mutable_labels())["test"] = "test";
  auto result = client.InsertDisks(project_id_, zone_, disk).get();
  ASSERT_THAT(result, testing_util::IsOk());

  auto get_disk = client.GetDisks(project_id_, zone_, "int-test-disk");
  ASSERT_THAT(get_disk, IsOk());

  google::cloud::cpp::compute::v1::ZoneSetLabelsRequest request;
  request.set_label_fingerprint(get_disk->label_fingerprint());
  (*request.mutable_labels())["test"] = "test";
  auto set_label =
      client.SetLabels(project_id_, zone_, "int-test-disk", request).get();
  EXPECT_THAT(set_label, IsOk());
```


<!-- Sent from Reviewable.io -->

2023-05-30 21:52 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734)* status: all files reviewed, 10 unresolved discussions (waiting on @coryan and @dbolduc)

___
*[`.typos.toml` line 2 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOAiBf31tUk4QnLfGk:-NWiZhdo3M9xWa4ibBfq:b-lllufd) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/.typos.toml#L2)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

Ideally, we would ignore the files that have misspellings. We still want `typos` to catch when we make these mistakes.
</blockquote></details>

Changed the exclusion mechanism to all .proto and .h files that could contain the typos from the json discovery document.
___
*[`.typos.toml` line 12 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOBHIIBgEv7dLxqdN-:-NWiZtYREFIPF8lczld5:b-qj92pf) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/.typos.toml#L12)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

"The discovery docs have one or more typos in their comments"
</blockquote></details>

Reworded.
___
*[`generator/generator_config.textproto` line 459 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOBwJzBC0x7qJqbacs:-NWiZw6p9PDrnCkiO8P0:blenhy7) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/generator/generator_config.textproto#L459)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

nit: newline
</blockquote></details>

Added newline.
___
*[`google/cloud/compute/README.md` line 4 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOMis82aEN84jGoi0I:-NWiZxrP9lNXSINnmes9:bj8incs) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/README.md#L4)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

"a service that lets you create and run virtual machines on Google’s infrastructure."
</blockquote></details>

Updated from previous copy/pasta.
___
*[`google/cloud/compute/disks/v1/disks.proto` line 221 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOAaHI6Fxg_6OrTv2E:-NWi_gWpB3x7tVPQ50zV:bgfkcjn) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/disks/v1/disks.proto#L221)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Ugh.  In most cases we do not care.  The fields are not relevant for the C++ code.  Maybe we can magically point developers to this:

https://cloud.google.com/compute/docs/reference/rest/v1/disks/aggregatedList#query-parameters

I mean we could ignore the comments in the discovery doc.  Just create a link based on the name of the request?
</blockquote></details>

Not sure what the best solution is at present, created issue to track https://github.com/googleapis/google-cloud-cpp/issues/11751
___
*[`google/cloud/compute/doc/environment-variables.dox` line 15 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWONJ2O5D-0WQDxtQ9I:-NWi_oae7-wJSYr_HK8I:bsybm6l) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/doc/environment-variables.dox#L15)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

Do we need script updates here?

https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/disks/v1/internal/disks_option_defaults.cc#L37
</blockquote></details>

I'm not sure if having per service endpoints make sense for non-grpc libraries. Added issue to track https://github.com/googleapis/google-cloud-cpp/issues/11749
___
*[`google/cloud/compute/doc/main.dox` line 6 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOOVUsBcViGksZeLDQ:-NWi_wFc15Sut1lOMw29:bneam7l) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/doc/main.dox#L6)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

Ah. This should probably match `compute/README.md`.

nit: It looks like "Compute Engine API" > "Compute API"
</blockquote></details>

Fixed all occurrences I found.
___
*[`google/cloud/compute/integration_tests/CMakeLists.txt` line 49 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOPTnR78jgHXovMdvI:-NWia-w140gM4eKeOhVD:b-qx85zf) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/integration_tests/CMakeLists.txt#L49)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

drop the emulator label
</blockquote></details>

Dropped and added the target to the production test targets.
___
*[`google/cloud/compute/integration_tests/CMakeLists.txt` line 53 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOP_OB5b8O8QdzFidu:-NWia4YhBfDaa9BJig5t:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/integration_tests/CMakeLists.txt#L53)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

remove dead code
</blockquote></details>

Done.
___
*[`google/cloud/compute/integration_tests/compute_integration_test.cc` line 77 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOQUyK0iMJBQYe6Kl8:-NWiaTCzCWM6wIWpBkV0:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/integration_tests/compute_integration_test.cc#L77)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

We will probably want the usual garbage collection at the beginning of these integration tests, i.e., remove (after a couple of days) any resources leaked by previous runs.
</blockquote></details>

Done.
___
*[`google/cloud/compute/integration_tests/compute_integration_test.cc` line 83 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWOQbjZ7KeSjcG2IAAg:-NWiaTax9TVKuoWmUlRS:bij5ehl) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bacf5cd7142618574d7ca36fdb9c635e4ce2bb56/google/cloud/compute/integration_tests/compute_integration_test.cc#L83)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

What @dbolduc said.
</blockquote></details>

Added random name generation.
___
*[`google/cloud/compute/integration_tests/compute_integration_test.cc` line 73 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWP-hSh4rf_gQGIqGRm:-NWiaOYTAHhjg4EsnbDW:b-4lbmls) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f4d7538e60d89ba0b6b385bcb51ca83a3f81e502/google/cloud/compute/integration_tests/compute_integration_test.cc#L73)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Consider something like this:

```cc
auto const random_name = RandomDiskName();

  google::cloud::cpp::compute::v1::Disk disk;
  disk.set_name(random_name);
  disk.set_size_gb("10");
  (*disk.mutable_labels())["test"] = "test";
  auto result = client.InsertDisks(project_id_, zone_, disk).get();
  ASSERT_THAT(result, testing_util::IsOk());

  auto get_disk = client.GetDisks(project_id_, zone_, random_name);
  ASSERT_THAT(get_disk, IsOk());

  google::cloud::cpp::compute::v1::ZoneSetLabelsRequest request;
  request.set_label_fingerprint(get_disk->label_fingerprint());
  (*request.mutable_labels())["test"] = "test";
  auto se [...]

2023-05-30 22:04 UTC, coryan approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-:-NWig8QTDLc4uHZE7c_I:bnfp4nl)* status: all files reviewed, 11 unresolved discussions (waiting on @dbolduc and @scotthart)

___
*[`google/cloud/compute/integration_tests/compute_integration_test.cc` line 39 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWifP5T6aF9XPGtc_75:-NWifP5UEhQBPNt99IFh:bbduc98) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4d35fb7759f1d75d00b3e5948cd328a7b542c49b/google/cloud/compute/integration_tests/compute_integration_test.cc#L39)):*
> ```cpp
> 
> std::string CreateRandomName(std::string const& prefix) {
>   static internal::DefaultPRNG generator = internal::MakeDefaultPRNG();
> ```

nit: you could move this variable to the fixture and avoid the hidden global.
___
*[`google/cloud/compute/integration_tests/compute_integration_test.cc` line 115 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWifha94pXYpWrzqzTe:-NWifha94pXYpWrzqzTf:bmc5b0v) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4d35fb7759f1d75d00b3e5948cd328a7b542c49b/google/cloud/compute/integration_tests/compute_integration_test.cc#L115)):*
> ```cpp
>     // Garbage collect old disks, ignore errors.
>     auto creation_timestamp = internal::ParseRfc3339(d->creation_timestamp());
>     if (creation_timestamp) {
> ```

nit: `if (!creation_timestamp) continue;`


<!-- Sent from Reviewable.io -->

2023-05-30 22:09 UTC, dbolduc reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734)* status: all files reviewed, 11 unresolved discussions (waiting on @scotthart)

___
*[`google/cloud/compute/integration_tests/compute_integration_test.cc` line 107 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWigzzl-h8ofu--ZZvS:-NWigzzm1wpntsCTQV6t:b-r88prp) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4d35fb7759f1d75d00b3e5948cd328a7b542c49b/google/cloud/compute/integration_tests/compute_integration_test.cc#L107)):*
> ```cpp
>     // Delete the disk we just created, we expect this to succeed.
>     if (d->name() == disk.name()) {
>       // Can you create a client that retries delete operations? Otherwise this
> ```

I don't think this comment was meant for the code :)


<!-- Sent from Reviewable.io -->

2023-05-30 22:19 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734)* status: 83 of 84 files reviewed, 11 unresolved discussions (waiting on @coryan and @dbolduc)

___
*[`google/cloud/compute/integration_tests/compute_integration_test.cc` line 39 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWifP5T6aF9XPGtc_75:-NWijXegBsnJqY-UZvQZ:b4qmvv0) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4d35fb7759f1d75d00b3e5948cd328a7b542c49b/google/cloud/compute/integration_tests/compute_integration_test.cc#L39)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: you could move this variable to the fixture and avoid the hidden global.
</blockquote></details>

Moved into the fixture
___
*[`google/cloud/compute/integration_tests/compute_integration_test.cc` line 107 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWigzzl-h8ofu--ZZvS:-NWij8az2uV6uw1-jc1a:b-ip3hac) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4d35fb7759f1d75d00b3e5948cd328a7b542c49b/google/cloud/compute/integration_tests/compute_integration_test.cc#L107)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

I don't think this comment was meant for the code :)
</blockquote></details>

Removed the comment, I'll try and figure out a retry mechanism in the future.
___
*[`google/cloud/compute/integration_tests/compute_integration_test.cc` line 115 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11734#-NWifha94pXYpWrzqzTe:-NWijNey5h-dEb1625Nq:b-68d4z4) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4d35fb7759f1d75d00b3e5948cd328a7b542c49b/google/cloud/compute/integration_tests/compute_integration_test.cc#L115)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: `if (!creation_timestamp) continue;`
</blockquote></details>

I'm `continue` adverse :)
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es77-minimize-the-use-of-break-and-continue-in-loops


<!-- Sent from Reviewable.io -->

2023-05-31 15:42 UTC, merged