feat: use full jitter exp backoff policy in the generator
googleapis/google-cloud-cpp pull request #11748
Opened 2023-05-30 18:49 UTC by alevenberg

Fixes issue #8755

2023-05-30 19:46 UTC, coryan approved these changes

2023-05-30 20:02 UTC, dbolduc requested changes
> Reviewed 3 of 233 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11748)* status: 3 of 233 files reviewed, 2 unresolved discussions (waiting on @alevenberg and @coryan)

___
*[`generator/internal/option_defaults_generator.cc` line 166 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11748#-NWiF5E16xIwkTfORy4y:-NWiF5E16xIwkTfORy4z:boji137) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1f24eecf935bb7e1d8898a0ecc7bd84857275038/generator/internal/option_defaults_generator.cc#L166)):*
> ```cpp
>     "            $product_namespace$::$service_name$BackoffPolicyOption::Type>(\n"
>     "            options.get<$product_namespace$::$retry_policy_name$Option>()->clone(),\n"
>     "            options.get<$product_namespace$::$service_name$BackoffPolicyOption>()->clone())\n"
> ```

We should change this back to the old value.


<!-- Sent from Reviewable.io -->

2023-05-30 20:03 UTC, alevenberg reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11748)* status: 3 of 233 files reviewed, 1 unresolved discussion (waiting on @coryan and @dbolduc)

___
*[`generator/internal/option_defaults_generator.cc` line 166 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11748#-NWiF5E16xIwkTfORy4y:-NWiFbri-MM50vJZL_n_:b-lbut5x) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1f24eecf935bb7e1d8898a0ecc7bd84857275038/generator/internal/option_defaults_generator.cc#L166)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

We should change this back to the old value.
</blockquote></details>

What do you mean?


<!-- Sent from Reviewable.io -->

2023-05-30 20:31 UTC, dbolduc reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11748)* status: 3 of 233 files reviewed, 1 unresolved discussion (waiting on @alevenberg and @coryan)

___
*[`generator/internal/option_defaults_generator.cc` line 166 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11748#-NWiF5E16xIwkTfORy4y:-NWiLDNX2LFcGM_bLDxS:b-2abla3) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1f24eecf935bb7e1d8898a0ecc7bd84857275038/generator/internal/option_defaults_generator.cc#L166)):*
<details><summary><i>Previously, alevenberg (Anna Levenberg) wrote…</i></summary><blockquote>

What do you mean?
</blockquote></details>

We should use `ExponentialBackoffPolicy(std::chrono::seconds(1), std::chrono::minutes(5), kBackoffScaling)` instead of cloning the `*BackoffPolicyOption`


(Because full jitter is good for individual retries to address the thundering herd problem. But it is not best for polling LROs. We do not want to be waking up background threads after 0 seconds to check the status of the operation.) 


<!-- Sent from Reviewable.io -->

2023-05-30 21:25 UTC, alevenberg reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11748)* status: 2 of 233 files reviewed, 1 unresolved discussion (waiting on @coryan and @dbolduc)

___
*[`generator/internal/option_defaults_generator.cc` line 166 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11748#-NWiF5E16xIwkTfORy4y:-NWiY8TK4lSFQ8yG-LIP:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1f24eecf935bb7e1d8898a0ecc7bd84857275038/generator/internal/option_defaults_generator.cc#L166)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

We should use `ExponentialBackoffPolicy(std::chrono::seconds(1), std::chrono::minutes(5), kBackoffScaling)` instead of cloning the `*BackoffPolicyOption`


(Because full jitter is good for individual retries to address the thundering herd problem. But it is not best for polling LROs. We do not want to be waking up background threads after 0 seconds to check the status of the operation.) 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-30 21:35 UTC, dbolduc reviewed
It might be worth adding tests to ...

- https://github.com/googleapis/google-cloud-cpp/blob/main/generator/integration_tests/tests/golden_kitchen_sink_option_defaults_test.cc
- https://github.com/googleapis/google-cloud-cpp/blob/main/generator/integration_tests/tests/golden_thing_admin_option_defaults_test.cc

... to verify that the retry / backoff / polling policy options have values. (We wouldn't need to check what their value is.)

2023-05-30 21:35 UTC, dbolduc commented on generator/internal/option_defaults_generator.cc
> -    "            options.get<$product_namespace$::$service_name$BackoffPolicyOption>()->clone())\n"
This is the only line we want to change.

2023-05-30 21:35 UTC, dbolduc commented on generator/internal/option_defaults_generator.cc
> +    "    options.set<$product_namespace$::$service_name$BackoffPolicyOption>(\n"
we want to set the PollingPolicyOption

2023-05-31 13:53 UTC, alevenberg commented on generator/internal/option_defaults_generator.cc
> +    "    options.set<$product_namespace$::$service_name$BackoffPolicyOption>(\n"
Fixed

2023-05-31 14:43 UTC, dbolduc commented on generator/internal/option_defaults_generator.cc
> +    "    options.set<$product_namespace$::$service_name$BackoffPolicyOption>(\n"
`git push` ?

2023-05-31 18:22 UTC, dbolduc approved these changes
The inline namespace thing needs to get fixed, but I trust you can make the change.

2023-05-31 18:22 UTC, dbolduc commented on generator/integration_tests/tests/golden_kitchen_sink_option_defaults_test.cc
> +using ::google::cloud::golden_v1::v2_11::GoldenKitchenSinkRetryPolicyOption;
we should not be using the [inline namespace](https://en.cppreference.com/w/cpp/language/namespace#Inline_namespaces), `v2_11`. Inline namespaces are only used by libraries/applications that need to use two versions of `google-cloud-cpp` at the same time. (which is hopefully rare).

```cc
using ::google::cloud::golden_v1::GoldenKitchenSinkBackoffPolicyOption;
```

2023-05-31 18:22 UTC, dbolduc commented on generator/integration_tests/tests/golden_kitchen_sink_option_defaults_test.cc
> +  EXPECT_EQ(true, updated_options.has<GoldenKitchenSinkRetryPolicyOption>());
nit: here and below, we always say:

```cc
EXPECT_TRUE(updated_options.has<GoldenKitchenSinkRetryPolicyOption>());
```

2023-05-31 18:22 UTC, dbolduc commented on generator/integration_tests/tests/golden_thing_admin_option_defaults_test.cc
> +using ::google::cloud::golden_v1::GoldenThingAdminBackoffPolicyOption;
these are right :+1:

2023-05-31 18:48 UTC, dbolduc approved these changes

2023-05-31 20:51 UTC, alevenberg reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11748#-:-NWnGymF7500h_1eQaHO:bb6un1j)* status: 2 of 235 files reviewed, 5 unresolved discussions (waiting on @coryan and @dbolduc)

*[a discussion](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11748#gh-1210845141:-NWnH04S9Y2pDuaU8LEK:bb6un1j) (no related file):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map this GitHub inline comment thread to the right spot — sorry!)*

This is the only line we want to change.
</blockquote></details>

Done

___
*[a discussion](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11748#gh-1210845260:-NWnH11x8V0_kZQHduv6:bh9f965) (no related file):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

`git push` ?
</blockquote></details>

Whoops. Done

___
___
*[`generator/integration_tests/tests/golden_kitchen_sink_option_defaults_test.cc` line 32 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11748#gh-1212124010:-NWnH4yGC8Hht9TLSADZ:bb6un1j) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/76ecfbb3aa9960bf6b5bfa9664e5adb77362a14c/generator/integration_tests/tests/golden_kitchen_sink_option_defaults_test.cc#L32)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

we should not be using the [inline namespace](https://en.cppreference.com/w/cpp/language/namespace#Inline_namespaces), `v2_11`. Inline namespaces are only used by libraries/applications that need to use two versions of `google-cloud-cpp` at the same time. (which is hopefully rare).

```cc
using ::google::cloud::golden_v1::GoldenKitchenSinkBackoffPolicyOption;
```
</blockquote></details>

Done
___
*[`generator/integration_tests/tests/golden_kitchen_sink_option_defaults_test.cc` line 91 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11748#gh-1212124448:-NWnH5pgBcFra-2susnJ:bb6un1j) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/76ecfbb3aa9960bf6b5bfa9664e5adb77362a14c/generator/integration_tests/tests/golden_kitchen_sink_option_defaults_test.cc#L91)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

nit: here and below, we always say:

```cc
EXPECT_TRUE(updated_options.has<GoldenKitchenSinkRetryPolicyOption>());
```
</blockquote></details>

Done
___
*[`generator/integration_tests/tests/golden_thing_admin_option_defaults_test.cc` line 29 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11748#gh-1212127021:-NWnH6l8ALKzPEMlDft8:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/76ecfbb3aa9960bf6b5bfa9664e5adb77362a14c/generator/integration_tests/tests/golden_thing_admin_option_defaults_test.cc#L29)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

these are right :+1: 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-31 20:52 UTC, alevenberg reviewed
> Dismissed @dbolduc from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11748)* status: 2 of 235 files reviewed, all discussions resolved (waiting on @coryan and @dbolduc)



<!-- Sent from Reviewable.io -->

2023-05-31 20:57 UTC, coryan approved these changes
> Reviewed 122 of 233 files at r1, 111 of 113 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11748)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alevenberg)



<!-- Sent from Reviewable.io -->

2023-05-31 21:16 UTC, merged