ci: include discovery services in feature list
googleapis/google-cloud-cpp pull request #12124
Opened 2023-07-17 22:23 UTC by dbolduc

There is currently no effect to this change. But this is a necessary step towards documenting `google/cloud/compute/`.

The one place where we use `list_full()` and `list_full_cmake()` differently is in our `publish-docs` build. We iterate over the `features::list_full()` when uploading:

https://github.com/googleapis/google-cloud-cpp/blob/de9cf7ece900ebe8f758091b2baaae8e3a932d8f/ci/cloudbuild/builds/publish-docs.sh#L24

https://github.com/googleapis/google-cloud-cpp/blob/de9cf7ece900ebe8f758091b2baaae8e3a932d8f/ci/cloudbuild/builds/publish-docs.sh#L148

https://github.com/googleapis/google-cloud-cpp/blob/de9cf7ece900ebe8f758091b2baaae8e3a932d8f/ci/cloudbuild/builds/publish-docs.sh#L166

And our only discovery based service (`compute`) has documentation disabled. (see #11792)

https://github.com/googleapis/google-cloud-cpp/blob/de9cf7ece900ebe8f758091b2baaae8e3a932d8f/google/cloud/compute/CMakeLists.txt#L132-L134

2023-07-17 22:44 UTC, coryan commented
Do we need `ci/etc/full_feature_list`?  We can do something like `cmake -DCMAKE_MODULE_PATH=$PWD/cmake -P cmake/print-ga-libraries.cmake`...

2023-07-17 23:02 UTC, dbolduc commented on google/cloud/compute/doc/main.dox
>  are part of the same product or are often used together. A typical example may
Hm, maybe we don't want this change.

2023-08-07 22:57 UTC, dbolduc reviewed
@scotthart - I will let you decide what to do with this PR. If you do not want it, I will just close the thing. We can always find it later.

2023-08-07 22:57 UTC, dbolduc commented on google/cloud/compute/doc/main.dox
>  are part of the same product or are often used together. A typical example may
I propose that we merge this PR, then in a follow up, change the checkers script to `s/gRPC //` in these two places.

2023-08-07 23:08 UTC, scotthart requested changes
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12124)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @dbolduc)

___
*[`google/cloud/compute/doc/environment-variables.dox` line 13 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12124#-NbHEctzCog_MO9XlPOF:-NbHEctzCog_MO9XlPOG:bf3a1gd) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bdad028382726eb4aa49fad0a2e0c7011cb5a459/google/cloud/compute/doc/environment-variables.dox#L13)):*
> ```
> <!-- inject-endpoint-env-vars-start -->
> 
> - `GOOGLE_CLOUD_CPP_ACCELERATOR_TYPES_ENDPOINT=...` overrides the
> ```

would we want this to to be `GOOGLE_CLOUD_CPP_COMPUTE_ACCELERATOR_TYPES_ENDPOINT` to properly scope the var name? 
Looking forward, I can't guarantee that compute won't add a resource name that conflicts with another existing service.
___
*[`google/cloud/compute/doc/main.dox` line 29 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12124#gh-1265980811:-NbHFEAwAluXtl_gBSp9:bb7ohn6) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/681391dcbf1268f2a5a7ddda1d2bdacd82d7ab68/google/cloud/compute/doc/main.dox#L29)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

I propose that we merge this PR, then in a follow up, change the checkers script to `s/gRPC //` in these two places.
</blockquote></details>

sgtm


<!-- Sent from Reviewable.io -->

2023-08-08 15:33 UTC, dbolduc reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12124)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @devbww and @scotthart)

___
*[`google/cloud/compute/doc/environment-variables.dox` line 13 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12124#-NbHEctzCog_MO9XlPOF:-NbKkVbJ6Q7cfCI40eIV:b-dw2p89) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/bdad028382726eb4aa49fad0a2e0c7011cb5a459/google/cloud/compute/doc/environment-variables.dox#L13)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

would we want this to to be `GOOGLE_CLOUD_CPP_COMPUTE_ACCELERATOR_TYPES_ENDPOINT` to properly scope the var name? 
Looking forward, I can't guarantee that compute won't add a resource name that conflicts with another existing service.
</blockquote></details>

I think that is a good question, but not relevant to this PR. (Aside: it might have been wise to do this for the gRPC based services).

`checkers` is just grabbing the variable name from the code.

https://github.com/googleapis/google-cloud-cpp/blob/10f89ff813e56e1ca531d4515b3c705932e57bfa/google/cloud/compute/accelerator_types/v1/internal/accelerator_types_option_defaults.cc#L37

 So if we change the variable name the docs should update accordingly.

Also, I think @devbww made `checkers` smart enough to not repeat env var names within a library. So if we go with one `GOOGLE_CLOUD_CPP_COMPUTE_ENDPOINT` for all compute services, the docs should still look fine.

PTAL


<!-- Sent from Reviewable.io -->

2023-08-08 17:06 UTC, scotthart approved these changes
> Reviewed 1 of 8 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12124)* status: all files reviewed, 1 unresolved discussion (waiting on @dbolduc)



<!-- Sent from Reviewable.io -->

2023-08-08 17:47 UTC, merged