refactor(iam): move iam_v2_policy_protos to a separate lib
googleapis/google-cloud-cpp pull request #12413
Opened 2023-08-18 19:35 UTC by scotthart

2023-08-18 19:56 UTC, coryan reviewed
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12413)* status: all files reviewed, 1 unresolved discussion (waiting on @scotthart)

___
*[`external/googleapis/CMakeLists.txt` line 233 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12413#-Nc9CNIu-b_JtNm8BYnx:-Nc9CNIu-b_JtNm8BYny:b-bm80sc) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/03384a8112f54976eec342b0a8a36594a2400d43/external/googleapis/CMakeLists.txt#L233)):*
> ```CMake
>     google_cloud_cpp_iam_v1_options_protos
>     google_cloud_cpp_iam_v1_policy_protos
>     google_cloud_cpp_iam_v2_deny_protos
> ```

This will let you introduce the new policy troubleshooter service, but will always compile the IAM v2 protos, even when not needed (see #8022).  Though I gave up on fixing the existing problem, I would like to not make it bigger.

See what we did for grafeas for inspiration.


<!-- Sent from Reviewable.io -->

2023-08-22 18:50 UTC, coryan requested changes
A few things to clean up.

The library name ... I don't have great suggestions but maybe you do?

2023-08-22 18:50 UTC, coryan commented on cmake/GoogleCloudCppFeatures.cmake
> +        list(INSERT enabled_features 0 iam iam_policy)
```suggestion
        list(INSERT enabled_features 0 iam_policy iam)
```

2023-08-22 18:50 UTC, coryan commented on google/cloud/iam/CMakeLists.txt
> +           google_cloud_cpp_iam_policy_protos)
For consistency, maybe we should use the aliased name?

```suggestion
           google-cloud-cpp::iam_policy_protos)
```

2023-08-22 18:50 UTC, coryan commented on external/googleapis/update_libraries.sh
> -      "@com_google_googleapis//google/iam/v1/logging:logging_cc_grpc"
Looks like lost the iam/v1/logging protos?  I am not sure it was a good idea to include them in the past, but since we did, we need to keep them.

2023-08-22 18:50 UTC, coryan commented on google/cloud/iam_policy/CMakeLists.txt
> +            COMPONENT google_cloud_cpp_development)
We have not cleaned this up everwhere, but we can do better now that we require CMake >= 3.13:


```suggestion
            NAMELINK_COMPONENT google_cloud_cpp_development
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
            COMPONENT google_cloud_cpp_development)
```

2023-08-22 18:50 UTC, coryan commented on cmake/GoogleCloudCppFeatures.cmake
> +        list(INSERT enabled_features 0 iam iam_policy)
I think we want to compile `iam_policy` before compiling `iam`?

2023-08-22 18:50 UTC, coryan commented on external/googleapis/protolists/iam_policy.list
> +@com_google_googleapis//google/iam/v2:deny.proto
The name of the library and its contents do not really match anymore.  I think we got here through a series of reasonable decisions, but having a library called `iam_policy` which only contains the `v2` protos seems ... unfortunate.

Would `iam_v2` be a better name? or even `iam_v2_protos`?

2023-08-24 15:32 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12413)* status: 2 of 15 files reviewed, 6 unresolved discussions (waiting on @coryan)

___
*[`cmake/GoogleCloudCppFeatures.cmake` line 207 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12413#gh-1302038650:-Ncc9_Ay8Fi7NmaLRHMK:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ce905d10c1ce8eaa68a863a5943f4f9756ceafb0/cmake/GoogleCloudCppFeatures.cmake#L207)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think we want to compile `iam_policy` before compiling `iam`?
</blockquote></details>

Done.
___
*[`external/googleapis/CMakeLists.txt` line 233 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12413#-Nc9CNIu-b_JtNm8BYnx:-Ncc9awk8bRv64rHQ7Z5:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/03384a8112f54976eec342b0a8a36594a2400d43/external/googleapis/CMakeLists.txt#L233)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This will let you introduce the new policy troubleshooter service, but will always compile the IAM v2 protos, even when not needed (see #8022).  Though I gave up on fixing the existing problem, I would like to not make it bigger.

See what we did for grafeas for inspiration.
</blockquote></details>

Done.
___
*[`external/googleapis/update_libraries.sh` line 0 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12413#gh-1302041375:-Ncc9buS58IS23zLCzR0:b-o5uh9q) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ce905d10c1ce8eaa68a863a5943f4f9756ceafb0/external/googleapis/update_libraries.sh#L0)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map this GitHub inline comment thread to the right spot — sorry!)*

Looks like lost the iam/v1/logging protos?  I am not sure it was a good idea to include them in the past, but since we did, we need to keep them.

</blockquote></details>

While the logging protos were included in the iam_policy.list and iam_policy.deps files, no libraries were ever built using them as inputs. So removing the iam/v1/logging protos doesn't affect anything as far as I can tell.
___
*[`external/googleapis/protolists/iam_policy.list` line 1 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12413#gh-1302059987:-NccA3nd3dW0HA4oTuEb:b-d36dy4) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ce905d10c1ce8eaa68a863a5943f4f9756ceafb0/external/googleapis/protolists/iam_policy.list#L1)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

The name of the library and its contents do not really match anymore.  I think we got here through a series of reasonable decisions, but having a library called `iam_policy` which only contains the `v2` protos seems ... unfortunate.

Would `iam_v2` be a better name? or even `iam_v2_protos`?
</blockquote></details>

I'm hoping that we can eventually factor out the iam v1 policy protos from external/googleapis/CMakeLists.txt and add them to this new lib, making it whole.
___
*[`google/cloud/iam/CMakeLists.txt` line 57 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12413#gh-1302041143:-NccADQDAY2qj8gLtMzg:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ce905d10c1ce8eaa68a863a5943f4f9756ceafb0/google/cloud/iam/CMakeLists.txt#L57)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

For consistency, maybe we should use the aliased name?

```suggestion
           google-cloud-cpp::iam_policy_protos)
```
</blockquote></details>

Done.
___
*[`google/cloud/iam_policy/CMakeLists.txt` line 66 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12413#gh-1302045439:-NccAEob7miTUolQRh1W:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ce905d10c1ce8eaa68a863a5943f4f9756ceafb0/google/cloud/iam_policy/CMakeLists.txt#L66)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

We have not cleaned this up everwhere, but we can do better now that we require CMake >= 3.13:


```suggestion
            NAMELINK_COMPONENT google_cloud_cpp_development
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
            COMPONENT google_cloud_cpp_development)
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-24 18:59 UTC, dbolduc commented on google/cloud/iam_policy/CMakeLists.txt
> +            COMPONENT google_cloud_cpp_runtime
ditto

2023-08-24 19:17 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12413)* status: 2 of 15 files reviewed, 8 unresolved discussions (waiting on @coryan and @dbolduc)

___
*[`google/cloud/iam/CMakeLists.txt` line 0 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12413#gh-1304742058:-NccyG0n-RTSm6SppGWZ:b-odd20v) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/702ccab022efd4377f103b72068a0f18177122ce/google/cloud/iam/CMakeLists.txt#L0)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map this GitHub inline comment thread to the right spot — sorry!)*

Can't say I know what it does, but I think we want:
`NAMELINK_COMPONENT google_cloud_cpp_development`
</blockquote></details>

From what I grok of https://cmake.org/cmake/help/latest/command/install.html `NAMELINK_COMPONENT` is only needed if we want a different name for the symbolic link.


<!-- Sent from Reviewable.io -->

2023-08-28 21:16 UTC, coryan requested changes
> Reviewed 10 of 13 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12413)* status: all files reviewed, 5 unresolved discussions (waiting on @dbolduc and @scotthart)

___
*[`google/cloud/iam/CMakeLists.txt` line 0 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12413#gh-1304742058:-Ncxz15ZAL6LXbjwvzpU:blyazu9) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/702ccab022efd4377f103b72068a0f18177122ce/google/cloud/iam/CMakeLists.txt#L0)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

From what I grok of https://cmake.org/cmake/help/latest/command/install.html `NAMELINK_COMPONENT` is only needed if we want a different name for the symbolic link.
</blockquote></details>

We define our install components to achieve this:

```
# This will install all the artifacts needed to create the development package of our libraries, i.e., headers, CMake and pkg-config files, as well as .so and necessary .so links 
cmake --install .build --component google_cloud_cpp_development

# This will install all the artifacts needed to create the runtime package of our libraries, just the minimal .so files:
cmake --install .build --component google_cloud_cpp_runtime
```

`NAMELINK_COMPONENT` picks which of the "install components" creates links for the `.so` files.  Not the name of the links, but the name of the install component that will create the links.
___
*[`google/cloud/iam/CMakeLists.txt` line 131 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12413#-Ncy-JIiAKMQQlsqEB_z:-Ncy-JIiAKMQQlsqEBa-:b92cjlb) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/702ccab022efd4377f103b72068a0f18177122ce/google/cloud/iam/CMakeLists.txt#L131)):*
> ```CMake
>             COMPONENT google_cloud_cpp_runtime
>     LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
>             COMPONENT google_cloud_cpp_runtime
> ```

This is missing the `NAMELINK_COMPONENT`.
___
*[`google/cloud/iam_policy/CMakeLists.txt` line 66 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12413#gh-1302045439:-Ncy-8Ia595mDTNZ0z8F:balhue5) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ce905d10c1ce8eaa68a863a5943f4f9756ceafb0/google/cloud/iam_policy/CMakeLists.txt#L66)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still missing the `NAMELINK_COMPONENT` here too.


<!-- Sent from Reviewable.io -->

2023-08-28 22:53 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12413)* status: 13 of 15 files reviewed, 5 unresolved discussions (waiting on @coryan and @dbolduc)

___
*[`google/cloud/iam/CMakeLists.txt` line 131 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12413#-Ncy-JIiAKMQQlsqEB_z:-NcyLOMZ6VL-H42UrRVC:bqmjwcz) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/702ccab022efd4377f103b72068a0f18177122ce/google/cloud/iam/CMakeLists.txt#L131)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This is missing the `NAMELINK_COMPONENT`.
</blockquote></details>

Added.
___
*[`google/cloud/iam_policy/CMakeLists.txt` line 66 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12413#gh-1302045439:-NcyLQ89-sPogZPXplkm:bqmjwcz) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ce905d10c1ce8eaa68a863a5943f4f9756ceafb0/google/cloud/iam_policy/CMakeLists.txt#L66)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Still missing the `NAMELINK_COMPONENT` here too.
</blockquote></details>

Added.


<!-- Sent from Reviewable.io -->

2023-08-28 22:54 UTC, coryan approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12413)* status: all files reviewed, 2 unresolved discussions (waiting on @dbolduc and @scotthart)



<!-- Sent from Reviewable.io -->

2023-08-29 01:27 UTC, merged