impl(compute): split features and bazel build targets per library
googleapis/google-cloud-cpp pull request #12656
Opened 2023-09-15 19:31 UTC by scotthart

2023-09-15 21:51 UTC, coryan requested changes

2023-09-15 21:51 UTC, coryan commented on cmake/CreateBazelConfig.cmake
> +                foreach (compute_lib ${GOOGLE_CLOUD_CPP_COMPUTE_LIBRARIES})
```suggestion
                foreach (compute_lib IN LISTS GOOGLE_CLOUD_CPP_COMPUTE_LIBRARIES)
```

2023-09-15 21:51 UTC, coryan commented on cmake/CreateBazelConfig.cmake
> +            # While cmake needs compute as a feature, it confuses bazel.
Is this comment still true?  Does CMake require `compute` as a feature?

2023-09-15 21:51 UTC, coryan commented on cmake/CreateBazelConfig.cmake
> +            if (${item} STREQUAL "compute")
This seems like the wrong place to implement this functionality.  This function is a general-purpose "export a list to a `.bzl` file".  It seems it should be called with a list that contains the regular features and all the values from `GOOGLE_CLOUD_CPP_COMPUTE_LIBRARIES` .

2023-09-18 16:07 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656)* status: 0 of 9 files reviewed, 7 unresolved discussions (waiting on @coryan)

*[a discussion](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656#gh-1327743890:-Ned1hefErg7q7uyuqiH:b-9ppiff) (no related file):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map this GitHub inline comment thread to the right spot — sorry!)*

If you are trying to avoid duplicates: there is no need, they are removed around line 314.
</blockquote></details>

Original changes removed.

___
*[a discussion](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656#gh-1327744949:-Ned1lRt8cntQq9nSYf2:b-9ppiff) (no related file):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map this GitHub inline comment thread to the right spot — sorry!)*

Are there any dependencies between the `compute_*` libraries?  If so, we need to add them below.
</blockquote></details>

Original changes removed.

___
*[a discussion](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656#gh-1327747068:-Ned1lrS0wrMtDtU5Jmf:b-9ppiff) (no related file):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map this GitHub inline comment thread to the right spot — sorry!)*

I wonder if we could get `compute/blah_blah` to work as feature names.
</blockquote></details>

Original changes removed.

___
*[a discussion](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656#gh-1327756308:-Ned1Niv251QYgd5nzyC:b-kmzlyu) (no related file):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map this GitHub inline comment thread to the right spot — sorry!)*

This file is missing the copyright boiler plate, and probably should go in the `bazel/` subdirectory.

</blockquote></details>

Added copyright and relocated file.

___
___
*[`cmake/CreateBazelConfig.cmake` line 127 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656#gh-1327820660:-Ned1RmZ8WY25fjJExKu:bu0v084) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b05de1669e0c4a3131a62535932fa431d21c9870/cmake/CreateBazelConfig.cmake#L127)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Is this comment still true?  Does CMake require `compute` as a feature?
</blockquote></details>

Yes we still create compute-targets.cmake and compute-version.cmake files.
___
*[`cmake/CreateBazelConfig.cmake` line 128 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656#gh-1327822175:-Ned1b4QEOAHH12Qq9vC:b17o21s) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b05de1669e0c4a3131a62535932fa431d21c9870/cmake/CreateBazelConfig.cmake#L128)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This seems like the wrong place to implement this functionality.  This function is a general-purpose "export a list to a `.bzl` file".  It seems it should be called with a list that contains the regular features and all the values from `GOOGLE_CLOUD_CPP_COMPUTE_LIBRARIES` .
</blockquote></details>

Moved populating the correct lists to just prior to the function call.
___
*[`cmake/CreateBazelConfig.cmake` line 129 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656#gh-1327820106:-Ned1gbd8WCHwWx7yDFu:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b05de1669e0c4a3131a62535932fa431d21c9870/cmake/CreateBazelConfig.cmake#L129)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

```suggestion
                foreach (compute_lib IN LISTS GOOGLE_CLOUD_CPP_COMPUTE_LIBRARIES)
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-18 16:15 UTC, devbww commented on cmake/GoogleCloudCppFeatures.cmake
> +list(FIND GOOGLE_CLOUD_CPP_TRANSITION_LIBRARIES "compute" compute_experimental)
s/_experimental/_transition/?

2023-09-18 16:15 UTC, devbww commented on cmake/GoogleCloudCppFeatures.cmake
> +list(FIND GOOGLE_CLOUD_CPP_GA_LIBRARIES "compute" compute_experimental)
s/_experimental/_ga/?

2023-09-18 16:15 UTC, devbww commented on google/cloud/compute/BUILD.bazel
> +) for service in service_dirs + operation_service_dirs]
Should we just have one loop for "service proto targets" that instantiates all the targets, rather than a loop for each target?

2023-09-18 16:52 UTC, coryan requested changes
> Reviewed 3 of 8 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656)* status: all files reviewed, 4 unresolved discussions (waiting on @scotthart)

___
*[`cmake/CreateBazelConfig.cmake` line 127 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656#-NedC2In0sdthuMOML3f:-NedC2In0sdthuMOML3g:bh479s1) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/62a591d6bf93dd69b76758a8e535e881c8af7445/cmake/CreateBazelConfig.cmake#L127)):*
> ```CMake
>         file(APPEND "${filename}" "\n${VAR} = [\n")
>         foreach (item ${${VAR}})
>             # While cmake needs compute as a feature, it confuses bazel.
> ```

I think this code was moving to `GoogleCloudCppFeatures.cmake`?


<!-- Sent from Reviewable.io -->

2023-09-18 20:14 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656)* status: all files reviewed, 4 unresolved discussions (waiting on @coryan and @devbww)

___
*[`cmake/CreateBazelConfig.cmake` line 127 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656#-NedC2In0sdthuMOML3f:-Nedtm7g3dtDlCj2ljHp:bss4a2b) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/62a591d6bf93dd69b76758a8e535e881c8af7445/cmake/CreateBazelConfig.cmake#L127)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think this code was moving to `GoogleCloudCppFeatures.cmake`?
</blockquote></details>

Removed.
___
*[`cmake/GoogleCloudCppFeatures.cmake` line 251 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656#gh-1328964247:-NedtoYYD_LCrBmjsDU5:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/62a591d6bf93dd69b76758a8e535e881c8af7445/cmake/GoogleCloudCppFeatures.cmake#L251)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

s/_experimental/_transition/?
</blockquote></details>

Done.
___
*[`cmake/GoogleCloudCppFeatures.cmake` line 258 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656#gh-1328964617:-Nedtov585y2DgsjlGTZ:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/62a591d6bf93dd69b76758a8e535e881c8af7445/cmake/GoogleCloudCppFeatures.cmake#L258)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

s/_experimental/_ga/?
</blockquote></details>

Done.
___
*[`google/cloud/compute/BUILD.bazel` line 133 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656#gh-1328967979:-NedtrFK9ythG4-IFJFV:b-xdpryb) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/62a591d6bf93dd69b76758a8e535e881c8af7445/google/cloud/compute/BUILD.bazel#L133)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

Should we just have one loop for "service proto targets" that instantiates all the targets, rather than a loop for each target?
</blockquote></details>

I'm not sure I understand the question. How would you define the proto targets differently?


<!-- Sent from Reviewable.io -->

2023-09-18 20:59 UTC, devbww reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @coryan and @scotthart)

___
*[`google/cloud/compute/BUILD.bazel` line 133 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656#gh-1328967979:-NedxseGEm2_b-Ce_E2I:bs891ee) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/62a591d6bf93dd69b76758a8e535e881c8af7445/google/cloud/compute/BUILD.bazel#L133)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

I'm not sure I understand the question. How would you define the proto targets differently?
</blockquote></details>

Instead of ...
```
[ filegroup(...) for service in service_dirs + operation_service_dirs]
[ proto_library(...) for service in service_dirs + operation_service_dirs]
```
just ...
```
[[
    filegroup(...),
    proto_library(...),
] for service in service_dirs + operation_service_dirs]
```
That is, one loop for all targets instead of a loop for each target.


<!-- Sent from Reviewable.io -->

2023-09-18 21:21 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @coryan and @devbww)

___
*[`google/cloud/compute/BUILD.bazel` line 133 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656#gh-1328967979:-Nee9lJJ5ULFEk-ycPEY:b-mvxkxk) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/62a591d6bf93dd69b76758a8e535e881c8af7445/google/cloud/compute/BUILD.bazel#L133)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

Instead of ...
```
[ filegroup(...) for service in service_dirs + operation_service_dirs]
[ proto_library(...) for service in service_dirs + operation_service_dirs]
```
just ...
```
[[
    filegroup(...),
    proto_library(...),
] for service in service_dirs + operation_service_dirs]
```
That is, one loop for all targets instead of a loop for each target.
</blockquote></details>

TIL. Done.


<!-- Sent from Reviewable.io -->

2023-09-18 21:37 UTC, devbww reviewed
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656)* status: all files reviewed, 3 unresolved discussions (waiting on @coryan and @scotthart)

___
*[`google/cloud/compute/BUILD.bazel` line 157 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656#-NeeDB9qDVV7sMDD0KwT:-NeeDB9r8Hf4e_fy2C3m:b-ct6vs9) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/843705fd3af66979eb37851b1c1790e2c3617fa3/google/cloud/compute/BUILD.bazel#L157)):*
> ```Starlark
> ] for service in service_dirs + operation_service_dirs]
> 
> [[
> ```

Why not do the same thing with these two loops?  Or, at least give the seconds loop its own "Foo targets" comment?


<!-- Sent from Reviewable.io -->

2023-09-18 21:43 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @coryan and @devbww)

___
*[`google/cloud/compute/BUILD.bazel` line 157 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656#-NeeDB9qDVV7sMDD0KwT:-NeeEoNK25zjUtgiGN1Z:b-qurihc) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/843705fd3af66979eb37851b1c1790e2c3617fa3/google/cloud/compute/BUILD.bazel#L157)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

Why not do the same thing with these two loops?  Or, at least give the seconds loop its own "Foo targets" comment?
</blockquote></details>

Added a comment. I prefer having some separation between the proto and C++ components of the BUILD file.


<!-- Sent from Reviewable.io -->

2023-09-18 22:16 UTC, devbww reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656)* status: all files reviewed, 1 unresolved discussion (waiting on @coryan)



<!-- Sent from Reviewable.io -->

2023-09-18 22:45 UTC, coryan approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12656)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @scotthart)



<!-- Sent from Reviewable.io -->

2023-09-18 22:47 UTC, merged