impl(bigquery): Project benchmark program
googleapis/google-cloud-cpp pull request #12685
Opened 2023-09-20 19:50 UTC by jsrinnn

This benchmark PR includes the following changes

1) A Project benchmark program that runs theListProject apis end to end based on input parameters 
and prints latency and throughput results. See the Project benchmark program output here: https://paste.googleplex.com/5685157741723648

2) Minor refactor of common time conversion method used by all benchmarks.

3) Added more information in `PrintThroughputResults()`.

3) Fixed the following issues related to parsing of json projects response, as exposed by benchmark tests:

- Fixed json parsing of 64-bit numbers being returned as json strings and corresponding unit tests.
- Fixed the validation logic in `valid_projects_list()` (e.g. "projects" field is not always returned. It may not be returned for the last page when "totalItems" field is 0)
- Fixed handling of Empty projects list returned in the response. This can happen if totalItems in the json response has a value of 0 i.e last page.

2023-09-20 22:25 UTC, coryan requested changes
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685)* status: all files reviewed, 4 unresolved discussions (waiting on @jsrinnn)

___
*[`google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc` line 97 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685#-NeoeHL_7qAiCtCmqRBr:-NeoeHL_7qAiCtCmqRBs:bdgortn) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4049cecf04c84c667aaadc09068086975f766f26/google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc#L97)):*
> ```cpp
> std::time_t ConvertSteadyClockToTime(std::chrono::steady_clock::time_point t) {
>   return system_clock::to_time_t(
>       std::chrono::system_clock::now() +
> ```

Both calls to `now()` happen at different times and return a different "now".

I think you want to report wall clock time, then `steady_clock` is not the way to go, just use `std::chrono::system_clock` for that purpose.
___
*[`google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc` line 124 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685#-NeofQAw53MYGqk_gMYL:-NeofQAw53MYGqk_gMYM:bpe0t9s) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4049cecf04c84c667aaadc09068086975f766f26/google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc#L124)):*
> ```cpp
>       std::time_t now_t = ConvertSteadyClockToTime(now);
>       std::time_t mark_t = ConvertSteadyClockToTime(mark);
>       std::cout << "Start Time=" << std::ctime(&start_t)
> ```

 `std::ctime()` is not thread safe.  I would use some `absl::` function instead.
___
*[`google/cloud/bigquery/v2/minimal/benchmarks/project_benchmark_programs.cc` line 110 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685#-NeofmaIBp-pvamicHRr:-NeofmaIBp-pvamicHRs:bi47p4s) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4049cecf04c84c667aaadc09068086975f766f26/google/cloud/bigquery/v2/minimal/benchmarks/project_benchmark_programs.cc#L110)):*
> ```cpp
>       std::time_t mark_t = ConvertSteadyClockToTime(mark);
>       std::time_t now_t = ConvertSteadyClockToTime(now);
>       std::cout << "Start Time=" << std::ctime(&start_t)
> ```

In this context it absolutely matters.  `std::ctime` returns a pointer to a global variable, which is changed by any other thread calling `std::ctime()`.  Please use `absl::` time functions.
___
*[`google/cloud/bigquery/v2/minimal/internal/project_response.cc` line 72 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685#-NeogJG2EoIAXUre3ey3:-NeogJG2EoIAXUre3ey4:b-66yau) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4049cecf04c84c667aaadc09068086975f766f26/google/cloud/bigquery/v2/minimal/internal/project_response.cc#L72)):*
> ```cpp
>   }
> 
>   if (result.total_items > 0) {
> ```

maybe `if (result.total_items == 0) return result;` ? 


<!-- Sent from Reviewable.io -->

2023-09-21 21:54 UTC, jsrinnn reviewed
Addressed all feedback. Thank you Carlos!

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685#-:-NetRx8s5InQWTdg7AB-:btaox6u)* status: all files reviewed, 4 unresolved discussions (waiting on @coryan)

___
*[`google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc` line 97 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685#-NeoeHL_7qAiCtCmqRBr:-NetLQoDBLsz6XQbxN53:bcohhxj) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/9deb8ec94663faac31cebfdf9aa4c6497a599def/google/cloud/bigquery/v2/minimal/benchmarks/benchmark.cc#L97)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Both calls to `now()` happen at different times and return a different "now".

I think you want to report wall clock time, then `steady_clock` is not the way to go, just use `std::chrono::system_clock` for that purpose.
</blockquote></details>

Done.  

Makes sense. Thanks.
___
*[`google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc` line 124 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685#-NeofQAw53MYGqk_gMYL:-NetQLzBBMvrmr1aaTi5:boyexbg) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/9deb8ec94663faac31cebfdf9aa4c6497a599def/google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc#L124)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

`std::ctime()` is not thread safe.  I would use some `absl::` function instead.
</blockquote></details>

Done. Thanks.
___
*[`google/cloud/bigquery/v2/minimal/benchmarks/project_benchmark_programs.cc` line 110 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685#-NeofmaIBp-pvamicHRr:-NetQ_xI6XoIAHaLBFLs:bj1gr5n) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/9deb8ec94663faac31cebfdf9aa4c6497a599def/google/cloud/bigquery/v2/minimal/benchmarks/project_benchmark_programs.cc#L110)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

In this context it absolutely matters.  `std::ctime` returns a pointer to a global variable, which is changed by any other thread calling `std::ctime()`.  Please use `absl::` time functions.
</blockquote></details>

Done.

Got it. Replaced with absl::FormatTime functions
___
*[`google/cloud/bigquery/v2/minimal/internal/project_response.cc` line 72 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685#-NeogJG2EoIAXUre3ey3:-NetRnjF7OrjTSaV4osp:bakfd2l) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/9deb8ec94663faac31cebfdf9aa4c6497a599def/google/cloud/bigquery/v2/minimal/internal/project_response.cc#L72)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

maybe `if (result.total_items == 0) return result;` ?
</blockquote></details>

Done.

Semantically both are same but this seems a tad cleaner so I made the change.


<!-- Sent from Reviewable.io -->

2023-09-21 23:06 UTC, devbww commented on google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc
> +                << absl::FormatTime(start_time, absl::LocalTimeZone())
`absl::LocalTimeZone()` deserves to be factored out to a single location.

2023-09-21 23:06 UTC, devbww commented on google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc
> +                << std::endl
Do we really need to flush every line?

2023-09-22 13:09 UTC, coryan reviewed
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685)* status: all files reviewed, 3 unresolved discussions (waiting on @devbww and @jsrinnn)

___
*[`google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc` line 120 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685#gh-1333676456:-Newz2BrCsv6aGpdVjEb:b6m39fs) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2ade3f0fbf3a97e352c3edb219c39fb4da554bcb/google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc#L120)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

I would suggest, if you're going to use Abseil time at all, that you should use it exclusively, and forget about chrono and time_t along with all the requisite conversions.
</blockquote></details>

That makes sense to me too.  In general, we prefer to use `std::chrono` in public APIs, but have no objection to using `absl::*` for implementation details.

In the computers and time scales we care about, there is no practical difference between `std::steady_clock` and `std::system_clock` and `absl::Now()`: GCE instances (and Google development workstations) smear time changes.  Both clocks can measure slightly different intervals, but these differences are in seconds per day.  For your measurements it is unlikely that will matter: the noise introduced by scheduling and network effects will be bigger.


<!-- Sent from Reviewable.io -->

2023-09-22 16:36 UTC, jsrinnn reviewed
Addressed all feedback. Thank You, Bradley and Carlos!

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685#-:-NexGgQB53FYOV10i3lH:bdo4fp0)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @devbww)

___
*[`google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc` line 120 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685#gh-1333676456:-NexC4Is0YoSJ9-vYsTu:b-3kwtq) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2ade3f0fbf3a97e352c3edb219c39fb4da554bcb/google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc#L120)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

That makes sense to me too.  In general, we prefer to use `std::chrono` in public APIs, but have no objection to using `absl::*` for implementation details.

In the computers and time scales we care about, there is no practical difference between `std::steady_clock` and `std::system_clock` and `absl::Now()`: GCE instances (and Google development workstations) smear time changes.  Both clocks can measure slightly different intervals, but these differences are in seconds per day.  For your measurements it is unlikely that will matter: the noise introduced by scheduling and network effects will be bigger.
</blockquote></details>

Done.

I have converted everything in the main benchmark porgram to use absl instead of chrono. I have done this for all the benchmark programs. However there are dependent classes/libraries that use chrono and I have not changed those. In those (few) cases I have used the `absl::ToChrono*` and `absl::FromChrono*` methods where necessary.
___
*[`google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc` line 130 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685#gh-1333679971:-NexCj6mB-B3ocunlsSa:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2ade3f0fbf3a97e352c3edb219c39fb4da554bcb/google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc#L130)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

`absl::LocalTimeZone()` deserves to be factored out to a single location.
</blockquote></details>

Done.
___
*[`google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc` line 131 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685#gh-1333680385:-Nex80Yd7iJhrewP0YYk:b-z3d4is) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2ade3f0fbf3a97e352c3edb219c39fb4da554bcb/google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc#L131)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

Do we really need to flush every line?
</blockquote></details>

Its not every line. Its basically progress reporting on calls made after a certain time has progressed. Especially makes sense when the test duration is long.


<!-- Sent from Reviewable.io -->

2023-09-22 16:47 UTC, coryan approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685)* status: all files reviewed, 3 unresolved discussions (waiting on @devbww)



<!-- Sent from Reviewable.io -->

2023-09-22 16:51 UTC, jsrinnn reviewed
I went ahead and enabled auto merge (after Carlos approval) in order to make forward progress.

Bradley, if there are additional action items for me please let me know and I can address them in a separate PR.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685#-:-NexnBG4072oyItjqqI-:b-gy1nx)* status: all files reviewed, 3 unresolved discussions (waiting on @devbww)



<!-- Sent from Reviewable.io -->

2023-09-22 17:10 UTC, devbww approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685)* status: all files reviewed, 1 unresolved discussion (waiting on @jsrinnn)

___
*[`google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc` line 131 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685#gh-1333680385:-Nexpm7TDbjla-pb8J12:b-rfi8h6) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2ade3f0fbf3a97e352c3edb219c39fb4da554bcb/google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc#L131)):*
<details><summary><i>Previously, jsrinnn wrote…</i></summary><blockquote>

Its not every line. Its basically progress reporting on calls made after a certain time has progressed. Especially makes sense when the test duration is long.
</blockquote></details>

It looks like it is every line.  For example, I count five `std::endl`s in this statement, and another one in the next, but no non-flushing `'\n'`s among them.

I'm all for a strategically placed flush if it helps when writing to a buffered output stream, but it seems like this is overkill.

Anyway, think about it and perhaps you can loop back later if you agree that the repeated flushing is too much.


<!-- Sent from Reviewable.io -->

2023-09-22 17:14 UTC, jsrinnn reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685)* status: all files reviewed, 1 unresolved discussion (waiting on @devbww)

___
*[`google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc` line 131 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12685#gh-1333680385:-Nexs6_Z27ufSLNc9dNt:bd0k2sd) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2ade3f0fbf3a97e352c3edb219c39fb4da554bcb/google/cloud/bigquery/v2/minimal/benchmarks/dataset_benchmark_programs.cc#L131)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

It looks like it is every line.  For example, I count five `std::endl`s in this statement, and another one in the next, but no non-flushing `'\n'`s among them.

I'm all for a strategically placed flush if it helps when writing to a buffered output stream, but it seems like this is overkill.

Anyway, think about it and perhaps you can loop back later if you agree that the repeated flushing is too much.
</blockquote></details>

Ah..sorry. My bad. I understood your comment to mean will it print out at every iteration of the loop.

Got it. I can replace `std::endl` with `\n` in my followup PR.

 Also my ignorance that I assumed  "\n" and "endl" were equivalend :)


<!-- Sent from Reviewable.io -->

2023-09-22 18:07 UTC, merged