impl(generator): add non-path fields as query parameters
googleapis/google-cloud-cpp pull request #12721
Opened 2023-09-25 20:00 UTC by scotthart

So we used to transcode the entire request proto in json. This worked for some cases but not all, so we then built the query path from some of the fields in the proto and transcode the "resource' field into the json request body. In the process, we dropped fields that should have been query params on the floor for non-GET http methods. This PR reinstates those non-path, non-resource fields as query parameters.

Sending empty query parameters is an error for Compute methods, so we make sure to omit them.

The accompanying integration test verifies the query parameter is being passed, but not a successful update. This is do to the lack of update methods for easily configurable test resources in compute.

2023-09-25 21:09 UTC, coryan approved these changes

2023-09-25 23:23 UTC, scotthart commented
Added code to not emit deprecated fields as query parameters.

2023-09-26 12:18 UTC, coryan requested changes
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12721)* status: 3 of 114 files reviewed, 1 unresolved discussion (waiting on @scotthart)

___
*[`generator/internal/http_option_utils.cc` line 183 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12721#-NfGOseLDHnxtXrPPRBq:-NfGOseLDHnxtXrPPRBr:bd6w9da) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/567158ad1becdac1ae941f7cabeb6a8eeeda3003/generator/internal/http_option_utils.cc#L183)):*
> ```cpp
>           if (!internal::Contains(param_field_names, field->name())) {
>             if (!field->options().deprecated()) {
>               remaining_request_fields.emplace_back(field->name(),
> ```

We are three levels deep in `if (a) { if (b) { if (c) {`. Maybe a helper function or lambda that can return early?  Or maybe use `if (!a) continue; if (!b) continue; ...`.  Or if all else fails `if (a && b && c)`



_Suggestion:_
```cpp
          if (!internal::Contains(param_field_names, field->name())
              && !field->options().deprecated()) {
              remaining_request_fields.emplace_back(field->name(),
```


<!-- Sent from Reviewable.io -->

2023-09-26 16:53 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12721)* status: 3 of 114 files reviewed, 1 unresolved discussion (waiting on @coryan)

___
*[`generator/internal/http_option_utils.cc` line 183 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12721#-NfGOseLDHnxtXrPPRBq:-NfHP1AZ9TzFOfSQqXlW:btga1x7) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/567158ad1becdac1ae941f7cabeb6a8eeeda3003/generator/internal/http_option_utils.cc#L183)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

We are three levels deep in `if (a) { if (b) { if (c) {`. Maybe a helper function or lambda that can return early?  Or maybe use `if (!a) continue; if (!b) continue; ...`.  Or if all else fails `if (a && b && c)`
</blockquote></details>

Combined the field checks into one compound AND condition, such that we reduce the more expensive calls to `Contains`.


<!-- Sent from Reviewable.io -->

2023-09-26 17:26 UTC, coryan approved these changes
> Reviewed 110 of 114 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12721)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @scotthart)

___
*[`generator/internal/http_option_utils.cc` line 183 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12721#-NfGOseLDHnxtXrPPRBq:-NfHWXo9-sSPZucqGv67:b-efx8xy) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/567158ad1becdac1ae941f7cabeb6a8eeeda3003/generator/internal/http_option_utils.cc#L183)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Combined the field checks into one compound AND condition, such that we reduce the more expensive calls to `Contains`.
</blockquote></details>

nit: `&&` short circuits in C++, you can remove one more `if()` level.


<!-- Sent from Reviewable.io -->

2023-09-26 20:41 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12721)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @scotthart)

___
*[`generator/internal/http_option_utils.cc` line 183 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12721#-NfGOseLDHnxtXrPPRBq:-NfIDHMg5XJoKj2aRXZv:b-gt7fdu) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/567158ad1becdac1ae941f7cabeb6a8eeeda3003/generator/internal/http_option_utils.cc#L183)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: `&&` short circuits in C++, you can remove one more `if()` level.
</blockquote></details>

I thought about it, but figured this was slightly more readable.


<!-- Sent from Reviewable.io -->

2023-09-26 20:41 UTC, merged