fix: Use default values
googleapis/google-cloud-cpp pull request #12988
Opened 2023-10-27 08:04 UTC by MeilakhSiarhei

Default values of these fields are empty strings.
BQ API doesn't accept empty strings, according to documentation these fields are enums.
`location` is not enum according to documentation, but it works similar - only valid location is accepted.

2023-10-27 12:14 UTC, coryan commented on google/cloud/bigquery/v2/minimal/internal/job.h
> -  std::string location;
It may be better to leave this empty and get an error than to fill-in `"US"` and surprise a caller with the wrong behavior.

2023-10-27 12:14 UTC, coryan commented on google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h
> -  KeyResultStatementKind key_result_statement;
What does the service do with `::UnSpecified()`?  Does it also fail like with an empty value?  If so, I would just not bother.  If it works then this is worthwhile.

2023-10-27 12:14 UTC, coryan commented
/gcbrun

2023-10-27 16:08 UTC, coryan commented
/gcbrun

2023-10-30 10:26 UTC, MeilakhSiarhei reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12988)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @coryan)

___
*[`google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h` line 0 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12988#gh-1374488208:-Ni-4vSwA6nu5IC94c0l:bm3r775) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1b3c597dd8d5d1be032534cc672fec73e0b5462f/google/cloud/bigquery/v2/minimal/internal/common_v2_resources.h#L0)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map [this GitHub inline comment thread](https://github.com/googleapis/google-cloud-cpp/pull/12988#discussion_r1374488208) to the right spot — sorry!)*

What does the service do with `::UnSpecified()`?  Does it also fail like with an empty value?  If so, I would just not bother.  If it works then this is worthwhile.

</blockquote></details>

It fails only with empty string. Documentation specifies only 3 possible options for enum (in general). For example:
https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#keyresultstatementkind
And it fails if the value is not one of them.
Changing an empty string to `::UnSpecified()` fixes it. Basically it works similar to if this field was absent in json.
https://screenshot.googleplex.com/AAYdU9mCMtcoGWc
https://screenshot.googleplex.com/3Gyrurch5WjT7bL
___
*[`google/cloud/bigquery/v2/minimal/internal/job.h` line 0 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12988#gh-1374486630:-Ni-5eUr4StczB7bAvfH:b-p9lugm) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1b3c597dd8d5d1be032534cc672fec73e0b5462f/google/cloud/bigquery/v2/minimal/internal/job.h#L0)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map [this GitHub inline comment thread](https://github.com/googleapis/google-cloud-cpp/pull/12988#discussion_r1374486630) to the right spot — sorry!)*

It may be better to leave this empty and get an error than to fill-in `"US"` and surprise a caller with the wrong behavior.
</blockquote></details>

According to documentation, `US` is default option.
https://cloud.google.com/bigquery/docs/reference/rest/v2/JobReference
Only empty string (or any random, not recognized location like `custom_location`) fails the BQ API request validation check.
Putting `US` here works similar to if this field was absent in json. If the user fill some custom location - the error is expected. But I believe default behavior should not raise it.
https://screenshot.googleplex.com/AAYdU9mCMtcoGWc
https://screenshot.googleplex.com/3Gyrurch5WjT7bL


<!-- Sent from Reviewable.io -->

2023-10-30 10:27 UTC, MeilakhSiarhei commented
I fixed one unit test, so I hope now all checks should pass.

2023-10-30 12:32 UTC, coryan commented
/gcbrun

2023-10-30 13:26 UTC, MeilakhSiarhei commented
I fixed formatting.

2023-10-30 14:01 UTC, coryan commented
/gcbrun

2023-10-30 16:39 UTC, coryan requested changes
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12988)* status: all files reviewed, 1 unresolved discussion (waiting on @jsrinnn)

___
*[`google/cloud/bigquery/v2/minimal/internal/job.h` line 0 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12988#gh-1374486630:-Ni0RVIs9OvAfOJgetAq:be2vz9u) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1b3c597dd8d5d1be032534cc672fec73e0b5462f/google/cloud/bigquery/v2/minimal/internal/job.h#L0)):*
> Only empty string (or any random, not recognized location like `custom_location`) fails the BQ API request validation check.  

Okay.

> Putting `US` here works similar to if this field was absent in json. 

So now we have two places that define the default behavior.  The client library and the service.  What happens if the service ever changes to "processes running in Europe will default to EU" or something similar?

> But I believe default behavior should not raise it.  

@jsrinnn maybe y'all should consider omitting the field if it is the empty string.  That will yield the default behavior without duplicating the source of truth.


<!-- Sent from Reviewable.io -->

2023-10-30 16:40 UTC, MeilakhSiarhei commented
I close this PR as it fixes the issue only partially.
Full fix (making the library smart enough to populate json with only required values) is going to take too much time. It can be done in future.

2023-10-30 16:40 UTC, closed without merging