impl: add DetermineServiceEndpoint function
googleapis/google-cloud-cpp pull request #13123
Opened 2023-11-13 20:21 UTC by scotthart

fixes #13118

2023-11-13 20:34 UTC, dbolduc commented on google/cloud/internal/service_endpoint.cc
> +  if (endpoint_option.has_value()) return *endpoint_option;
I think the plan is to call `DetermineServiceEndpoint` in the stub factory function. By that point the `EndpointOption` has already been defaulted, and will always have a value. So I think we would always break here.

https://github.com/googleapis/google-cloud-cpp/blob/4523a0a2b9ba461289c8f463ef0c1f65838e360d/google/cloud/accessapproval/v1/access_approval_connection.cc#L105-L106

2023-11-13 20:38 UTC, dbolduc commented on google/cloud/internal/service_endpoint.cc
> +  if (endpoint_option.has_value()) return *endpoint_option;
Can we modify `PopulateCommonOptions` to incorporate `UniverseDomainOption` ?

https://github.com/googleapis/google-cloud-cpp/blob/4523a0a2b9ba461289c8f463ef0c1f65838e360d/google/cloud/internal/populate_common_options.cc#L27

2023-11-13 20:41 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dbolduc)

___
*[`google/cloud/internal/service_endpoint.cc` line 33 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1391673523:-Nj9OkQOCnx8sAEmxuhM:bgpnsz3) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5d6fba4a4f484eb31e40a6178893206e4994a87e/google/cloud/internal/service_endpoint.cc#L33)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

Can we modify `PopulateCommonOptions` to incorporate `UniverseDomainOption` ?

https://github.com/googleapis/google-cloud-cpp/blob/4523a0a2b9ba461289c8f463ef0c1f65838e360d/google/cloud/internal/populate_common_options.cc#L27
</blockquote></details>

I would prefer to remove the EndpointOption processing in PopulateCommonOptions and handle it in this new function. One reason for that is this new function will be used with more than just `EndpointOption`. There are a few places in the REST code paths and authentication that need have different named options/env vars  but require the same resolution process.


<!-- Sent from Reviewable.io -->

2023-11-13 20:52 UTC, dbolduc commented
> There are a few places [... that] require the same resolution process.

Ah, thanks. I am guessing `AuthorityOption` needs the same treatment too.

> update `PopulateCommonOptions` after all the service work has been completed.

So the plan is to refactor `PopulateCommonOptions()` to call this thing? If so, I think we should refactor now.

2023-11-13 20:59 UTC, devbww commented on google/cloud/internal/service_endpoint_test.cc
> +TEST(DetermineServiceEndpoint, EndpointOptionSet) {
This and the following tests should probably be surrounded by...
```
  ScopedEnvironment("GOOGLE_CLOUD_CPP_FOO_SERVICE_ENDPOINT", absl::nullopt);
```
But, better yet, don't bother setting/getting environment variables at all ... just pass appropriate `absl::optional<std::string>` values to the code under test.

2023-11-13 20:59 UTC, devbww commented on google/cloud/internal/service_endpoint.h
> +// UniverseDomainOption is contained in options, then the respective endpoint is
s/respective //

2023-11-13 20:59 UTC, devbww commented on google/cloud/internal/service_endpoint.h
> +    std::string default_host);
s/default_host/default_endpoint/?

2023-11-13 20:59 UTC, devbww commented on google/cloud/internal/service_endpoint.cc
> +// TODO(#13122): This function may need to be enhanced to support a env var
s/a env var/an env var/

2023-11-13 21:01 UTC, scotthart reviewed
Whatever endpoint related options are being set in `PopulateCommonOptions` will be removed. In the specific places we need to adjudicate an endpoint based on env vars, endpoint options, universe domain options, and default endpoint names, `DetermineServiceEndpoint` will be called. Because of the new universe domain requirements, we need to be able to handle error cases in this process which other common options do not require. Additionally, I would prefer to have exactly one implementation of this logic.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-:-Nj9T8BR88vu0F6EmH26:b5wjab)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @dbolduc and @devbww)



<!-- Sent from Reviewable.io -->

2023-11-13 21:09 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @dbolduc and @devbww)

___
*[`google/cloud/internal/service_endpoint.h` line 31 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1391697468:-Nj9VuVO1s4PzSaT2ZBb:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5d6fba4a4f484eb31e40a6178893206e4994a87e/google/cloud/internal/service_endpoint.h#L31)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

s/respective //
</blockquote></details>

Done.
___
*[`google/cloud/internal/service_endpoint.h` line 41 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1391698131:-Nj9Vup17ofY4YLQPKnD:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5d6fba4a4f484eb31e40a6178893206e4994a87e/google/cloud/internal/service_endpoint.h#L41)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

s/default_host/default_endpoint/?
</blockquote></details>

Done.
___
*[`google/cloud/internal/service_endpoint.cc` line 25 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1391698499:-Nj9VvIk3DtU7aKr1-Ih:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5d6fba4a4f484eb31e40a6178893206e4994a87e/google/cloud/internal/service_endpoint.cc#L25)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

s/a env var/an env var/
</blockquote></details>

Done.
___
*[`google/cloud/internal/service_endpoint_test.cc` line 47 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1391696339:-Nj9VwCHE3PU0ekntR7V:bk7y5oq) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5d6fba4a4f484eb31e40a6178893206e4994a87e/google/cloud/internal/service_endpoint_test.cc#L47)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

This and the following tests should probably be surrounded by...
```
  ScopedEnvironment("GOOGLE_CLOUD_CPP_FOO_SERVICE_ENDPOINT", absl::nullopt);
```
But, better yet, don't bother setting/getting environment variables at all ... just pass appropriate `absl::optional<std::string>` values to the code under test.
</blockquote></details>

While not strictly necessary, I wanted the usages appearing in these test cases to mimic how they would be called in the actual service code.


<!-- Sent from Reviewable.io -->

2023-11-13 21:20 UTC, devbww reviewed
> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123)* status: all files reviewed, 2 unresolved discussions (waiting on @dbolduc and @scotthart)

___
*[`google/cloud/internal/service_endpoint_test.cc` line 47 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1391696339:-Nj9Xxdn-tRgaktfxPIl:b-lnhv1) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5d6fba4a4f484eb31e40a6178893206e4994a87e/google/cloud/internal/service_endpoint_test.cc#L47)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

While not strictly necessary, I wanted the usages appearing in these test cases to mimic how they would be called in the actual service code.
</blockquote></details>

I'm not sure why that's a goal ... testing the interface directly would be simpler/clearer.  But OK, add the environment setting then.


<!-- Sent from Reviewable.io -->

2023-11-13 21:31 UTC, dbolduc reviewed
> Whatever endpoint related options are being set in `PopulateCommonOptions` will be removed.

Ok, I see the plan now. Sorry I made you say it twice. It was not obvious to me and I did not see anything about where (or whether) we default endpoint-type options in the design doc.

I would just caution that removing a suite of tests and adding a brand new suite of tests can be slightly more error prone than doing a refactor, verifying that the current tests are still passing, then removing the old code. Is that argument compelling at all? (Fine if no.)

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-:-Nj9ZHLnDVjszYX1Ik0S:bmca8th)* status: all files reviewed, 4 unresolved discussions (waiting on @scotthart)

___
*[`google/cloud/internal/service_endpoint.cc` line 36 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-Nj9XXhf6vHmiiQF2T7_:-Nj9XXhf6vHmiiQF2T7a:b-xiuwrx) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a1720efa84a7899cbb1ca2939078a86fc43f4f7f/google/cloud/internal/service_endpoint.cc#L36)):*
> ```cpp
>   if (options.has<UniverseDomainOption>()) {
>     std::string universe_domain_option = options.get<UniverseDomainOption>();
>     if (universe_domain_option.empty()) {
> ```

I think this function should return a `std::string`. What does this check buy us?

Applications should always be using the result of `GetUniverseDomain()`, which should either be a `Status` or non-empty, right?
```cc
Options options;
auto universe_domain = GetUniverseDomain(...);
if (!universe_domain) throw "bad UD!";
options.set<UniverseDomainOption>(universe_domain);
```

We do not check that `EndpointOption` is empty before using it, for example.
___
*[`google/cloud/internal/service_endpoint_test.cc` line 34 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-Nj9_Vu34iDzkBbgzq2F:-Nj9_Vu34iDzkBbgzq2G:bgceku5) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a1720efa84a7899cbb1ca2939078a86fc43f4f7f/google/cloud/internal/service_endpoint_test.cc#L34)):*
> ```cpp
> using ::testing::HasSubstr;
> 
> auto constexpr kDefaultHost = "default_host.googleapis.com";
> ```

nit: If we changed the parameter to `default_endpoint`, we should probably `s/DefaultHost/DefaultEndpoint/g`


<!-- Sent from Reviewable.io -->

2023-11-14 13:35 UTC, coryan requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123)* status: all files reviewed, 4 unresolved discussions (waiting on @dbolduc, @devbww, and @scotthart)

___
*[`google/cloud/internal/service_endpoint.cc` line 38 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-NjD1LRk1-3fIswBWovf:-NjD1LRk1-3fIswBWovg:b2uujgi) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a1720efa84a7899cbb1ca2939078a86fc43f4f7f/google/cloud/internal/service_endpoint.cc#L38)):*
> ```cpp
>     if (universe_domain_option.empty()) {
>       return internal::InvalidArgumentError(
>           "UniverseDomainOption can not be empty");
> ```

Where is this error going to go?  Eventually this is all used to initialize a `FooConnection` and the application won't be receiving the error.
___
*[`google/cloud/internal/service_endpoint.cc` line 41 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-NjD06YT21mCMY78Sq4d:-NjD06YT21mCMY78Sq4e:b-gtarsk) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a1720efa84a7899cbb1ca2939078a86fc43f4f7f/google/cloud/internal/service_endpoint.cc#L41)):*
> ```cpp
>     }
>     return absl::StrReplaceAll(
>         default_endpoint, {{kGoogleDefaultUniverse, universe_domain_option}});
> ```

This also the universe domain in  `foo.googleapis.com.some-future-domain.net` I am not sure that can happen, but I am sure it is not desirable to do this blind replacement if it does happen.  Maybe add a comment explaining that we think this is "impossible".
___
*[`google/cloud/internal/service_endpoint_test.cc` line 47 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1391696339:-NjD0qQz-D-f0b0rYxqs:b-8al45r) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5d6fba4a4f484eb31e40a6178893206e4994a87e/google/cloud/internal/service_endpoint_test.cc#L47)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

I'm not sure why that's a goal ... testing the interface directly would be simpler/clearer.  But OK, add the environment setting then.
</blockquote></details>

Test code is code that we need to maintain too.  Adding complexity here is no helpful for the future.  Please remove the environment variable stuff and test the function.


<!-- Sent from Reviewable.io -->

2023-11-14 18:39 UTC, scotthart reviewed
It is a compelling argument, and I acknowledge the increased risk, but I'm not sure it's avoidable at this time. The addition of this universe domain feature is definitely disruptive as it upends one of our previous assumptions regarding when in the code flow that we know the hostname of the remote connection.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-:-NjE60DY6mNTluMgpHrQ:b-htgckt)* status: all files reviewed, 4 unresolved discussions (waiting on @coryan, @dbolduc, and @devbww)

___
*[`google/cloud/internal/service_endpoint.cc` line 36 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-Nj9XXhf6vHmiiQF2T7_:-NjE4nZiARCEv1l2SvZN:bx9uje7) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a1720efa84a7899cbb1ca2939078a86fc43f4f7f/google/cloud/internal/service_endpoint.cc#L36)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

I think this function should return a `std::string`. What does this check buy us?

Applications should always be using the result of `GetUniverseDomain()`, which should either be a `Status` or non-empty, right?
```cc
Options options;
auto universe_domain = GetUniverseDomain(...);
if (!universe_domain) throw "bad UD!";
options.set<UniverseDomainOption>(universe_domain);
```

We do not check that `EndpointOption` is empty before using it, for example.
</blockquote></details>

Applications should use that result, but we cannot force them to. Until the user passes their pack of Options to MakeConnection, they can mutate them however they choose. Only after the call to MakeConnection can we perform any checks. Whether or not we should check EndpointOption is out of scope for this feature.
___
*[`google/cloud/internal/service_endpoint.cc` line 38 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-NjD1LRk1-3fIswBWovf:-NjE5HlK-Xi3fFp77dNj:bzi8og4) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a1720efa84a7899cbb1ca2939078a86fc43f4f7f/google/cloud/internal/service_endpoint.cc#L38)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Where is this error going to go?  Eventually this is all used to initialize a `FooConnection` and the application won't be receiving the error.
</blockquote></details>

Per the design document, if DetermineServiceEndpoint returns an error status, we then create an ErrorCredentialsConfig with that status and leverage the auth decorator the return that error on all rpc class made with the Connection.
___
*[`google/cloud/internal/service_endpoint.cc` line 41 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-NjD06YT21mCMY78Sq4d:-NjE5_GOEuTeKyuJihc-:b-iilc08) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a1720efa84a7899cbb1ca2939078a86fc43f4f7f/google/cloud/internal/service_endpoint.cc#L41)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This also the universe domain in  `foo.googleapis.com.some-future-domain.net` I am not sure that can happen, but I am sure it is not desirable to do this blind replacement if it does happen.  Maybe add a comment explaining that we think this is "impossible".
</blockquote></details>

Updated the code to only replace "googleapis.com" if it's the suffix.
___
*[`google/cloud/internal/service_endpoint_test.cc` line 47 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1391696339:-NjE5tWoC43F51TnEY0B:bss4a2b) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5d6fba4a4f484eb31e40a6178893206e4994a87e/google/cloud/internal/service_endpoint_test.cc#L47)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Test code is code that we need to maintain too.  Adding complexity here is no helpful for the future.  Please remove the environment variable stuff and test the function.
</blockquote></details>

Removed.
___
*[`google/cloud/internal/service_endpoint_test.cc` line 34 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-Nj9_Vu34iDzkBbgzq2F:-NjE5s5hBcxi7-H-YIhr:b-bw8e14) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a1720efa84a7899cbb1ca2939078a86fc43f4f7f/google/cloud/internal/service_endpoint_test.cc#L34)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

nit: If we changed the parameter to `default_endpoint`, we should probably `s/DefaultHost/DefaultEndpoint/g`
</blockquote></details>

Updated.


<!-- Sent from Reviewable.io -->

2023-11-14 18:41 UTC, scotthart reviewed
Additionally, I think we can preserve the ability to retrieve the EndpointOption value from the Connection::options by passing an Options& instead of Options const& to CreateDefaultStub

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-:-NjE7dTp6RAEcmiL-_Hc:bzb0t5w)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @coryan, @dbolduc, and @devbww)



<!-- Sent from Reviewable.io -->

2023-11-14 18:50 UTC, coryan approved these changes
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123)* status: all files reviewed, 4 unresolved discussions (waiting on @dbolduc and @devbww)

___
*[`google/cloud/internal/service_endpoint.cc` line 38 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-NjD1LRk1-3fIswBWovf:-NjE8vK9Au4lcWsDRBEx:bawz0vz) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a1720efa84a7899cbb1ca2939078a86fc43f4f7f/google/cloud/internal/service_endpoint.cc#L38)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Per the design document, if DetermineServiceEndpoint returns an error status, we then create an ErrorCredentialsConfig with that status and leverage the auth decorator the return that error on all rpc class made with the Connection.
</blockquote></details>

I assume there will be other error conditions, because it is tempting to just ignore empty values and treat those as `googleapis.com`.
___
*[`google/cloud/internal/service_endpoint.cc` line 41 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-NjD06YT21mCMY78Sq4d:-NjE9BQu3KpmwyYpzlLL:b-bazjen) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a1720efa84a7899cbb1ca2939078a86fc43f4f7f/google/cloud/internal/service_endpoint.cc#L41)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Updated the code to only replace "googleapis.com" if it's the suffix.
</blockquote></details>

I should have thought of this too: `foo.googleapis.com.` (with a final period) is perfectly valid.  and `universe_domain` = `somewhere-else.com.` is also possible.


<!-- Sent from Reviewable.io -->

2023-11-14 20:54 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123)* status: all files reviewed, 4 unresolved discussions (waiting on @dbolduc and @devbww)

___
*[`google/cloud/internal/service_endpoint.cc` line 38 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-NjD1LRk1-3fIswBWovf:-NjEJu_-9NSC6aj6hNIg:bwfftrm) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a1720efa84a7899cbb1ca2939078a86fc43f4f7f/google/cloud/internal/service_endpoint.cc#L38)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I assume there will be other error conditions, because it is tempting to just ignore empty values and treat those as `googleapis.com`.
</blockquote></details>

Additional error conditions are planned.
___
*[`google/cloud/internal/service_endpoint.cc` line 41 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-NjD06YT21mCMY78Sq4d:-NjEK1Cw2o2Vxh_Ta3Fo:bhia8u5) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a1720efa84a7899cbb1ca2939078a86fc43f4f7f/google/cloud/internal/service_endpoint.cc#L41)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I should have thought of this too: `foo.googleapis.com.` (with a final period) is perfectly valid.  and `universe_domain` = `somewhere-else.com.` is also possible.
</blockquote></details>

Updated to handle trailing `.` in universe domain option.
Updated to ensure default_endpoint always has a trailing `.`.


<!-- Sent from Reviewable.io -->

2023-11-15 04:19 UTC, devbww commented on google/cloud/internal/service_endpoint.h
> +// by replacing the googleapis.com string in the default_host value with the
s/default_host/default_endpoint/

2023-11-15 04:19 UTC, devbww commented on google/cloud/internal/service_endpoint.h
> +//      "${service}.googleapis.com");
Make it fully qualified?

2023-11-15 04:19 UTC, devbww commented on google/cloud/internal/service_endpoint.cc
> +        universe_domain_option);
"foo.bargoogleapis.com" would receive the wrong treatment.

2023-11-15 16:21 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123)* status: 3 of 6 files reviewed, 7 unresolved discussions (waiting on @coryan, @dbolduc, and @devbww)

___
*[`google/cloud/internal/service_endpoint.h` line 32 at r5](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1393614297:-NjIlSa1AMgF0LB8c7v2:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2bfa373d775e29eddc2ade908f77d411ab1e63bc/google/cloud/internal/service_endpoint.h#L32)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

s/default_host/default_endpoint/
</blockquote></details>

Done.
___
*[`google/cloud/internal/service_endpoint.h` line 37 at r5](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1393614609:-NjIlSrx8mDuii-LheCv:b-9clxt9) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2bfa373d775e29eddc2ade908f77d411ab1e63bc/google/cloud/internal/service_endpoint.h#L37)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

Make it fully qualified?
</blockquote></details>

This argument is the value of `option (google.api.default_host)` from the proto files, and is usually not qualified.
___
*[`google/cloud/internal/service_endpoint.cc` line 47 at r5](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1393616043:-NjIm7D0-VrNk9JgnkhN:bj3d48m) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2bfa373d775e29eddc2ade908f77d411ab1e63bc/google/cloud/internal/service_endpoint.cc#L47)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

"foo.bargoogleapis.com" would receive the wrong treatment.
</blockquote></details>

Added a check to verify the default_endpoint is in the "googleapis.com" universe, which it should always be as its sourced from the service proto file.


<!-- Sent from Reviewable.io -->

2023-11-15 16:45 UTC, devbww commented on google/cloud/internal/service_endpoint.cc
> +        absl::StrCat("default_endpoint is not in GDU: ", default_endpoint));
Nit:  Is it worth showing the user an acronym here, particular when (it seems) we're uncomfortable with `kGDU` in the code?

2023-11-15 16:55 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123)* status: 3 of 6 files reviewed, 8 unresolved discussions (waiting on @coryan, @dbolduc, and @devbww)

___
*[`google/cloud/internal/service_endpoint.cc` line 40 at r6](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1394477912:-NjIteIc4QlRIKV7L_eQ:b-mxaqcq) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8f48c3752eabf8291e4938e8e877c6d43efce586/google/cloud/internal/service_endpoint.cc#L40)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

Nit:  Is it worth showing the user an acronym here, particular when (it seems) we're uncomfortable with `kGDU` in the code?
</blockquote></details>

I didn't use `kGDU` in the code because style guide. I used the acronym in the error message as this message is intended for us. If the user receives this error message, there's nothing they can do to fix it other than file an issue.


<!-- Sent from Reviewable.io -->

2023-11-15 17:12 UTC, dbolduc submitted a review, later dismissed
I am convinced the function should return a `std::string` instead of a `StatusOr<std::string>`.

> Additionally, I think we can preserve the ability to retrieve the EndpointOption value from the Connection::options by passing an Options& instead of Options const& to CreateDefaultStub

SGTM. I am happy if preserving the `Connection::options()` is a goal.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-:-NjIws4k87dlx6NWR6Tp:b8a3q7e)* status: 3 of 6 files reviewed, 8 unresolved discussions (waiting on @coryan, @devbww, and @scotthart)

___
*[`google/cloud/internal/service_endpoint.cc` line 36 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-Nj9XXhf6vHmiiQF2T7_:-NjIudJZ1YxQE8l85e2M:br3x40m) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a1720efa84a7899cbb1ca2939078a86fc43f4f7f/google/cloud/internal/service_endpoint.cc#L36)):*
My point is that the empty string is not a special error, and we should not treat it as such. Please change.

> Whether or not we should check EndpointOption is out of scope for this feature.

Why not be consistent?
___
*[`google/cloud/internal/service_endpoint.cc` line 40 at r6](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1394477912:-NjIvFIwAp_pXlzI2m11:b-u91edk) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8f48c3752eabf8291e4938e8e877c6d43efce586/google/cloud/internal/service_endpoint.cc#L40)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

I didn't use `kGDU` in the code because style guide. I used the acronym in the error message as this message is intended for us. If the user receives this error message, there's nothing they can do to fix it other than file an issue.
</blockquote></details>

This does not seem like the place to check that the value of `default_endpoint` ends with `kGDU`. We could `assert(...)` in the generator and notice the default endpoint is weird during code generation time, instead of performing this check during run time.

(If I understand how this function is being used)


<!-- Sent from Reviewable.io -->

2023-11-15 17:24 UTC, scotthart reviewed
`DetermineServiceEndpoint` needs to return a `StatusOr<std::string>` to detect if the `UniverseDomainOption` is empty at the present time. In the future, `DetermineServiceEndpoint` will need to check for other possible errors.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-:-NjJ-KZm01gbNtbEwlwI:b-en57gl)* status: 3 of 6 files reviewed, 8 unresolved discussions (waiting on @coryan, @dbolduc, and @devbww)

___
*[`google/cloud/internal/service_endpoint.cc` line 36 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-Nj9XXhf6vHmiiQF2T7_:-NjIzol3BlIzQZeJxlfC:beakcp9) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a1720efa84a7899cbb1ca2939078a86fc43f4f7f/google/cloud/internal/service_endpoint.cc#L36)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

My point is that the empty string is not a special error, and we should not treat it as such. Please change.

> Whether or not we should check EndpointOption is out of scope for this feature.

Why not be consistent?
</blockquote></details>

There is a requirement that if the universe_domain is specified that it must not be empty. At present, no similar requirement exists for EndpointOption. If we feel that adding such a requirement for EndpointOption to be non-empty is a good idea, then we should do so in a separate issue/PR.
___
*[`google/cloud/internal/service_endpoint.cc` line 40 at r6](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1394477912:-NjIzKLN3momg404Hdm7:b-4dmh2u) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8f48c3752eabf8291e4938e8e877c6d43efce586/google/cloud/internal/service_endpoint.cc#L40)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

This does not seem like the place to check that the value of `default_endpoint` ends with `kGDU`. We could `assert(...)` in the generator and notice the default endpoint is weird during code generation time, instead of performing this check during run time.

(If I understand how this function is being used)
</blockquote></details>

There are code paths where this function is called outside of generated code. The default_endpoint should be a string ending in ".googleapis.com" such that we can substitute the universe_domain for it.


<!-- Sent from Reviewable.io -->

2023-11-15 17:36 UTC, dbolduc reviewed
> In the future, `DetermineServiceEndpoint` will need to check for other possible errors.

Oh. I was too short-sighted then. Sorry.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-:-NjJ1WZZ25NMUtYIUHX-:b-wzpyg7)* status: 3 of 6 files reviewed, 8 unresolved discussions (waiting on @coryan, @devbww, and @scotthart)

___
*[`google/cloud/internal/service_endpoint.cc` line 36 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-Nj9XXhf6vHmiiQF2T7_:-NjJ0uU9AwgN9LzMjFYI:b-mpcto8) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a1720efa84a7899cbb1ca2939078a86fc43f4f7f/google/cloud/internal/service_endpoint.cc#L36)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

There is a requirement that if the universe_domain is specified that it must not be empty. At present, no similar requirement exists for EndpointOption. If we feel that adding such a requirement for EndpointOption to be non-empty is a good idea, then we should do so in a separate issue/PR.
</blockquote></details>

Hm. I would say there is an implicit requirement that `EndpointOption` cannot be empty... If `EndpointOption` is empty none of the applications requests will work.

I still don't think the two options should be treated any differently. :shrug:
___
*[`google/cloud/internal/service_endpoint.cc` line 40 at r6](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1394477912:-NjJ1sNy7UCTQhkw3QR7:b80nbdc) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8f48c3752eabf8291e4938e8e877c6d43efce586/google/cloud/internal/service_endpoint.cc#L40)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

There are code paths where this function is called outside of generated code. The default_endpoint should be a string ending in ".googleapis.com" such that we can substitute the universe_domain for it.
</blockquote></details>

The code paths would be like `bigtable` hardcoding the value to `bigtable.googleapis.com`, right? If so, this function is not the place to check the default endpoint.


<!-- Sent from Reviewable.io -->

2023-11-15 17:50 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123)* status: 3 of 6 files reviewed, 8 unresolved discussions (waiting on @coryan, @dbolduc, and @devbww)

___
*[`google/cloud/internal/service_endpoint.cc` line 40 at r6](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1394477912:-NjJ4xAi291EO-ZDel_q:b-xatw9h) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8f48c3752eabf8291e4938e8e877c6d43efce586/google/cloud/internal/service_endpoint.cc#L40)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

The code paths would be like `bigtable` hardcoding the value to `bigtable.googleapis.com`, right? If so, this function is not the place to check the default endpoint.
</blockquote></details>

So should this function assume that the default endpoint always ends with ".googleapis.com" or ".googleapis.com."? If it doesn't then there's no definitive substring to swap out for the universe_domain.


<!-- Sent from Reviewable.io -->

2023-11-15 17:53 UTC, devbww reviewed
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123)* status: all files reviewed, 7 unresolved discussions (waiting on @coryan, @dbolduc, and @scotthart)

___
*[`google/cloud/internal/service_endpoint.cc` line 47 at r5](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1393616043:-NjJ5yqf5tJKeYBcC57A:b-gjp7ak) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2bfa373d775e29eddc2ade908f77d411ab1e63bc/google/cloud/internal/service_endpoint.cc#L47)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Added a check to verify the default_endpoint is in the "googleapis.com" universe, which it should always be as its sourced from the service proto file.
</blockquote></details>

Similar to above, it seems like this should be a build error instead.
___
*[`google/cloud/internal/service_endpoint.cc` line 40 at r6](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1394477912:-NjJ4q6rE--dlZxi_-dv:b-l74kxy) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8f48c3752eabf8291e4938e8e877c6d43efce586/google/cloud/internal/service_endpoint.cc#L40)):*
> I didn't use `kGDU` in the code because style guide.

So, presumably there is good reason for that.  I would assert that the same reason applies to the error message, whether the user is only forwarding it to us or not.  But, a small point.

In the bigger picture I agree with @dbolduc ... we should be able to guarantee that we have valid default endpoints long before a user is executing code.


<!-- Sent from Reviewable.io -->

2023-11-15 17:59 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123)* status: 4 of 6 files reviewed, 7 unresolved discussions (waiting on @coryan, @dbolduc, and @devbww)

___
*[`google/cloud/internal/service_endpoint.cc` line 40 at r6](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1394477912:-NjJ7gyqDZS36L1KERYn:b-m228js) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8f48c3752eabf8291e4938e8e877c6d43efce586/google/cloud/internal/service_endpoint.cc#L40)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

> I didn't use `kGDU` in the code because style guide.

So, presumably there is good reason for that.  I would assert that the same reason applies to the error message, whether the user is only forwarding it to us or not.  But, a small point.

In the bigger picture I agree with @dbolduc ... we should be able to guarantee that we have valid default endpoints long before a user is executing code.
</blockquote></details>

SGTM. I removed the GDU check.


<!-- Sent from Reviewable.io -->

2023-11-15 19:24 UTC, devbww commented on google/cloud/internal/service_endpoint.h
> +//      internal::ExtractOption<EndpointOption>(opts), opts,
Passing `ExtractOption<FooOption>(opts)` and `opts` in the same parameter list is probably something to be avoided.

2023-11-15 19:24 UTC, devbww commented on google/cloud/internal/service_endpoint.h
> +    std::string default_endpoint);
Q.  Is there anything to be said for passing `Options` last?

2023-11-15 19:24 UTC, devbww commented on google/cloud/internal/service_endpoint_test.cc
> +auto constexpr kDefaultHost = "default_endpoint.googleapis.com";
s/DefaultHost/DefaultEndpoint/

2023-11-15 19:24 UTC, devbww commented on google/cloud/internal/service_endpoint.cc
> +  auto constexpr kGoogleDefaultUniverse = ".googleapis.com.";
Nit:  I'd probably move this down to immediately before the one place it is (now) used (at which point giving it a name may be overkill)

2023-11-15 19:35 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123)* status: 4 of 6 files reviewed, 10 unresolved discussions (waiting on @coryan, @dbolduc, and @devbww)

___
*[`google/cloud/internal/service_endpoint.h` line 36 at r7](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1394672316:-NjJT4G70tsPaDylr_RM:b-3dzec) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8cfbdb49796dad0f165e1a3a5457ff0169057e75/google/cloud/internal/service_endpoint.h#L36)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

Passing `ExtractOption<FooOption>(opts)` and `opts` in the same parameter list is probably something to be avoided.
</blockquote></details>

The option type extracted is not going to be the same for every invocation of this function. An additional benefit of calling `ExtractOption` is that it returns an optional<string>/
___
*[`google/cloud/internal/service_endpoint.h` line 41 at r7](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1394674230:-NjJTafB7N8_-SmeOZ4O:b-c9g1av) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8cfbdb49796dad0f165e1a3a5457ff0169057e75/google/cloud/internal/service_endpoint.h#L41)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

Q.  Is there anything to be said for passing `Options` last?
</blockquote></details>

I'm not sure it matters.
___
*[`google/cloud/internal/service_endpoint.cc` line 36 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#-Nj9XXhf6vHmiiQF2T7_:-NjJTkIv9fxDto4o-Wl4:b2nhb2c) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/a1720efa84a7899cbb1ca2939078a86fc43f4f7f/google/cloud/internal/service_endpoint.cc#L36)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

Hm. I would say there is an implicit requirement that `EndpointOption` cannot be empty... If `EndpointOption` is empty none of the applications requests will work.

I still don't think the two options should be treated any differently. :shrug:
</blockquote></details>

Ack
___
*[`google/cloud/internal/service_endpoint.cc` line 47 at r5](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1393616043:-NjJTm841z3tEMKjLLRE:b2nhb2c) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2bfa373d775e29eddc2ade908f77d411ab1e63bc/google/cloud/internal/service_endpoint.cc#L47)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

Similar to above, it seems like this should be a build error instead.
</blockquote></details>

Ack
___
*[`google/cloud/internal/service_endpoint.cc` line 32 at r7](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1394677383:-NjJTVOP9X9cDHlG37if:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8cfbdb49796dad0f165e1a3a5457ff0169057e75/google/cloud/internal/service_endpoint.cc#L32)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

Nit:  I'd probably move this down to immediately before the one place it is (now) used (at which point giving it a name may be overkill)
</blockquote></details>

Done.
___
*[`google/cloud/internal/service_endpoint_test.cc` line 32 at r7](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1394675297:-NjJTYDm1R1NC8snpggc:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8cfbdb49796dad0f165e1a3a5457ff0169057e75/google/cloud/internal/service_endpoint_test.cc#L32)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

s/DefaultHost/DefaultEndpoint/
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-15 21:12 UTC, devbww reviewed
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123)* status: all files reviewed, 9 unresolved discussions (waiting on @coryan, @dbolduc, and @scotthart)

___
*[`google/cloud/internal/service_endpoint.h` line 36 at r7](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1394672316:-NjJnqCT08ktQR9LjQjA:b-9psbd) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8cfbdb49796dad0f165e1a3a5457ff0169057e75/google/cloud/internal/service_endpoint.h#L36)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

The option type extracted is not going to be the same for every invocation of this function. An additional benefit of calling `ExtractOption` is that it returns an optional<string>/
</blockquote></details>

I have no problem extracting from `opts`, but I wouldn't do it in the same parameter list as passing `opts` for the same reason I would avoid `foo(i, ++i)`.
___
*[`google/cloud/internal/service_endpoint.h` line 41 at r7](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1394674230:-NjJnQO28nulBlgVtyM0:b9gbr8h) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8cfbdb49796dad0f165e1a3a5457ff0169057e75/google/cloud/internal/service_endpoint.h#L41)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

I'm not sure it matters.
</blockquote></details>

Only that it would be consistent with most other functions where we pass `Options`.


<!-- Sent from Reviewable.io -->

2023-11-15 21:41 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123)* status: 3 of 6 files reviewed, 9 unresolved discussions (waiting on @coryan, @dbolduc, and @devbww)

___
*[`google/cloud/internal/service_endpoint.h` line 36 at r7](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1394672316:-NjJvJFH81AU4Dc3oIUQ:btmz3m8) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8cfbdb49796dad0f165e1a3a5457ff0169057e75/google/cloud/internal/service_endpoint.h#L36)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

I have no problem extracting from `opts`, but I wouldn't do it in the same parameter list as passing `opts` for the same reason I would avoid `foo(i, ++i)`.
</blockquote></details>

Good point, I didn't realize you were referring to the issue of argument evaluation order (or lack thereof).
___
*[`google/cloud/internal/service_endpoint.h` line 41 at r7](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123#gh-1394674230:-NjJvY8s3XnuZ4vNbvo5:b-law22v) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8cfbdb49796dad0f165e1a3a5457ff0169057e75/google/cloud/internal/service_endpoint.h#L41)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

Only that it would be consistent with most other functions where we pass `Options`.
</blockquote></details>

Reordered.


<!-- Sent from Reviewable.io -->

2023-11-15 21:54 UTC, devbww approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13123)* status: all files reviewed, 7 unresolved discussions (waiting on @coryan and @dbolduc)



<!-- Sent from Reviewable.io -->

2023-11-15 22:02 UTC, dbolduc approved these changes

2023-11-15 23:21 UTC, merged