impl: heed `RetryInfo` in common loops
googleapis/google-cloud-cpp pull request #13657
Opened 2024-02-23 17:59 UTC by dbolduc

Part of the work for #13514 

Retry on `RetryInfo` in the common loops. This overrides idempotency and any supplied backoff policies.

This rounds out the Bigtable client calls.

2024-02-23 20:29 UTC, devbww commented on google/cloud/internal/retry_loop_helpers.cc
> +    if (ri.has_value()) {
Did we discuss eschewing `optional::has_value()` in explicit boolean contexts (i.e., just `if (ri)`)?  I thought so, but can't find any trace.

2024-02-23 20:29 UTC, devbww commented on google/cloud/internal/retry_loop_helpers.cc
> +          ri->retry_delay());
Followup on previous review:  Perhaps we should add an explicit `Note:` that we're choosing to ignore the backoff policy's delay.

2024-02-23 20:29 UTC, devbww commented on google/cloud/internal/retry_loop_helpers.cc
> +  if (should_retry) return backoff.OnCompletion();
Should we be calling `backoff.OnCompletion()` in the `RetryInfo` case too, even though its return value is ignored?

2024-02-23 20:29 UTC, scotthart requested changes
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13657)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @dbolduc and @devbww)

___
*[`google/cloud/internal/retry_loop_helpers.h` line 78 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13657#-NrMdgYf1KnHJ3-6WrTo:-NrMdgYf1KnHJ3-6WrTp:blryypx) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/04332c90199719f4c76471a9f247e30b102dd54f/google/cloud/internal/retry_loop_helpers.h#L78)):*
> ```objc
>                                             BackoffPolicy& backoff,
>                                             Idempotency idempotency,
>                                             bool enable_server_retries);
> ```

Can we change this from a `bool` to an `enum class` to increase call-site readability (https://abseil.io/tips/94).


<!-- Sent from Reviewable.io -->

2024-02-26 07:39 UTC, dbolduc reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13657)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @devbww and @scotthart)

___
*[`google/cloud/internal/retry_loop_helpers.h` line 78 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13657#-NrMdgYf1KnHJ3-6WrTo:-NrZIkdPBiAFIFoUxczi:b-n3kva6) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/04332c90199719f4c76471a9f247e30b102dd54f/google/cloud/internal/retry_loop_helpers.h#L78)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Can we change this from a `bool` to an `enum class` to increase call-site readability (https://abseil.io/tips/94).
</blockquote></details>

Done. Do you think we should expose the enum? as in:

```cc
enum class RetryInfoPolicy { kHeed, kIgnore };

struct RetryInfoPolicyOption {
  using Type = RetryInfoPolicy;
};
```

(this would replace `EnableServerRetriesOption`, which is a bool). It just seems funny to take a bool then convert it to an enum then convert it back to a bool.

Note that `EnableServerRetriesOption` is in `internal`, so moving/renaming/retyping it would happen in a follow up PR.
___
*[`google/cloud/internal/retry_loop_helpers.cc` line 118 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13657#gh-1501130730:-NrZJcZtDyOmCcp5cETd:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/04332c90199719f4c76471a9f247e30b102dd54f/google/cloud/internal/retry_loop_helpers.cc#L118)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

Did we discuss eschewing `optional::has_value()` in explicit boolean contexts (i.e., just `if (ri)`)?  I thought so, but can't find any trace.
</blockquote></details>

Done.
___
*[`google/cloud/internal/retry_loop_helpers.cc` line 123 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13657#gh-1501134459:-NrZKbt-20HmITNa4FNe:bqmjwcz) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/04332c90199719f4c76471a9f247e30b102dd54f/google/cloud/internal/retry_loop_helpers.cc#L123)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

Followup on previous review:  Perhaps we should add an explicit `Note:` that we're choosing to ignore the backoff policy's delay.
</blockquote></details>

Added.
___
*[`google/cloud/internal/retry_loop_helpers.cc` line 129 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13657#gh-1501135934:-NrZKc_JDsoIPhbsryAs:bracy9a) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/04332c90199719f4c76471a9f247e30b102dd54f/google/cloud/internal/retry_loop_helpers.cc#L129)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

Should we be calling `backoff.OnCompletion()` in the `RetryInfo` case too, even though its return value is ignored?
</blockquote></details>

While it is not a huge difference, I think so. I'll send another PR to do this for the other code path (that handles the streaming APIs).


<!-- Sent from Reviewable.io -->

2024-02-26 15:33 UTC, devbww approved these changes
> Reviewed 2 of 7 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13657)* status: all files reviewed, 1 unresolved discussion (waiting on @scotthart)

___
*[`google/cloud/internal/retry_loop_helpers.cc` line 129 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13657#gh-1501135934:-Nra2-cm17Hrfc_szn33:bb6sh2i) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/04332c90199719f4c76471a9f247e30b102dd54f/google/cloud/internal/retry_loop_helpers.cc#L129)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

While it is not a huge difference, I think so. I'll send another PR to do this for the other code path (that handles the streaming APIs).
</blockquote></details>

Ack.


<!-- Sent from Reviewable.io -->

2024-02-26 16:35 UTC, scotthart approved these changes
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13657)* status: all files reviewed, 1 unresolved discussion (waiting on @dbolduc)

___
*[`google/cloud/internal/retry_loop_helpers.h` line 78 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13657#-NrMdgYf1KnHJ3-6WrTo:-NraG1I02UIm55xr9XnZ:b-maf8nq) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/04332c90199719f4c76471a9f247e30b102dd54f/google/cloud/internal/retry_loop_helpers.h#L78)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

Done. Do you think we should expose the enum? as in:

```cc
enum class RetryInfoPolicy { kHeed, kIgnore };

struct RetryInfoPolicyOption {
  using Type = RetryInfoPolicy;
};
```

(this would replace `EnableServerRetriesOption`, which is a bool). It just seems funny to take a bool then convert it to an enum then convert it back to a bool.

Note that `EnableServerRetriesOption` is in `internal`, so moving/renaming/retyping it would happen in a follow up PR.
</blockquote></details>

It does look funny. Let's leave it as a bool for the time being (don't add the enum). It seems more trouble than it's worth in this situation (as there's only 1 bool parameter in the function signature).


<!-- Sent from Reviewable.io -->

2024-02-26 19:07 UTC, dbolduc commented
>  Let's leave it as a bool for the time being (don't add the enum).

Done, and added parameter name hints to the test for clarity

2024-02-27 15:19 UTC, merged