doc(bigquerycontrol): add job query sample
googleapis/google-cloud-cpp pull request #14580
Opened 2024-07-26 22:10 UTC by scotthart

2024-07-26 22:21 UTC, coryan requested changes
Lots of nits... The thing around `std::runtime_error()` matters more I think.

2024-07-26 22:21 UTC, coryan commented on google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc
> +  if (argv.size() == 3) retry_delay = std::stoi(argv[2]);
Consider:

```suggestion
  auto const backoff  = std::chrono::seconds(argv.size() == 3 ? std::stoi(argv[2]) : 2);
```

2024-07-26 22:21 UTC, coryan commented on google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc
> +      for (auto delay : retries) {
consider:

```suggestion
      for (auto b : {backoff, backoff, backoff, backoff}) {
```

2024-07-26 22:21 UTC, coryan commented on google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc
> +      if (!job_complete) throw "Query execution timed out after 5 retries.";
Better to throw `std::runtime_error()` I think strings will print as "unknown error" without any details.

2024-07-26 22:21 UTC, coryan commented on google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc
> +        if (!query_results) throw query_results.status();
```suggestion
        if (!query_results) throw std::move(query_results).status();
```

2024-07-26 22:21 UTC, coryan commented on google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc
> +      if (!query_results) throw query_results.status();
```suggestion
      if (!query_results) throw std::move(query_results).status();
```

2024-07-26 22:21 UTC, coryan commented on google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc
> +    if (!insert_result) throw insert_result.status();
```suggestion
    if (!insert_result) throw std::move(insert_result).status();
```

2024-07-26 22:21 UTC, coryan commented on google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc
> +     int retry_delay) {
```suggestion
     std::chrono::seconds retry_delay) {
```

2024-07-26 22:21 UTC, coryan commented on google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc
> +  if (argv.size() == 3) retry_delay = std::stoi(argv[2]);
This is because we prefer to use duration types with explicit units.

2024-07-26 22:21 UTC, coryan commented on google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc
> +      query_results = client.GetQueryResults(query_results_request);
```suggestion
    int num_pages = 0;
    bool finished = false;
    while (!finished) {
      auto query_results = client.GetQueryResults(query_results_request);
```

2024-07-26 22:21 UTC, coryan commented on google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc
> +#include <vector>
If you end up using `std::runtime_error()`:

```
#include <stdexcept>
```

2024-07-29 15:43 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14580)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @coryan)

___
*[`google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc` line 26 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14580#gh-1693650070:-O2z9D6CClgR2sRy5cX9:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/21273408571711f0879ba3373fec18d368f27843/google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc#L26)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

If you end up using `std::runtime_error()`:

```
#include <stdexcept>
```


</blockquote></details>

Done.
___
*[`google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc` line 44 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14580#gh-1693645985:-O2z9DUf8XkTw07AwT_1:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/21273408571711f0879ba3373fec18d368f27843/google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc#L44)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This is because we prefer to use duration types with explicit units.
</blockquote></details>

Done.
___
*[`google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc` line 49 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14580#gh-1693648658:-O2z9DuGBecUCyCPplCz:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/21273408571711f0879ba3373fec18d368f27843/google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc#L49)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

```suggestion
     std::chrono::seconds retry_delay) {
```

</blockquote></details>

Done.
___
*[`google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc` line 70 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14580#gh-1693648366:-O2z9F0j0KdFn-akmkbQ:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/21273408571711f0879ba3373fec18d368f27843/google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc#L70)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

```suggestion
    if (!insert_result) throw std::move(insert_result).status();
```
</blockquote></details>

Done.
___
*[`google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc` line 82 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14580#gh-1693647265:-O2z9FSi4eKklJ2zAeAK:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/21273408571711f0879ba3373fec18d368f27843/google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc#L82)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

consider:

```suggestion
      for (auto b : {backoff, backoff, backoff, backoff}) {
```

</blockquote></details>

Done.
___
*[`google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc` line 90 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14580#gh-1693647627:-O2z9FrW9UeSoCleAJU3:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/21273408571711f0879ba3373fec18d368f27843/google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc#L90)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Better to throw `std::runtime_error()` I think strings will print as "unknown error" without any details.
</blockquote></details>

Done.
___
*[`google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc` line 111 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14580#gh-1693649500:-O2z9GGA7B3A7-syIApy:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/21273408571711f0879ba3373fec18d368f27843/google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc#L111)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

```suggestion
    int num_pages = 0;
    bool finished = false;
    while (!finished) {
      auto query_results = client.GetQueryResults(query_results_request);
```
</blockquote></details>

Done.
___
*[`google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc` line 112 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14580#gh-1693648176:-O2z9GdG4HKDFKOKV7nR:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/21273408571711f0879ba3373fec18d368f27843/google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc#L112)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

```suggestion
      if (!query_results) throw std::move(query_results).status();
```
</blockquote></details>

Done.
___
*[`google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc` line 131 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14580#gh-1693648086:-O2z9Hmm7V7TVQAdJKmv:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/21273408571711f0879ba3373fec18d368f27843/google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc#L131)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

```suggestion
        if (!query_results) throw std::move(query_results).status();
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-29 15:48 UTC, coryan approved these changes
One last fix I think.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14580#-:-O2zAVrm0e2A7Sdbh2qK:b-2st1jr)* status: all files reviewed, 2 unresolved discussions (waiting on @scotthart)

___
*[`google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc` line 82 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14580#-O2zA1oE4p-xiCDmlxMY:-O2zA1oE4p-xiCDmlxMZ:b-inocxr) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/48d4402d47f25c5719aa5112a96d4652a628efaa/google/cloud/bigquerycontrol/v2/samples/job_query_samples.cc#L82)):*
> ```cpp
>           break;
>         }
>         std::this_thread::sleep_for(std::chrono::seconds(b));
> ```

`b` is already a `std::chrono::duration` type, right?



_Code snippet:_
```cpp
std::this_thread::sleep_for(b);
```


<!-- Sent from Reviewable.io -->

2024-07-29 17:23 UTC, merged