refactor(generator): prepare for dynamic query params
googleapis/google-cloud-cpp pull request #14596
Opened 2024-07-31 18:34 UTC by dbolduc

Part of the work for #14492, #10176

To support repeated fields and arbitrary message nesting, we will need to dynamically add the query parameters. An initializer list cannot handle that complexity.

This PR just refactors the construction of the query parameters (in generated code) to prepare for adding loops and such, e.g.: https://github.com/dbolduc/google-cloud-cpp/commit/7874e790c64a2e0a61c7da727ff471da190b35ec

2024-07-31 21:03 UTC, scotthart requested changes
> Reviewed 1 of 123 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14596)* status: 1 of 123 files reviewed, 1 unresolved discussion (waiting on @dbolduc)

___
*[`generator/integration_tests/golden/v1/internal/golden_thing_admin_rest_stub.cc` line 73 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14596#-O39aD862kNk5H_TXdaR:-O39aD862kNk5H_TXdaS:b-jt8tjv) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/f6a4417a2044e4e4e7cd7232d63b0f53b6be3ad4/generator/integration_tests/golden/v1/internal/golden_thing_admin_rest_stub.cc#L73)):*
> ```cpp
>   std::thread t{[](
>           auto p, auto service, auto request, auto rest_context, auto options) {
>       std::vector<std::pair<std::string, std::string>> query_params;
> ```

Do we want to emit this code when there are no query parameters?


<!-- Sent from Reviewable.io -->

2024-07-31 21:05 UTC, dbolduc commented
> Do we want to emit this code when there are no query parameters?

I do. And the ghost of @devbww would. (He would say: no default parameters for internal functions).

I think it is easier to do the same thing all the time instead of handling an empty vector as a special case.

2024-07-31 22:19 UTC, scotthart reviewed
Fair enough, but let's remove the call to `TrimQueryParameters` when there are no parameters. I'm pretty sure the optimizer cannot reason about a function in another TU and will have to always call it.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14596#-:-O39r_pM6Dk8SkXgo42c:bw4emze)* status: 1 of 123 files reviewed, 1 unresolved discussion (waiting on @dbolduc)



<!-- Sent from Reviewable.io -->

2024-07-31 23:37 UTC, dbolduc commented
> Fair enough, but let's remove the call to `TrimQueryParameters` when there are no parameters. I'm pretty sure the optimizer cannot reason about a function in another TU and will have to always call it.

I am not worried about calling a function that returns immediately when compared with the subsequent network call.... but it is easy enough to do, so done.

2024-08-01 15:37 UTC, scotthart approved these changes
> Reviewed 1 of 117 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14596)* status: 1 of 123 files reviewed, 1 unresolved discussion (waiting on @dbolduc)



<!-- Sent from Reviewable.io -->

2024-08-01 15:44 UTC, merged