chore(compute): update_discovery_doc.sh now edits generator_config
googleapis/google-cloud-cpp pull request #14623
Opened 2024-08-08 18:34 UTC by scotthart

Improve automation by having script edit generator_config.textproto when new compute services are detected and re-running the generator to emit code for the new services.

2024-08-09 14:58 UTC, dbolduc commented
/gcbrun

2024-08-12 02:02 UTC, dbolduc requested changes

2024-08-12 02:02 UTC, dbolduc commented on generator/discovery/update_discovery_doc.sh
> +  io::log_h2 "Running generate-libraries again with updated generator_config.textproto"
> again

If `UPDATED_DISCOVERY_DOCUMENT` is set, we could cut off `generate-libraries.sh` after it writes the compute protos.

Then we can run  `build.sh -t generate-libraries-pr || true` here without setting `UPDATED_DISCOVERY_DOCUMENT`?

It seems cleaner to do all the `git add`ing in this script.

2024-08-12 02:02 UTC, dbolduc commented on generator/discovery/update_discovery_doc.sh
> +  (
I am too lazy to figure out what these commands do. My guess is that it fills in the text between "Begin" and "End" with the new additions. But doesn't that get overwritten the next time we update the discovery doc?

Also do we care about sorting?

---

A solution where we have all the `rest_services {}` between "Begin" and "End" is close. The issue is with the copyright year which is variable. Ugh.

If we don't care about sorting, we can have one marker, and just insert the new `rest_services {}` above it in the config.

2024-08-12 20:47 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14623)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dbolduc)

___
*[`generator/discovery/update_discovery_doc.sh` line 27 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14623#gh-1713112688:-O46J_U_2uTIWEE4lzFM:b-1ii3da) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/76fcfd6058fb2fd26e4f90fb82770caf4e964cdd/generator/discovery/update_discovery_doc.sh#L27)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

I am too lazy to figure out what these commands do. My guess is that it fills in the text between "Begin" and "End" with the new additions. But doesn't that get overwritten the next time we update the discovery doc?

Also do we care about sorting?

---

A solution where we have all the `rest_services {}` between "Begin" and "End" is close. The issue is with the copyright year which is variable. Ugh.

If we don't care about sorting, we can have one marker, and just insert the new `rest_services {}` above it in the config.
</blockquote></details>

Fixed the `sed` stuff to append new service definitions instead of overwriting. The sorting was mostly for benefit of the human editing it, but this should remove that interaction. One marker mechanism adopted.
___
*[`generator/discovery/update_discovery_doc.sh` line 98 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14623#gh-1713112438:-O47KsY22UYopx21EKq_:b-gijd9x) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/76fcfd6058fb2fd26e4f90fb82770caf4e964cdd/generator/discovery/update_discovery_doc.sh#L98)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

> again

If `UPDATED_DISCOVERY_DOCUMENT` is set, we could cut off `generate-libraries.sh` after it writes the compute protos.

Then we can run  `build.sh -t generate-libraries-pr || true` here without setting `UPDATED_DISCOVERY_DOCUMENT`?

It seems cleaner to do all the `git add`ing in this script.
</blockquote></details>

Updated generate-libraries to exit early after emitting protos (when UPDATED_DISCOVERY_DOCUMENT is set). Moved all the `git add` from generate-libraries to this script.


<!-- Sent from Reviewable.io -->

2024-08-13 15:27 UTC, dbolduc approved these changes

2024-08-13 15:27 UTC, dbolduc commented on generator/discovery/update_discovery_doc.sh
> +    xargs -r -P "$(nproc)" -n 50 -0 sed -i 's/[[:blank:]]\+$//'
nit: we are not pressed for time or anything, but we could scope these to `google/cloud/compute`

2024-08-13 15:47 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14623)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @dbolduc)

___
*[`generator/discovery/update_discovery_doc.sh` line 121 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14623#gh-1715503511:-O4BPrDR9RBawntLA0S4:b-f6qlzn) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/021d22226753f20e043a0a920bfd4bfe17084023/generator/discovery/update_discovery_doc.sh#L121)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

nit: we are not pressed for time or anything, but we could scope these to `google/cloud/compute`
</blockquote></details>

I'll look into that next time I'm modifying this script.


<!-- Sent from Reviewable.io -->

2024-08-13 15:47 UTC, merged