cleanup(generator): generalize return type strings
googleapis/google-cloud-cpp pull request #14657
Opened 2024-08-21 20:11 UTC by cuiy0006

Create function to generalize return type strings of the methods in generator.

Only clean up for 2 generators: 
generator/internal/auth_decorator_generator.cc
generator/internal/client_generator.cc

There are more cleanups to do in the follow up PR:
generator/internal/connection_generator.cc
generator/internal/connection_impl_generator.cc
generator/internal/connection_impl_rest_generator.cc
generator/internal/logging_decorator_generator.cc
generator/internal/logging_decorator_rest_generator.cc
generator/internal/metadata_decorator_generator.cc
generator/internal/metadata_decorator_rest_generator.cc
generator/internal/mock_connection_generator.cc
generator/internal/round_robin_decorator_generator.cc
generator/internal/stub_generator_base.cc
generator/internal/stub_generator.cc
generator/internal/stub_rest_generator.cc
generator/internal/tracing_connection_generator.cc
generator/internal/tracing_stub_generator.cc

2024-08-21 23:00 UTC, dbolduc requested changes
Good idea to stop after 1 or 2 generators.

2024-08-22 16:09 UTC, cuiy0006 commented on generator/internal/auth_decorator_generator.cc
> +                  FormatMethodReturnType(method, /*is_async=*/false,
I agree with using `method_vars`, that is better than my helper function.

But I think `return_type` is not enough, one method can be generated as sync and async versions at the same time. We may need both `sync_return_type` and `async_return_type`.

2024-08-22 16:13 UTC, cuiy0006 commented on generator/internal/descriptor_utils.cc
> +  if (is_async) {
There is an exception. For longrunning, the sync return type includes `longrunning_operation_type` while the async version is `longrunning_deduced_response_type`.

2024-08-22 16:17 UTC, cuiy0006 commented on generator/internal/auth_decorator_generator.cc
> +                  FormatMethodReturnType(method, /*is_async=*/false,
Using `method_vars` is a good idea, it's better than the helper function.

But as the comment above, longrunning response types are different between sync and async versions. So I think we may need both `sync_ return_type` and `async_return_type`.

2024-08-22 16:18 UTC, cuiy0006 commented on generator/internal/descriptor_utils.h
> +std::string FormatMethodReturnType(
Yeah, if we use `method_vars`, the function makes no sense, I will remove it.

2024-08-22 16:58 UTC, dbolduc commented on generator/internal/descriptor_utils.cc
> +  if (is_async) {
I am not suggesting that we change the LRO code to use `$return_type$`.

2024-08-22 18:01 UTC, cuiy0006 commented on generator/internal/descriptor_utils.cc
> +  if (is_async) {
After discussion with @dbolduc, we decide to only generalize the return string for non-longrunning types.

2024-08-23 15:24 UTC, cuiy0006 commented on generator/internal/auth_decorator_generator.cc
> +                  FormatMethodReturnType(method, /*is_async=*/false,
I will only generalize non-lro return type.

2024-08-23 15:41 UTC, dbolduc reviewed
Can you add a simple test case to `descriptor_utils_test.cc` to verify the `Status` and `StatusOr<T>` cases of `return_type`?

Something like this:

https://github.com/googleapis/google-cloud-cpp/blob/0e6f85404a95c4de085ae6f905216505f25fe32a/generator/internal/descriptor_utils_test.cc#L1258-L1259

2024-08-23 17:39 UTC, dbolduc approved these changes

2024-08-23 18:51 UTC, merged