impl(otel): copy service resource labels into metric labels
googleapis/google-cloud-cpp pull request #14825
Opened 2024-11-06 03:09 UTC by IcySteam

fixed #14823

2024-11-13 18:49 UTC, dbolduc requested changes
I don't think the copying is necessary. Can we check for the known service labels and do the manipulations here:

https://github.com/googleapis/google-cloud-cpp/blob/912533cf46cc0e9e08c90e12472a65d9adaffbc9/google/cloud/opentelemetry/internal/time_series.cc#L174-L177

and add a `TEST(ToMonitoredResource, AddsServiceLabels) { ... }` in `time_series_test.cc` ?

2024-11-13 19:15 UTC, dbolduc commented on google/cloud/opentelemetry/internal/monitored_resource.cc
> +        auto& attributes = pda.attributes;
Sorry, I am confused. Do we want the labels to end up getting added to the `google.api.Metric` https://github.com/googleapis/googleapis/blob/2d05911be5a468b556236bee537c91922f9c23a3/google/api/metric.proto#L286

... or to the `google.api.MonitoredResource` https://github.com/googleapis/googleapis/blob/2d05911be5a468b556236bee537c91922f9c23a3/google/api/monitored_resource.proto#L106

... or both?

unit tests would help clarify the intended behavior that we want.

2024-11-22 16:54 UTC, dbolduc commented
/gcbrun

2024-11-25 06:37 UTC, IcySteam commented
Thanks; we indeed want the labels to end up getting added to the `google.api.Metric` class. I've refactored the PR and added some unit tests in the latest commit, PTAL.

2025-01-10 22:51 UTC, dbolduc reviewed
Thanks for the PR. Sorry it took me so long to review it. I have been splitting time between `google-cloud-cpp` and another team.

I feel like I owe you one, so I made the review changes in #14930. Hopefully that can cut out some review iterations and unblock y'all faster.

2025-01-10 22:51 UTC, dbolduc commented on google/cloud/opentelemetry/internal/time_series.h
> +std::unordered_map<std::string, OTelKeyMatch> const kExtraLabelsLookup = {
On second thought, I don't think this struct is buying us much of anything. It seems kind of misapplied, in that the things like `"service_name"` are supposed to represent monitored resources.

I think we will be better off just iterating over the 3 labels we care about, and reuse the name changing logic from `ToMetric()`

2025-01-10 22:51 UTC, dbolduc commented on google/cloud/opentelemetry/internal/time_series_test.cc
> +    for (auto const& ts : tss) {
We should avoid logical branches and stuff in tests. Let's try to make them as simple as possible.

2025-01-10 22:51 UTC, dbolduc commented on google/cloud/opentelemetry/internal/time_series_test.cc
> +      EXPECT_EQ(labels.at(kv.first), kv.first);
We probably want to use GMock's container matchers.

https://google.github.io/googletest/reference/matchers.html

2025-01-10 22:51 UTC, dbolduc commented on google/cloud/opentelemetry/internal/time_series_test.cc
> +      if (existing_labels.GetAttributes().find(kv.first) ==
`if`s in tests kind of scare me.

2025-01-10 22:51 UTC, dbolduc commented on google/cloud/opentelemetry/internal/time_series.cc
> +  WithExtraLabels(data, tss);
I think it would make sense to build this into `ToMetric(...)` which deals specifically with the `google.api.Metric`. It also has logic for changing strings from `service.name` -> `service_name` which we can reuse.

2025-01-10 22:54 UTC, dbolduc commented
I am closing this PR in favor of #14930 

Thank you @IcySteam for the hard work on this PR. I copied a lot of it in #14930.

2025-01-10 22:54 UTC, closed without merging