test: test gRPC data plane on GCS
googleapis/google-cloud-cpp pull request #5031
Opened 2020-09-09 14:14 UTC by dopiera

The emulator doesn't support this, so production environment is needed.

A number of tests had to be weakened/disabled due to #5030 and
b/146890058.

This needs #5029.

2020-09-09 15:40 UTC, coryan requested changes
I know you are planning some additional testing, but some general comments.

> Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5031#-:-MGnO3iP8VtnIf0AfbGJ:b-anutld)* status: all files reviewed, 5 unresolved discussions (waiting on @dopiera)

___
*[ci/kokoro/docker/build.sh, line 460 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5031#-MGnUC8SCrYYMQcUnK0a:-MGnUC8T9aZuJorDFhTJ:b-r2k1mh) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/da0c04a10ad56e53ff0857c8496821d02fc5e1f6/ci/kokoro/docker/build.sh#L460)):*
> ```Shell
>   # If set to 'yes', the build script will execute all GCS tests agains
>   # production (rather than emulator).
>   "--env" "RUN_ALL_GCS_TESTS_ON_PROD=${RUN_ALL_GCS_TESTS_ON_PROD:-}"
> ```

I think this could be generalized where any service could run against emulators or production, maybe `TEST_IN_PRODUCTION=storage,pubsub` ... then one can do something like:

```sh
if echo "${TEST_INPRODUCTION}" | fgrep -qw storage; then
  # run against production
else
  # run against the emulator
fi
```

WDYT?
___
*[google/cloud/storage/tests/object_integration_test.cc, line 393 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5031#-MGnVdW06mrl8BDsdXe8:-MGnVdW06mrl8BDsdXe9:b-a9tox1) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/da0c04a10ad56e53ff0857c8496821d02fc5e1f6/google/cloud/storage/tests/object_integration_test.cc#L393)):*
> ```cpp
>   if (!UsingGrpc()) {
>     EXPECT_FALSE(meta.ok()) << "value=" << meta.value();
>     EXPECT_EQ(StatusCode::kInvalidArgument, meta.status().code())
> ```

Consider:


```
#include "google/cloud/testing_util/status_matchers.h"


EXPECT_THAT(meta.status(), StatusIs(StatusCode::KInvalidArgument));
```
___
*[google/cloud/storage/tests/object_integration_test.cc, line 807 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5031#-MGnOPXcCKNplKVtOl22:-MGnOPXcCKNplKVtOl23:b-3x2nag) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/da0c04a10ad56e53ff0857c8496821d02fc5e1f6/google/cloud/storage/tests/object_integration_test.cc#L807)):*
> ```cpp
> 
> TEST_F(ObjectIntegrationTest, DeleteResumableUpload) {
>   if (UsingGrpc()) {
> ```

We generally write these as:

```cc
// TODO(#5030) - DeleteResumableUpload does not work with gRPC yet.
if (UsingGrpc()) GTEST_SKIP();
```
___
*[google/cloud/storage/tests/object_resumable_parallel_upload_integration_test.cc, line 42 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5031#-MGnO_V14d5v4fO9mAf_:-MGnO_V14d5v4fO9mAfa:bbw4h2b) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/da0c04a10ad56e53ff0857c8496821d02fc5e1f6/google/cloud/storage/tests/object_resumable_parallel_upload_integration_test.cc#L42)):*
> ```cpp
> TEST_F(ObjectResumableParallelUploadIntegrationTest, ResumableParallelUpload) {
>   // TODO(b/146890058) - reenable the test for gRPC
>   if (UsingGrpc()) {
> ```

see above.
___
*[google/cloud/storage/tests/object_resumable_parallel_upload_integration_test.cc, line 86 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5031#-MGnOb9Y2KI10fyv2oFs:-MGnOb9Y2KI10fyv2oFt:bs4q9op) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/da0c04a10ad56e53ff0857c8496821d02fc5e1f6/google/cloud/storage/tests/object_resumable_parallel_upload_integration_test.cc#L86)):*
> ```cpp
> 
> TEST_F(ObjectResumableParallelUploadIntegrationTest, ResumeParallelUploadFile) {
>   // TODO(b/146890058) - reenable the test for gRPC
> ```

Ditto.


<!-- Sent from Reviewable.io -->

2020-09-16 14:28 UTC, dopiera reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5031)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @coryan and @dopiera)

___
*[google/cloud/storage/tests/object_integration_test.cc, line 393 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5031#-MGnVdW06mrl8BDsdXe8:-MHMG7aD89QGDtcKB1GF:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/da0c04a10ad56e53ff0857c8496821d02fc5e1f6/google/cloud/storage/tests/object_integration_test.cc#L393)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Consider:


```
#include "google/cloud/testing_util/status_matchers.h"


EXPECT_THAT(meta.status(), StatusIs(StatusCode::KInvalidArgument));
```

</blockquote></details>

Done.
___
*[google/cloud/storage/tests/object_integration_test.cc, line 807 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5031#-MGnOPXcCKNplKVtOl22:-MHMGBssDquDcVAWzdI8:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/da0c04a10ad56e53ff0857c8496821d02fc5e1f6/google/cloud/storage/tests/object_integration_test.cc#L807)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

We generally write these as:

```cc
// TODO(#5030) - DeleteResumableUpload does not work with gRPC yet.
if (UsingGrpc()) GTEST_SKIP();
```
</blockquote></details>

Done.
___
*[google/cloud/storage/tests/object_resumable_parallel_upload_integration_test.cc, line 42 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5031#-MGnO_V14d5v4fO9mAf_:-MHMGPb4D3IMp9fjirhv:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/da0c04a10ad56e53ff0857c8496821d02fc5e1f6/google/cloud/storage/tests/object_resumable_parallel_upload_integration_test.cc#L42)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

see above.
</blockquote></details>

Done.
___
*[google/cloud/storage/tests/object_resumable_parallel_upload_integration_test.cc, line 86 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5031#-MGnOb9Y2KI10fyv2oFs:-MHMGQ7J6p4hZ8dvgON1:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/da0c04a10ad56e53ff0857c8496821d02fc5e1f6/google/cloud/storage/tests/object_resumable_parallel_upload_integration_test.cc#L86)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-22 23:24 UTC, dopiera commented
@coryan I think we don't need to create an additional kokoro config. Piggybacking to `gcc-9` configs is probably enough, WDYT?

2020-09-22 23:36 UTC, coryan commented
>  Piggybacking to gcc-9 configs is probably enough, WDYT?

In the past, that has created confusion. OTOH, it is more efficient in resources.  Thinking about it for a couple of minutes, I think we should have a separate build.

2020-09-23 09:06 UTC, dopiera commented
> > Piggybacking to gcc-9 configs is probably enough, WDYT?
> 
> In the past, that has created confusion. OTOH, it is more efficient in resources. Thinking about it for a couple of minutes, I think we should have a separate build.

ACK, may I ask you to add a gcs-grpc kokoro config then?

2020-09-23 11:54 UTC, coryan commented
I will, we need to commit the config files first, or the Kokoro builds fail (Kokoro fails if the GitHub configs are missing).

2020-09-23 12:45 UTC, coryan requested changes
It looks good (one missing change below).  I think the PR builds will fail until #5122 is merged and you rebase, and sadly they take 2 hours to fail.

> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5031#-:-MHuzb9x3Xb1-h2fIgAF:b-r2j2k)* status: all files reviewed, 1 unresolved discussion (waiting on @dopiera)

___
*[google/cloud/storage/tests/object_integration_test.cc, line 807 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5031#-MGnOPXcCKNplKVtOl22:-MHuzJix4adb-L-WX9F-:by0vvk9) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/da0c04a10ad56e53ff0857c8496821d02fc5e1f6/google/cloud/storage/tests/object_integration_test.cc#L807)):*
<details><summary><i>Previously, dopiera (Marek Dopiera) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I am still seeing `return` instead of `GTEST_SKIP()`?


<!-- Sent from Reviewable.io -->

2020-09-23 12:58 UTC, dopiera reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5031)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @coryan)

___
*[google/cloud/storage/tests/object_integration_test.cc, line 807 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5031#-MGnOPXcCKNplKVtOl22:-MHv1jD18c3vjEbsL_z2:b-hi9yf9) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/da0c04a10ad56e53ff0857c8496821d02fc5e1f6/google/cloud/storage/tests/object_integration_test.cc#L807)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I am still seeing `return` instead of `GTEST_SKIP()`?
</blockquote></details>

Ooops, fixed.


<!-- Sent from Reviewable.io -->

2020-09-23 14:48 UTC, coryan approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5031)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-23 14:49 UTC, coryan approved these changes
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5031)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-23 14:52 UTC, merged