cleanup(storage): Remove references of BucketPolicyOnly
googleapis/google-cloud-cpp pull request #5254
Opened 2020-10-14 23:58 UTC by remyabel

Fixes: #3194

**BREAKING CHANGE**

* `UniformBucketLevelAccess` was known as `BucketPolicyOnly` during the beta.
  For compatibility the C++ Cloud Storage library supported both, however
  `BucketPolicyOnly` is now completely removed.

2020-10-15 01:08 UTC, coryan requested changes
Let me kick start the builds +kokoro:run while I think about this.  Breaking changes always make me uncomfortable, sometimes they are the "Right Thing":tm: 

One thought, maybe we should announce this in two consecutive releases, and remove it around 60 days after the first announcement.  WDYT?

> Reviewed 4 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5254#-:-MJdj-sN0bX7b0LND9yj:btny9lr)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @remyabel)

___
*[google/cloud/storage/bucket_metadata.h, line 156 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5254#-MJdjSEH10hCEwlgM_Jm:-MJdjSEH10hCEwlgM_Jn:b-c13taw) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b1a726cc8e88a7f6590cdf6a50229f062b75827f/google/cloud/storage/bucket_metadata.h#L156)):*
> ```objc
>   std::chrono::system_clock::time_point locked_time;
> };
> using BucketPolicyOnly = UniformBucketLevelAccess;
> ```

I think I would like to keep this alias, even if we do not use it.


<!-- Sent from Reviewable.io -->

2020-10-15 01:56 UTC, remyabel reviewed
I assume you mean leave this PR open until users get a chance to change their code? Sounds fine to me.

Side note: I still cannot see the Kokoro logs. Any word on that? I also think I need to fix the ABI dump but Docker is unreliable on my slow internet, so let me do the changes manually and I'll post them tomorrow.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5254#-:-MJdxySb8tDaSnlHZ_6L:b465bce)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @coryan)

___
*[google/cloud/storage/bucket_metadata.h, line 156 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5254#-MJdjSEH10hCEwlgM_Jm:-MJdxvlH91r7GQMvWQjd:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b1a726cc8e88a7f6590cdf6a50229f062b75827f/google/cloud/storage/bucket_metadata.h#L156)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think I would like to keep this alias, even if we do not use it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-15 13:41 UTC, coryan reviewed
> I assume you mean leave this PR open until users get a chance to change their code? Sounds fine to me.

More than that. We need to make a separate change where we make an announcement in the CHANGELOG, we need to include this announcement int the release notes for the 2020-11 release (and I think the 2020-12 and 2021-01 releases).  The announcement should include a date when we would retire the API (I think "at or around 2021-01-15" is the language we should use).

I would think we would remove after the API early after 2021-01 release, so the first release that includes this change would be in 2021-02.

> Side note: I still cannot see the Kokoro logs. Any word on that?

Sorry, escaped my mind.  This is working for me from my personal account, on personal equipment and in incognito mode.  I had a family member check on their equipment and personal account, works for them too. A colleague checked on their personal account and also using their family member account (and equipment), works for them also. One of the contractors checked, works for them.  I had a friend check on their account, works too.

Looks more plausible that it is a problem with your laptop or account?  One thing I noticed: in one of my browsers I was logged out from my personal Google account and it refused to give me access until either (a) I used incognito mode, or (b) I logged back into my account.  Seems like the UI accepts completely anonymous access (the incognito account), but if you have expired tokens/cookies/something it refuses to grant you access.  Could that be your case?

> Reviewed 2 of 9 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5254#-:-MJgCeC_5SCdhCO73AW9:b-ekawaq)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-15 14:15 UTC, remyabel reviewed
Incognito mode wasn't enough for me. I had to create a new profile so I guess my browser settings are too "private". Deeply apologize for the inconvenience.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5254#-:-MJgbB9k1LBokAJVmq68:b7cek2z)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-05 18:55 UTC, coryan commented
Do you mind closing the PR until we are ready to get back to it?

2020-11-05 20:47 UTC, closed without merging