feat: Enforce id limits in instance emulator
googleapis/google-cloud-cpp pull request #5642
Opened 2020-12-16 15:30 UTC by amitchauhan1007

2020-12-16 15:45 UTC, coryan reviewed
Looks good, one nit about the definition of the constants.

2020-12-16 15:45 UTC, coryan commented on google/cloud/bigtable/tests/instance_admin_emulator.cc
> +    constexpr int kMaxInstanceIdLength = 33;
The project is "east const" and we prefer `auto`: s/constexpr int/auto constexpr/ here and below.

2020-12-16 17:44 UTC, devbww requested changes

2020-12-16 17:44 UTC, devbww commented on google/cloud/bigtable/tests/instance_admin_emulator.cc
> +    if (((request->instance_id()).size() > kMaxInstanceIdLength) &&
I presume these should all be disjunctions.

2020-12-16 17:50 UTC, devbww requested changes

2020-12-16 17:50 UTC, devbww commented on google/cloud/bigtable/tests/instance_admin_emulator.cc
> +      throw std::invalid_argument(
Raw `throw`s don't compile in the "noex" builds.  Consider `google/cloud/internal/throw_delegate.h`.

2021-01-05 21:25 UTC, coryan commented
@amitchauhan1007 no longer works with us, I will close this PR and send a new one with these changes.

2021-01-05 21:25 UTC, closed without merging