feature(iam): add IAMCredentials service library
googleapis/google-cloud-cpp pull request #5643
Opened 2020-12-16 18:15 UTC by scotthart

This PR sets up the google/cloud/iam directory and adds the generated code for the IAMCredentials service defined in `google/iam/credentials/v1/iamcredentials.proto`, as well as, hand authored integration tests. Samples and additional documentation will be added at a later date. This service should be considered to be in a pre-alpha state.

2020-12-16 19:11 UTC, coryan requested changes
This is a lot of generated code.  Left comments here and there as I noticed things that were not quite right.

> Reviewed 34 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-:-MOguFdW4qREIWJsZ9-w:b-vc5g7v)* status: all files reviewed, 22 unresolved discussions (waiting on @scotthart)

___
*[ci/kokoro/docker/build-in-docker-bazel.sh, line 189 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgokNQ7uKxihZ59yNN:-MOgokNQ7uKxihZ59yNO:b-57iywf) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/ci/kokoro/docker/build-in-docker-bazel.sh#L189)):*
> ```Shell
>   fi
> 
>   if ! test_against_production "iam"; then
> ```

I understand the appeal of consistency, but it is unlikely that we will ever test this against anything other than production.  There is no emulator, right?
___
*[ci/test-abi/iam_client.expected.abi.dump.gz, line 0 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgp0oZ4mh-ngc9GkMS:-MOgp0oZ4mh-ngc9GkMT:b-u2yyen) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/ci/test-abi/iam_client.expected.abi.dump.gz#L0)):*
FYI, you may want to delay committing this function (and adding the test) until the library is close to GA (as opposed to Beta).
___
*[google/cloud/iam/CMakeLists.txt, line 21 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgxB9u9yCWBNDLVa5B:-MOgxB9v-3P_aWwfM_EO:bnkg9qk) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/CMakeLists.txt#L21)):*
> ```CMake
> set(DOXYGEN_PROJECT_NUMBER "${GOOGLE_CLOUD_CPP_VERSION} (Beta)")
> set(DOXYGEN_EXAMPLE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/samples
>                          ${CMAKE_CURRENT_SOURCE_DIR}/quickstart)
> ```

I did not see a quickstart.  Do we plan to create one for this library?  The quickstart is a useful starting point for application developers (obviously), but it is also used to test that our `install` rules work.
___
*[google/cloud/iam/config.cmake.in, line 24 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgq4wo8XYoKguMGZ9A:-MOgq4wo8XYoKguMGZ9B:b-nmzmm2) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/config.cmake.in#L24)):*
> ```
> include("${CMAKE_CURRENT_LIST_DIR}/iam-targets.cmake")
> 
> add_library(googleapis-c++::iam_client IMPORTED INTERFACE)
> ```

Please see #5531, there is a better way to do this:

https://github.com/GoogleCloudPlatform/functions-framework-cpp/blob/97790429115041bcbbd1f9cb51b16481fc7da253/google/cloud/functions/CMakeLists.txt#L67-L71
___
*[google/cloud/iam/iam_credentials_client.gcpcxx.pb.h, line 30 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgp_935ShdVYEeXdoq:-MOgp_935ShdVYEeXdor:b-7yc1jo) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/iam_credentials_client.gcpcxx.pb.h#L30)):*
> ```objc
> namespace google {
> namespace cloud {
> namespace iam {
> ```

FYI: consider #5622 
___
*[google/cloud/iam/iam_credentials_connection.gcpcxx.pb.h, line 26 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgqWyr5RQ70LlCAlSK:-MOgqWyr5RQ70LlCAlSL:b-tqtvl0) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/iam_credentials_connection.gcpcxx.pb.h#L26)):*
> ```objc
> #include "google/cloud/backoff_policy.h"
> #include "google/cloud/connection_options.h"
> #include "google/cloud/future.h"
> ```

This is not used?
___
*[google/cloud/iam/iam_credentials_connection.gcpcxx.pb.h, line 27 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgqaP1CCzjIklX37x7:-MOgqaP1CCzjIklX37x8:b-tqtvl0) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/iam_credentials_connection.gcpcxx.pb.h#L27)):*
> ```objc
> #include "google/cloud/connection_options.h"
> #include "google/cloud/future.h"
> #include "google/cloud/internal/pagination_range.h"
> ```

This is not used?
___
*[google/cloud/iam/iam_credentials_connection.gcpcxx.pb.h, line 28 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgqdgbBwP30_kot1pb:-MOgqdgbBwP30_kot1pc:bfqrefl) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/iam_credentials_connection.gcpcxx.pb.h#L28)):*
> ```objc
> #include "google/cloud/future.h"
> #include "google/cloud/internal/pagination_range.h"
> #include "google/cloud/polling_policy.h"
> ```

Is this used?
___
*[google/cloud/iam/iam_credentials_connection.gcpcxx.pb.cc, line 188 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgvekc71Xv4oOXM7XB:-MOgvekc71Xv4oOXM7XC:bsmirjc) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/iam_credentials_connection.gcpcxx.pb.cc#L188)):*
> ```cpp
>     std::unique_ptr<IAMCredentialsConnectionIdempotencyPolicy>
>         idempotency_policy) {
>   return std::make_shared<IAMCredentialsConnectionImpl>(
> ```

In case you care, this function is not tested at all.
___
*[google/cloud/iam/iam_credentials_connection.gcpcxx.pb.cc, line 201 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgvhltEgi4UHvFqyQW:-MOgvhltEgi4UHvFqyQX:b-n516sz) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/iam_credentials_connection.gcpcxx.pb.cc#L201)):*
> ```cpp
>     std::unique_ptr<IAMCredentialsConnectionIdempotencyPolicy>
>         idempotency_policy) {
>   return std::make_shared<IAMCredentialsConnectionImpl>(
> ```

same thing, this function is not tested.
___
*[google/cloud/iam/iam_credentials_connection_idempotency_policy.gcpcxx.pb.h, line 21 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgqlZE3fAErekg53zq:-MOgqlZE3fAErekg53zr:b-tqtvlh) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/iam_credentials_connection_idempotency_policy.gcpcxx.pb.h#L21)):*
> ```objc
> #define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_IAM_IAM_CREDENTIALS_CONNECTION_IDEMPOTENCY_POLICY_GCPCXX_PB_H
> 
> #include "google/cloud/future.h"
> ```

This is not used.
___
*[google/cloud/iam/iam_credentials_connection_idempotency_policy.gcpcxx.pb.h, line 22 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgqnf9ANfToeGPoEiY:-MOgqnf9ANfToeGPoEiZ:b-tqtvl0) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/iam_credentials_connection_idempotency_policy.gcpcxx.pb.h#L22)):*
> ```objc
> 
> #include "google/cloud/future.h"
> #include "google/cloud/internal/retry_policy.h"
> ```

This is not used?
___
*[google/cloud/iam/ci/run_integration_tests_emulator_bazel.sh, line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgqzcl2ew9IdvQxcKH:-MOgqzcl2ew9IdvQxcKI:b-oviu5n) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/ci/run_integration_tests_emulator_bazel.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

How is this file used?  There is no emulator that I know off, so when / how would it be used?
___
*[google/cloud/iam/integration_tests/iam_credentials_integration_test.cc, line 17 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgrXGq0MqdOnb0l7_E:-MOgrXGq0MqdOnb0l7_F:b-lrp1b4) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/integration_tests/iam_credentials_integration_test.cc#L17)):*
> ```cpp
> #include "google/cloud/iam/iam [...]

2020-12-17 04:44 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643)* status: 19 of 34 files reviewed, 22 unresolved discussions (waiting on @coryan)

___
*[ci/kokoro/docker/build-in-docker-bazel.sh, line 189 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgokNQ7uKxihZ59yNN:-MOi6ChR8GFkMo4Hb2ZJ:bss4a2b) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/ci/kokoro/docker/build-in-docker-bazel.sh#L189)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I understand the appeal of consistency, but it is unlikely that we will ever test this against anything other than production.  There is no emulator, right?
</blockquote></details>

Removed.
___
*[ci/test-abi/iam_client.expected.abi.dump.gz, line  at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgp0oZ4mh-ngc9GkMS:-MOi6ersCyfOrYTS9LLj:ba46hv8) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/ci/test-abi/iam_client.expected.abi.dump.gz#L)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

FYI, you may want to delay committing this function (and adding the test) until the library is close to GA (as opposed to Beta).
</blockquote></details>

Removed for now.
___
*[google/cloud/iam/CMakeLists.txt, line 21 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgxB9u9yCWBNDLVa5B:-MOi7aa40U3jSJy7IB_t:beksu6m) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/CMakeLists.txt#L21)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I did not see a quickstart.  Do we plan to create one for this library?  The quickstart is a useful starting point for application developers (obviously), but it is also used to test that our `install` rules work.
</blockquote></details>

Yes. The quickstart is another item that will likely need to be hand authored and will be included in the list I'm compiling of what all needs to be done when generating a new client.
___
*[google/cloud/iam/config.cmake.in, line 24 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgq4wo8XYoKguMGZ9A:-MOiF55XApqHn8eEvW29:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/config.cmake.in#L24)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Please see #5531, there is a better way to do this:

https://github.com/GoogleCloudPlatform/functions-framework-cpp/blob/97790429115041bcbbd1f9cb51b16481fc7da253/google/cloud/functions/CMakeLists.txt#L67-L71

</blockquote></details>

Done.
___
*[google/cloud/iam/iam_credentials_client.gcpcxx.pb.h, line 30 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgp_935ShdVYEeXdoq:-MOi7yPV4_eeFn_u0-1S:b-k48q0d) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/iam_credentials_client.gcpcxx.pb.h#L30)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

FYI: consider #5622 
</blockquote></details>

I've created an issue #5646 to modify the generator and will refactor this code in a later PR.
___
*[google/cloud/iam/iam_credentials_connection.gcpcxx.pb.h, line 26 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgqWyr5RQ70LlCAlSK:-MOi8gPRA-oboOSsMeAE:bss4a2b) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/iam_credentials_connection.gcpcxx.pb.h#L26)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This is not used?
</blockquote></details>

Removed.
___
*[google/cloud/iam/iam_credentials_connection.gcpcxx.pb.h, line 27 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgqaP1CCzjIklX37x7:-MOi8hGjDEHboU4uzAOQ:bss4a2b) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/iam_credentials_connection.gcpcxx.pb.h#L27)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This is not used?
</blockquote></details>

Removed.
___
*[google/cloud/iam/iam_credentials_connection.gcpcxx.pb.h, line 28 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgqdgbBwP30_kot1pb:-MOi8iCq5i22zqpW_vhR:bss4a2b) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/iam_credentials_connection.gcpcxx.pb.h#L28)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Is this used?
</blockquote></details>

Removed.
___
*[google/cloud/iam/iam_credentials_connection.gcpcxx.pb.cc, line 188 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgvekc71Xv4oOXM7XB:-MOi8kyHEHVYM1pOaPHi:b-rbw6ya) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/iam_credentials_connection.gcpcxx.pb.cc#L188)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

In case you care, this function is not tested at all.
</blockquote></details>

Modified integration tests to call this function.
___
*[google/cloud/iam/iam_credentials_connection.gcpcxx.pb.cc, line 201 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgvhltEgi4UHvFqyQW:-MOi8pkC3xC3shxL3dpI:b-rbw6ya) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/iam_credentials_connection.gcpcxx.pb.cc#L201)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

same thing, this function is not tested.
</blockquote></details>

Modified integration tests to call this function.
___
*[google/cloud/iam/iam_credentials_connection_idempotency_policy.gcpcxx.pb.h, line 21 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgqlZE3fAErekg53zq:-MOi8u9tCwXMneIgXKnJ:bss4a2b) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/iam_credentials_connection_idempotency_policy.gcpcxx.pb.h#L21)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This is not used.
</blockquote></details>

Removed.
___
*[google/cloud/iam/iam_credentials_connection_idempotency_policy.gcpcxx.pb.h, line 22 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgqnf9ANfToeGPoEiY:-MOi8v5r38G4efEJ2KK1:bq3sbe6) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/iam_credentials_connection_idempotency_policy.gcpcxx.pb.h#L22)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This is not used?
</blockquote></details>

For better or worse, the definition for the `Idempotency` enum is in this file. Perhaps it needs to be relocated.
___
*[google/cloud/iam/ci/run_integration_tests_emulator_bazel.sh, line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgqzcl2ew9IdvQxcKH:-MOi95qD-17qlr9rErQM:bss4a2b) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/ci/run_integration_tests_emulator_bazel.sh#L1)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

How is this file used?  There is no emulator that I know off, so when / how would it be used?
</blockquote></details>

Removed.
___
*[google/cloud/iam/integration_tests/iam_credentials_integration_test.cc, line 17 at r1](https://reviewable.io/reviews/googleapis/goo [...]

2020-12-17 15:56 UTC, coryan approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 19 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-:-MOlPaJ528THAnCCl1ZD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @scotthart)

___
*[google/cloud/iam/integration_tests/iam_credentials_integration_test.cc, line 48 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOlNycgEvsbL8-jRlHX:-MOlNycgEvsbL8-jRlHY:b-39vks3) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/0d3d7fec13f01fc16e7b01188330f704cc2a0610/google/cloud/iam/integration_tests/iam_credentials_integration_test.cc#L48)):*
> ```cpp
>             .value_or("");
> 
>     EXPECT_FALSE(iam_service_account_.empty());
> ```

I think these should be `ASSERT_FALSE()`?  Little point in running the tests if they are not set.
___
*[google/cloud/iam/internal/iam_credentials_stub_factory.gcpcxx.pb.cc, line 35 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOgtsOm8swLf3pNiFcn:-MOlOVuM76m2g2REePRk:bb6sh2i) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/078ca8cc4563674550e621741fa4234026a87740/google/cloud/iam/internal/iam_credentials_stub_factory.gcpcxx.pb.cc#L35)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Created issue #5647 to update the stub factory function to process all the fields available in the ConnectionOptions.
</blockquote></details>

Ack.


<!-- Sent from Reviewable.io -->

2020-12-17 20:24 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643)* status: 34 of 35 files reviewed, 1 unresolved discussion (waiting on @coryan)

___
*[google/cloud/iam/integration_tests/iam_credentials_integration_test.cc, line 48 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-MOlNycgEvsbL8-jRlHX:-MOmMwbrCohqHLrY9GT3:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/0d3d7fec13f01fc16e7b01188330f704cc2a0610/google/cloud/iam/integration_tests/iam_credentials_integration_test.cc#L48)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think these should be `ASSERT_FALSE()`?  Little point in running the tests if they are not set.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-17 21:24 UTC, coryan approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5643#-:-MOm_jQ2BzKJGMxV9Nd5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @scotthart)



<!-- Sent from Reviewable.io -->

2020-12-17 22:40 UTC, merged