feat: allow cq actions in StartOperation
googleapis/google-cloud-cpp pull request #5666
Opened 2020-12-30 19:15 UTC by dopiera

Before this PR, the `StartOp` passed to
`CompletionQueueImpl::StartOperation` was called with the
`CompletionQueueImpl` lock held. This became problematic
because in #5665 we want to schedule timers on the `CompletionQueue`
when calling starting the operations.

2020-12-30 19:28 UTC, coryan requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5666)* status: all files reviewed, 1 unresolved discussion (waiting on @dopiera)

___
*[google/cloud/internal/default_completion_queue_impl.cc, line 242 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5666#-MPp4wpU9LCOmqA5BceT:-MPp4wpVAjdmkSDBeriX:bhzg81b) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ee935f7c6ce10518c92aeae721d94739a08dbe11/google/cloud/internal/default_completion_queue_impl.cc#L242)):*
> ```cpp
>   auto ins = pending_ops_.emplace(tag, std::move(op));
>   if (ins.second) {
>     lk.unlock();
> ```

I am sure you saw the TSAN and ASAN failures in #5665, and the failures in this PR.  They are reporting assertions here:

https://github.com/grpc/grpc/blob/95ab12cf8fca2d92b4a097369dd8249cf8997b9f/src/cpp/common/alarm.cc#L56

I think what happens is that a separate thread may shutdown the completion queue (including shutting down the `grpc::CompletionQueue`) after `unlock()` is called, but before `start()` gets called.


<!-- Sent from Reviewable.io -->

2020-12-30 20:25 UTC, dopiera reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5666)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @coryan)

___
*[google/cloud/internal/default_completion_queue_impl.cc, line 242 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5666#-MPp4wpU9LCOmqA5BceT:-MPpJBTP4MSkkV90aD0m:b-lbk67u) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ee935f7c6ce10518c92aeae721d94739a08dbe11/google/cloud/internal/default_completion_queue_impl.cc#L242)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I am sure you saw the TSAN and ASAN failures in #5665, and the failures in this PR.  They are reporting assertions here:

https://github.com/grpc/grpc/blob/95ab12cf8fca2d92b4a097369dd8249cf8997b9f/src/cpp/common/alarm.cc#L56

I think what happens is that a separate thread may shutdown the completion queue (including shutting down the `grpc::CompletionQueue`) after `unlock()` is called, but before `start()` gets called.

</blockquote></details>

That's exactly that. I hope my ugly "fix" doesn't scare you :)

But TBH, we're doing a weird thing here - even though `grpc::CompletionQueue` defines scheduling new events after calling `Shutdown()` as undefined (and aborts), we are putting extra effort to handle them gracefully. Probably not the best time to change the semantics, though...


<!-- Sent from Reviewable.io -->

2020-12-30 20:36 UTC, coryan requested changes
Looking "better", just some documentation nits below.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5666#-:-MPpM3Xk2pqo5OmVskkJ:bh8xbpn)* status: all files reviewed, 2 unresolved discussions (waiting on @dopiera)

___
*[google/cloud/internal/default_completion_queue_impl.cc, line 242 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5666#-MPp4wpU9LCOmqA5BceT:-MPpL8PV-T7_g8GDYSzU:bido0u0) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/ee935f7c6ce10518c92aeae721d94739a08dbe11/google/cloud/internal/default_completion_queue_impl.cc#L242)):*
> That's exactly that. I hope my ugly "fix" doesn't scare you :)

I was not like :scream: but I was like :worried: and :thinking: 
___
*[google/cloud/internal/default_completion_queue_impl.cc, line 144 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5666#-MPpKUWOEzuemCLDaabD:-MPpKUWOEzuemCLDaabE:brnq6p) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b4c3cbb5e03dd41f9c0963ed133b5473bebb1a62/google/cloud/internal/default_completion_queue_impl.cc#L144)):*
> ```cpp
> DefaultCompletionQueueImpl::DefaultCompletionQueueImpl()
>     : shutdown_guard_(
>           std::shared_ptr<void>(reinterpret_cast<void*>(0xdeadbeef),
> ```

I cannot say that I like `0xdeadbeef` a whole lot here, I assume `nullptr` is out of the question for "reasons"?  What about `this`?
___
*[google/cloud/internal/default_completion_queue_impl.cc, line 145 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5666#-MPpKo4Y5Hm0FyC0uMN0:-MPpKo4Y5Hm0FyC0uMN1:bsy0fx8) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b4c3cbb5e03dd41f9c0963ed133b5473bebb1a62/google/cloud/internal/default_completion_queue_impl.cc#L145)):*
> ```cpp
>     : shutdown_guard_(
>           std::shared_ptr<void>(reinterpret_cast<void*>(0xdeadbeef),
>                                 [this](void*) { cq_.Shutdown(); })) {}
> ```

:thinking: why is this not UB waiting to happen?  You are capturing `this` into a shared pointer, copies of which do not outlive the object because <please fill in the blank> and then copy said <fill in> to a comment...


<!-- Sent from Reviewable.io -->

2020-12-30 20:49 UTC, dopiera reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5666)* status: all files reviewed, 2 unresolved discussions (waiting on @coryan)

___
*[google/cloud/internal/default_completion_queue_impl.cc, line 144 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5666#-MPpKUWOEzuemCLDaabD:-MPpNs9ADKEgB0F5swe7:b7l838x) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b4c3cbb5e03dd41f9c0963ed133b5473bebb1a62/google/cloud/internal/default_completion_queue_impl.cc#L144)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I cannot say that I like `0xdeadbeef` a whole lot here, I assume `nullptr` is out of the question for "reasons"?  What about `this`?
</blockquote></details>

I don't think deleter gets called on a `nullptr`. Changed to `this`.
___
*[google/cloud/internal/default_completion_queue_impl.cc, line 145 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5666#-MPpKo4Y5Hm0FyC0uMN0:-MPpP9sW6-iVnIAvk2f7:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b4c3cbb5e03dd41f9c0963ed133b5473bebb1a62/google/cloud/internal/default_completion_queue_impl.cc#L145)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

:thinking: why is this not UB waiting to happen?  You are capturing `this` into a shared pointer, copies of which do not outlive the object because <please fill in the blank> and then copy said <fill in> to a comment...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-31 15:22 UTC, coryan approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5666)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-31 15:22 UTC, merged