refactor(bigtable): pull out tests for SampleRows, AsyncSampleRows into their own test fixture
googleapis/google-cloud-cpp pull request #6599
Opened 2021-05-17 21:08 UTC by dbolduc

Pros:
* could save test time (since the async test was added)
* could have implications for #441, as we are no longer calling `SampleRowKeys` and `DropRowRange` on the same table in the emulator

Cons:
* increases `CreateTable` calls from 7 to 8 per build. We still should be fine on the GCB quota though.

2021-05-17 21:13 UTC, dbolduc commented on google/cloud/bigtable/tests/table_sample_rows_integration_test.cc
> +std::unique_ptr<Table> SampleRowsIntegrationTest::table_;
I copied [this](https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/spanner/integration_tests/data_types_integration_test.cc#L88) but without understanding. Maybe someone could explain over chat what is happening

2021-05-17 21:46 UTC, coryan requested changes
A few improvements (maybe?) for you to consider.  Looks better than before anyway.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6599#-:-M_wHdQU3Gl9lBznYKc6:bp515ak)* status: all files reviewed, 4 unresolved discussions (waiting on @dbolduc)

___
*[google/cloud/bigtable/tests/table_sample_rows_integration_test.cc, line 46 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6599#-M_wGSJk6b6v-GvC85_-:-M_wGSJk6b6v-GvC85_0:b-8tvgul) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2f891cb56268c56bbfa77bc537f619285b30c3b9/google/cloud/bigtable/tests/table_sample_rows_integration_test.cc#L46)):*
> ```cpp
>   // All we can check is that this is not empty, and that the offsets are in
>   // ascending order.
>   EXPECT_FALSE(samples->empty());
> ```

Consider: `EXPECT_THAT(*samples, Not(IsEmpty())` for the same reasons we prefer `ElementsAre()` Also this should probably be an `ASSERT_THAT()`
___
*[google/cloud/bigtable/tests/table_sample_rows_integration_test.cc, line 49 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6599#-M_wH3MO0YuKOCB883rj:-M_wH3MO0YuKOCB883rk:b-ya4yz) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2f891cb56268c56bbfa77bc537f619285b30c3b9/google/cloud/bigtable/tests/table_sample_rows_integration_test.cc#L49)):*
> ```cpp
>   std::int64_t previous = 0;
>   for (auto const& s : *samples) {
>     EXPECT_LE(previous, s.offset_bytes);
> ```

TIL: `WhenSortedBy()`

https://google.github.io/googletest/reference/matchers.html

maybe it can yield better output.  Your call.
___
*[google/cloud/bigtable/tests/table_sample_rows_integration_test.cc, line 53 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6599#-M_wHGIX4BB1ML_M3ChW:-M_wHGIX4BB1ML_M3ChX:b-pvatik) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2f891cb56268c56bbfa77bc537f619285b30c3b9/google/cloud/bigtable/tests/table_sample_rows_integration_test.cc#L53)):*
> ```cpp
>   }
>   // At least one of the samples should have non-zero offset:
>   auto last = samples->back();
> ```

This actually requires an `ASSERT_THAT(samples, Not(IsEmpty()));`
___
*[google/cloud/bigtable/tests/table_sample_rows_integration_test.cc, line 109 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6599#-M_w9Hd4ZZ8plcJ4WDl7-r1-109:-M_wEsSk7eBZplNmvj1h:b-dml63f) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2f891cb56268c56bbfa77bc537f619285b30c3b9/google/cloud/bigtable/tests/table_sample_rows_integration_test.cc#L109)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

I copied [this](https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/spanner/integration_tests/data_types_integration_test.cc#L88) but without understanding. Maybe someone could explain over chat what is happening
</blockquote></details>


I think in the olden days creating all the `Table` objects was slow, because it happened in each `SetUp()` and we moved it to a static member variable.  Since this test does it only 2 times or so, maybe you can simplify the code.  Up to you.


<!-- Sent from Reviewable.io -->

2021-05-18 01:34 UTC, dbolduc reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6599)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @coryan)

___
*[google/cloud/bigtable/tests/table_sample_rows_integration_test.cc, line 46 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6599#-M_wGSJk6b6v-GvC85_-:-M_wlzQV1cBFdtebavYa:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2f891cb56268c56bbfa77bc537f619285b30c3b9/google/cloud/bigtable/tests/table_sample_rows_integration_test.cc#L46)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Consider: `EXPECT_THAT(*samples, Not(IsEmpty())` for the same reasons we prefer `ElementsAre()` Also this should probably be an `ASSERT_THAT()`
</blockquote></details>

Done.
___
*[google/cloud/bigtable/tests/table_sample_rows_integration_test.cc, line 49 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6599#-M_wH3MO0YuKOCB883rj:-M_wn6YJ-emo37jw5XiL:b-cdqa4a) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2f891cb56268c56bbfa77bc537f619285b30c3b9/google/cloud/bigtable/tests/table_sample_rows_integration_test.cc#L49)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

TIL: `WhenSortedBy()`

https://google.github.io/googletest/reference/matchers.html

maybe it can yield better output.  Your call.
</blockquote></details>

It looks to me like`WhenSorted()` is used to sort an unsorted list. (maybe you know what the values will be, but not the order they will end up in the list).

What we need is something that tells us if our list is sorted. I do not see such a matcher, so I am leaving this code as is.
___
*[google/cloud/bigtable/tests/table_sample_rows_integration_test.cc, line 53 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6599#-M_wHGIX4BB1ML_M3ChW:-M_woURkBmQJqMfBvxdb:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2f891cb56268c56bbfa77bc537f619285b30c3b9/google/cloud/bigtable/tests/table_sample_rows_integration_test.cc#L53)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This actually requires an `ASSERT_THAT(samples, Not(IsEmpty()));`
</blockquote></details>

Done.
___
*[google/cloud/bigtable/tests/table_sample_rows_integration_test.cc, line 109 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6599#-M_w9Hd4ZZ8plcJ4WDl7-r1-109:-M_x4_k3ED88Lg3LF_U5:beijs5t) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2f891cb56268c56bbfa77bc537f619285b30c3b9/google/cloud/bigtable/tests/table_sample_rows_integration_test.cc#L109)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think in the olden days creating all the `Table` objects was slow, because it happened in each `SetUp()` and we moved it to a static member variable.  Since this test does it only 2 times or so, maybe you can simplify the code.  Up to you.
</blockquote></details>

I think I have simplified it. PTAL.


<!-- Sent from Reviewable.io -->

2021-05-18 13:01 UTC, coryan approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6599#-:-M_zZ4vD-SdbPpjBhp-2:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dbolduc)

___
*[google/cloud/bigtable/tests/table_sample_rows_integration_test.cc, line 109 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6599#-M_w9Hd4ZZ8plcJ4WDl7-r1-109:-M_zYwukELm0SaJSHdYi:bb6ywmx) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2f891cb56268c56bbfa77bc537f619285b30c3b9/google/cloud/bigtable/tests/table_sample_rows_integration_test.cc#L109)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

I think I have simplified it. PTAL.
</blockquote></details>

LGTM


<!-- Sent from Reviewable.io -->

2021-05-18 13:12 UTC, merged