chore: update CHANGELOG and abi dumps in preparation for release
googleapis/google-cloud-cpp pull request #6667
Opened 2021-06-01 21:58 UTC by scotthart

2021-06-01 22:29 UTC, coryan approved these changes
Some ideas to simplify the notes even further.

2021-06-01 22:29 UTC, coryan commented on CHANGELOG.md
> +* fix(storage): update emulator to use MultipartDecoder (#6453)
These 3 are related to the emulator, probably can skip them.

2021-06-01 22:29 UTC, coryan commented on CHANGELOG.md
> +* fix(storage): address behavior bugs (#6574)
These two are related to the emulator, probably can skip them.

2021-06-01 22:29 UTC, coryan commented on CHANGELOG.md
> +* feat(storage): impersonate service account credentials (#6441)
I think #6441 #6488 #6518 #6531 #6617 can be summarized as:

```md
 * Support unified credentials (`google::cloud::Credentials`) to initialize both the REST and gRPC plugins with the same classes.
```

2021-06-01 22:29 UTC, coryan commented on CHANGELOG.md
> +* feat: custom trust store with unified credentials (#6617)
I think you can summarize #6617 #6614 #6531 #6518 as:

```md
 * Add support for "unified" credentials, which allow applications to
   * Configure the REST and gRPC-based libraries using the same credential classes
   * Support complex credential types, such as service account impersonation
   * With this release, only usable in the `storage` library supports these classes.
```

2021-06-01 22:29 UTC, coryan commented on CHANGELOG.md
> +* feat(common): streaming RPCs that always fail (#6473)
I think this and the next are internal-only, we can skip them.

2021-06-02 15:02 UTC, dbolduc requested changes
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6667)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @scotthart)

___
*[CHANGELOG.md, line 86 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6667#-MbCASFn2UjqB0w4vxwm:-MbCASFn2UjqB0w4vxwn:bq15ckz) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/55dbf35896ace459f8142291796515fa7415593a/CHANGELOG.md#L86)):*
> ```
> * feat(bigtable): add async sample rows (#6561)
> ```

* Add asynchronous method for sampling row keys (#6561). Users that extend `bigtable::DataClient` and wish to use the new method will need to override `PrepareAsyncSampleRowKeys()`.
___
*[CHANGELOG.md, line 87 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6667#-MbCDhMjBR2Nvddm_Hvm:-MbCAFfOEVUiSdAi_TeE:b-xf4rl2) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/55dbf35896ace459f8142291796515fa7415593a/CHANGELOG.md#L87)):*
> ```
> * fix(bigtable): async bulk apply retry, backoff policy fix  (#6510)
> ```

* `bigtable::Table::AsyncBulkApply()` now respects the Retry and Backoff policies (#6510)


<!-- Sent from Reviewable.io -->

2021-06-02 16:13 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6667)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @coryan, @dbolduc, and @scotthart)

___
*[CHANGELOG.md, line 86 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6667#-MbCASFn2UjqB0w4vxwm:-MbCTCoF2cCUSFXQUjgz:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/55dbf35896ace459f8142291796515fa7415593a/CHANGELOG.md#L86)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

> ```
> * feat(bigtable): add async sample rows (#6561)
> ```

* Add asynchronous method for sampling row keys (#6561). Users that extend `bigtable::DataClient` and wish to use the new method will need to override `PrepareAsyncSampleRowKeys()`.
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 112 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6667#-Mb8_QG-yluSql4L48Wl-r2-112:-MbCT_HW4zeNynIpUUp8:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/55dbf35896ace459f8142291796515fa7415593a/CHANGELOG.md#L112)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

These two are related to the emulator, probably can skip them.
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 123 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6667#-Mb8_QG-yluSql4L48Wl-r2-123:-MbCUD2OBdWvhisoCqih:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/55dbf35896ace459f8142291796515fa7415593a/CHANGELOG.md#L123)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

These 3 are related to the emulator, probably can skip them.
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 124 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6667#-Mb8_QG-yluSql4L48Wl-r2-124:-MbCUDSR5iwLLqmjE7tg:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/55dbf35896ace459f8142291796515fa7415593a/CHANGELOG.md#L124)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think #6441 #6488 #6518 #6531 #6617 can be summarized as:

```md
 * Support unified credentials (`google::cloud::Credentials`) to initialize both the REST and gRPC plugins with the same classes.
```

</blockquote></details>

Done.
___
*[CHANGELOG.md, line 128 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6667#-Mb8_QG-yluSql4L48Wl-r2-128:-MbCUnxg0fwu6O4zsxtX:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/55dbf35896ace459f8142291796515fa7415593a/CHANGELOG.md#L128)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think you can summarize #6617 #6614 #6531 #6518 as:

```md
 * Add support for "unified" credentials, which allow applications to
   * Configure the REST and gRPC-based libraries using the same credential classes
   * Support complex credential types, such as service account impersonation
   * With this release, only usable in the `storage` library supports these classes.
```

</blockquote></details>

Done.
___
*[CHANGELOG.md, line 134 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6667#-Mb8_QG-yluSql4L48Wl-r2-134:-MbCUoGaBMYmaKHDVFJN:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/55dbf35896ace459f8142291796515fa7415593a/CHANGELOG.md#L134)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think this and the next are internal-only, we can skip them.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-02 16:16 UTC, coryan commented on CHANGELOG.md
> +  With this release, only usable in the `storage` library supports these classes.
Ugh, sorry, my grammar was awful here .. maybe "With this release only the `storage` library supports unified credentials"?

2021-06-02 16:16 UTC, coryan approved these changes

2021-06-02 16:27 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6667)* status: 0 of 7 files reviewed, 8 unresolved discussions (waiting on @coryan, @dbolduc, and @scotthart)

___
*[CHANGELOG.md, line 127 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6667#-Mb8_QG-yluSql4L48Wl-r3-127:-MbCYM8ACcbJ9GU3N3gg:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/80870bef0709a49e9b596dc2e9ca2f2c75094322/CHANGELOG.md#L127)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Ugh, sorry, my grammar was awful here .. maybe "With this release only the `storage` library supports unified credentials"?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-02 17:00 UTC, dbolduc approved these changes

2021-06-02 17:00 UTC, merged