feat(GCS+gRPC): checksums on ObjectInsert
googleapis/google-cloud-cpp pull request #6967
Opened 2021-07-10 18:02 UTC by coryan

With this change `ObjectInsert()` uses all the checksum options,
allowing applications to provide checksums (when known in advance),
disabling some checksums, or letting the library compute them.

Part of the work for #4156 and for #4157

2021-07-10 22:38 UTC, dbolduc requested changes
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6967)* status: 3 of 5 files reviewed, 9 unresolved discussions (waiting on @coryan)

___
*[google/cloud/storage/internal/grpc_client.cc, line 1758 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6967#-MeHJ-wy615aBriSam-x:-MeHJ-wy615aBriSam-y:bb8r7o7) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2dfa015bc5f292716a33151c64aefe79061f3d2b/google/cloud/storage/internal/grpc_client.cc#L1758)):*
> ```cpp
>     // convert this to the format expected by proto, which is just a 32-bit
>     // integer. But the value received by the application might be incorrect, so
>     // we need to validated it.
> ```

s/validated/validate/
___
*[google/cloud/storage/internal/grpc_client.cc, line 1763 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6967#-MeHXRfm8soSZ7zYbrZt:-MeHXRfm8soSZ7zYbrZu:b-w6pudg) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2dfa015bc5f292716a33151c64aefe79061f3d2b/google/cloud/storage/internal/grpc_client.cc#L1763)):*
> ```cpp
>     if (!as_proto.ok()) return std::move(as_proto).status();
>     checksums.mutable_crc32c()->set_value(*as_proto);
>   } else if (request.GetOption<DisableCrc32cChecksum>().value_or(false)) {
> ```

Do we need to consider a case where `DisableCrc32cChecksum` and `Crc32cChecksumValue` are set?

If so, I think I would expect a `DisableCrc32cChecksum` of `true` to take precedence. Which would mean switching the order of the `if` and `else if` clauses.... but I might not understand what is happening here.


(Comment also applies below to MD5 Hash)
___
*[google/cloud/storage/internal/grpc_client_insert_object_media_test.cc, line 54 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6967#-MeHVQcj7kFRcrzOwuR4:-MeHVQcj7kFRcrzOwuR5:b7dbnjk) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2dfa015bc5f292716a33151c64aefe79061f3d2b/google/cloud/storage/internal/grpc_client_insert_object_media_test.cc#L54)):*
> ```cpp
>     checksummed_data {
>       content: "The quick brown fox jumps over the lazy dog"
>       # grpc_client_object_request_test.cc documents on this magic value
> ```

s/documents on this/documents this/
___
*[google/cloud/storage/internal/grpc_client_object_request_test.cc, line 37 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6967#-MeHS69kERaXCd1vEnYQ:-MeHS69kERaXCd1vEnYR:brjq59t) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2dfa015bc5f292716a33151c64aefe79061f3d2b/google/cloud/storage/internal/grpc_client_object_request_test.cc#L37)):*
> ```
> /bin/echo -n $TEXT >/tmp/fox.txt
> ```
I'd add a space for readability `/bin/echo -n $TEXT > /tmp/fox/txt`
___
*[google/cloud/storage/internal/grpc_client_object_request_test.cc, line 41 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6967#-MeHRpuVD1MpRG_sPDLN:-MeHRpuVD1MpRG_sPDLO:bmguict) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2dfa015bc5f292716a33151c64aefe79061f3d2b/google/cloud/storage/internal/grpc_client_object_request_test.cc#L41)):*
> ```
> //	Hash (crc32c):		ImIEBA==
> //	Hash (md5):		nhB9nTcrtoJr2B01QqQZ1g==
> ```
should we replace the tabs with spaces?
___
*[google/cloud/storage/internal/grpc_client_object_request_test.cc, line 56 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6967#-MeHSTE3-GjXA3LwHcER:-MeHSLl--iP0kc8mBQDw:b-mzl4kx) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2dfa015bc5f292716a33151c64aefe79061f3d2b/google/cloud/storage/internal/grpc_client_object_request_test.cc#L56)):*
> ```
> //	Hash (crc32c):		StZ/gA==
> //	Hash (md5):		StEvo2V/qoDCuaktZSw3IQ==
> ```
more tabs
___
*[google/cloud/storage/internal/grpc_client_object_request_test.cc, line 92 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6967#-MeHYS7VEHJW3o2TXTtT:-MeHYS7W0Hyf87cguF5W:b-vkcu8t) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2dfa015bc5f292716a33151c64aefe79061f3d2b/google/cloud/storage/internal/grpc_client_object_request_test.cc#L92)):*
> ```cpp
>     std::string expected_checksums;
>   } cases[] = {
>       // These tests provide the "wrong" hashes, this is what would happen if
> ```

s/, this/. This/
___
*[google/cloud/storage/internal/grpc_client_object_request_test.cc, line 95 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6967#-MeHYhuo7Dk5qS6fpZyX:-MeHYhuo7Dk5qS6fpZyY:bxowc9t) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2dfa015bc5f292716a33151c64aefe79061f3d2b/google/cloud/storage/internal/grpc_client_object_request_test.cc#L95)):*
> ```cpp
>       // one was (for example) reading a GCS file, obtained the expected hashes
>       // from GCS, and then uploaded to another GCS destination *but*
>       // the data was somehow corrupted locally (say a bad disk), we don't want
> ```

s/, we/. In that case, we/
___
*[google/cloud/storage/internal/grpc_client_object_request_test.cc, line 110 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6967#-MeHURmLBQCTp751LiAM:-MeHURmLBQCTp751LiAN:b-r6jmom) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2dfa015bc5f292716a33151c64aefe79061f3d2b/google/cloud/storage/internal/grpc_client_object_request_test.cc#L110)):*
> ```cpp
>             r.set_option(DisableCrc32cChecksum(false));
>           },
>           R"pb(md5_hash: "9e107d9d372bb6826bd81d3542a419d6"
> ```

nit: other cases have a line break after the `R"pb(`


<!-- Sent from Reviewable.io -->

2021-07-11 14:55 UTC, coryan reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6967)* status: 2 of 5 files reviewed, 5 unresolved discussions (waiting on @dbolduc)

___
*[google/cloud/storage/internal/grpc_client.cc, line 1758 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6967#-MeHJ-wy615aBriSam-x:-MeKrhyS4R9EsTOwobRQ:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2dfa015bc5f292716a33151c64aefe79061f3d2b/google/cloud/storage/internal/grpc_client.cc#L1758)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

s/validated/validate/
</blockquote></details>

Done.
___
*[google/cloud/storage/internal/grpc_client.cc, line 1763 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6967#-MeHXRfm8soSZ7zYbrZt:-MeKrmZn67s1030GkQlU:b-yr9plh) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2dfa015bc5f292716a33151c64aefe79061f3d2b/google/cloud/storage/internal/grpc_client.cc#L1763)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

Do we need to consider a case where `DisableCrc32cChecksum` and `Crc32cChecksumValue` are set?

If so, I think I would expect a `DisableCrc32cChecksum` of `true` to take precedence. Which would mean switching the order of the `if` and `else if` clauses.... but I might not understand what is happening here.


(Comment also applies below to MD5 Hash)
</blockquote></details>

Hmmm... `Crc32cChecksumValue()` *implies* `DisableCrc32cChecksum(true)`.  If I am providing the checksum to the library, then the library does not need to compute its own checksum, it is wasteful, and the point of me providing a value is that I got it from somewhere else, not from the actual data.  If I wanted to just compute it from the data I would let the library do it. That is the behavior with REST, and the behavior we want here.
___
*[google/cloud/storage/internal/grpc_client_insert_object_media_test.cc, line 54 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6967#-MeHVQcj7kFRcrzOwuR4:-MeKsaXs5kAnFPhIeaQW:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2dfa015bc5f292716a33151c64aefe79061f3d2b/google/cloud/storage/internal/grpc_client_insert_object_media_test.cc#L54)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

s/documents on this/documents this/
</blockquote></details>

Done.
___
*[google/cloud/storage/internal/grpc_client_object_request_test.cc, line 92 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6967#-MeHYS7VEHJW3o2TXTtT:-MeKtQPHBdtc5UTPQyY_:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2dfa015bc5f292716a33151c64aefe79061f3d2b/google/cloud/storage/internal/grpc_client_object_request_test.cc#L92)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

s/, this/. This/
</blockquote></details>

Done.
___
*[google/cloud/storage/internal/grpc_client_object_request_test.cc, line 95 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6967#-MeHYhuo7Dk5qS6fpZyX:-MeKtTMB-0qmzekq45Lm:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2dfa015bc5f292716a33151c64aefe79061f3d2b/google/cloud/storage/internal/grpc_client_object_request_test.cc#L95)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

s/, we/. In that case, we/
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-11 16:57 UTC, dbolduc reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6967)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @dbolduc)

___
*[google/cloud/storage/internal/grpc_client.cc, line 1763 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6967#-MeHXRfm8soSZ7zYbrZt:-MeLUkqe2Qg0e-nZmsHu:b-ivfv8f) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/2dfa015bc5f292716a33151c64aefe79061f3d2b/google/cloud/storage/internal/grpc_client.cc#L1763)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Hmmm... `Crc32cChecksumValue()` *implies* `DisableCrc32cChecksum(true)`.  If I am providing the checksum to the library, then the library does not need to compute its own checksum, it is wasteful, and the point of me providing a value is that I got it from somewhere else, not from the actual data.  If I wanted to just compute it from the data I would let the library do it. That is the behavior with REST, and the behavior we want here.
</blockquote></details>

Ok. That helps me understand. Thanks.


<!-- Sent from Reviewable.io -->

2021-07-11 16:57 UTC, dbolduc approved these changes

2021-07-11 17:02 UTC, merged