feat(bigtable): add benchmark to measure MutationBatcher throughput
googleapis/google-cloud-cpp pull request #7070
Opened 2021-07-27 21:42 UTC by dbolduc

Fixes #7024 

A new benchmark to measure the throughput of `bigtable::MutationBatcher` given maximum number of mutations per batch and maximum number of outstanding batches.

### Design choices:

#### Shards / Splits / Row keys:

There are no initial splits provided to the table. I considered splitting based on:
* % of table - e.g. always split into 10 shards with 10% of the rows in each.
* \# of rows in split - e.g. split such that each shard will contain 1,000,000 rows
* \# of threads - e.g. launch T threads. split such that each shard contains 1/T of the data

(Our other benchmarks launch 10 threads and split the 10M rows into 10 shards. This is where my example numbers are coming from) 

But my current thinking is that it wouldn't be helpful at this time. I assume that the advantage of initial splits come when you concurrently send batches that hit different shards (where the mutations within a batch all belong to the same shard). Please correct me if I'm wrong.

The `MutationBatcher` is fed mutations from many threads. It simply [appends](https://github.com/googleapis/google-cloud-cpp/blob/1d18bca029224cab43a2e63d9a00716033cfc5df/google/cloud/bigtable/mutation_batcher.cc#L86) new mutations into the current batch. So I think the only way (presently) to guarantee mutations from a single shard make it into a single batch is to only send mutations from that shard across all threads. But then we are not getting the advantage of concurrent batches going to _different_ shards.

Initial splits might be worth adding. It would especially be worth adding if we change the guts of the `MutationBatcher` to try to batch mutations with splits in mind. I think it would come with a `--shard-count` option. And the row keys would be something like: `"row" + shard_index + mutation_index`. 

#### Cutoff deadline:

I want to be able to run the benchmark in a loop with random settings. Some of these settings are going to be very slow. I do not want to wait for them. I want to say something like "the best settings do M mutations in ~25s , so let me set a `--max-time=60s`. 

There might be a way to do this in bash with `timeout` but 1) I don't know how, 2) I want to get some sort of throughput measure if the program does get cut off.

This does complicate the code a little bit. I am obviously open to a better way to do this.

#### Logging progress:

Logging the progress of the writes also complicates the code a bit. But it's nice to know the program is doing something.

#### Things I didn't do:
* Accept an App Profile ID. Should I?
* Add ability to set maximum size in bytes of a batch (instead of maximum requests per batch). I didn't think this was necessary, as all mutations are of the same size. So I don't know if anything would be gained here.
* Make a way to compare this to using `Table::Apply` or `Table::BulkApply` directly. Our other benchmarks record throughput for manually sent batches. We can use those to get a feel for the throughput of the direct table methods.
* Make gRPC channel count configurable for the `DataClient`. It just uses the default.
* Have a setting for random row keys (instead of sequenced). I originally had this in, but I realized we are not even sending the batcher sequenced row keys, as discussed above in the initial splits section.
* Report total batches sent by the `MutationBatcher`. I think this data is valuable, but getting it is not yet native to the batcher. My plan is to first: get the benchmark done. Then second: modify `MutationBatcher` to record batches sent + update this benchmark to report the data.
* Use a version of `MutationBatcher::AsyncApply()` that uses the table's background threads. This method hasn't been made yet. Similar to the total batches, I want to first get the benchmark done before adding this feature.

#### Things that are highly questionable:
* I set the background thread pool size for the table to be equal to `max_batches`. I thought this made sense, but maybe I need to cap it. We probably don't want hundreds of threads if we set the option too high...
* I left `column_family` and `column` in the options struct... so they are essentially hard coded.

2021-07-27 23:05 UTC, coryan requested changes

2021-07-27 23:05 UTC, coryan commented on google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc
> +                           bool const& log) {
Ditto for the `std::int64_t` parameters.

2021-07-27 23:05 UTC, coryan commented on google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc
> +    for (std::int64_t i = start; i < end; ++i) {
I would just write `for (auto i = start; i != end; ++i)` 🤷

2021-07-27 23:05 UTC, coryan commented on google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc
> +            << options->max_batches << "," << snapshot.elapsed_time.count()
The `PerThread` timer may be overkill here.  Consider just using a steady clock if you are not interested in CPU time.  Or use the `PerProcess` timer and report the CPU time?

2021-07-28 06:01 UTC, dbolduc reviewed
I also (hopefully) dealt with the `std::max` errors on the kokoro builds. PTAL.

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-:-Mffdpj72kjpov8g3Z4j:bv6efqq)* status: 0 of 10 files reviewed, 14 unresolved discussions (waiting on @coryan)

___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, line 43 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-MfdurCOx7A_LGmOF1OI-r3-43:-Mff4Bqy9-_6uVSQsKgu:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c41e963c3193b6e6cd182a0d62eff8a22b6027dd/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc#L43)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

"effective ... that maximize throughput" maybe one or the other?
</blockquote></details>

Done.
___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, line 48 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-MfdurCOx7A_LGmOF1OI-r3-48:-Mff4kVFBKVbuHUfu6U9:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c41e963c3193b6e6cd182a0d62eff8a22b6027dd/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc#L48)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Could be slow because the options are bad or because the server is having a bad day, maybe?
</blockquote></details>

Done.
___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, line 144 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-MfdurCOx7A_LGmOF1OI-r3-144:-MffA8czEWQW4F5TQYTE:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c41e963c3193b6e6cd182a0d62eff8a22b6027dd/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc#L144)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

s/return -1/return 1/ unless you really want the exit status to be 255 or something. Consider `return EXIT_FAILURE;` if you want to make the C++ language lawyers happy.
</blockquote></details>

Done.
___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, line 150 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-MfdurCOx7A_LGmOF1OI-r3-150:-MffCcapBGaJs93fxYVy:b-80tlqk) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c41e963c3193b6e6cd182a0d62eff8a22b6027dd/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc#L150)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Will that be clear enough?  Do you wan to print the name of the table and so forth?
</blockquote></details>

Sure.
___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, line 181 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-MfdurCOx7A_LGmOF1OI-r3-181:-Mff_FuN2RqZLCemjPTY:bf6jvoh) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c41e963c3193b6e6cd182a0d62eff8a22b6027dd/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc#L181)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Why not just a regular `std::thread`?  You can use `std::thread::joinable()` to join if needed:

https://en.cppreference.com/w/cpp/thread/thread/joinable

</blockquote></details>

Ah. My previous code reveals my ignorance of how to use `std::thread::operator=`. Thanks for sharing the reference link.
___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, line 200 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-MfdurCOx7A_LGmOF1OI-r3-200:-MffDql42qEsANgPIHBl:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c41e963c3193b6e6cd182a0d62eff8a22b6027dd/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc#L200)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Ditto for the `std::int64_t` parameters.
</blockquote></details>

Done.
___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, line 210 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-MfdurCOx7A_LGmOF1OI-r3-210:-MffEOlMClJaiNAwdaGW:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c41e963c3193b6e6cd182a0d62eff8a22b6027dd/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc#L210)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

can you `std::move(mut)` here?
</blockquote></details>

Done.
___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, line 215 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-MfdurCOx7A_LGmOF1OI-r3-215:-MffEjhLC82E4-RXA83d:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c41e963c3193b6e6cd182a0d62eff8a22b6027dd/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc#L215)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think we need braces in this `if/else`.
</blockquote></details>

Done.
___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, line 223 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-MfdurCOx7A_LGmOF1OI-r3-223:-MffF6pj1dicTjgyyS7N:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c41e963c3193b6e6cd182a0d62eff8a22b6027dd/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc#L223)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Ditto, braces here.  We only use `if(foo) ...;` when it fits in a single line.
</blockquote></details>

Done.
___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, line 232 at r3](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-MfdurCOx7A_LGmOF1OI-r3-232:-MffKeb91v8tOlVkpljf:bs9en3d) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/c41e963c3193b6e6cd182a0d62eff8a22b6027dd/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc#L232)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Consider:

```cc
std::int64_t start = 0;
std::vector<std::future<void>> tasks(options->thread_count);
for (auto& t : tasks) {
  auto end = ...;
  t = std::async(std::launch::async, write, start, end, start == 0);
  start = end;
}
```

You could use a `std::transform()` too if you are into that sort of thing.

</blockquote></details>

`Ctrl+C` + `Ctrl+V`.... Done.
___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, line 206 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-MfdurCOx7A_LGmOF1OI-r4-206:-MffDqCT1gzDJ4eW9CmA:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4f3d9c809b55174cc72af817b9145575598b7456/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc#L206)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I would just write `for (auto i = start; i != end; ++i)` 🤷 
</blockquote></details>

Done.
___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, line 255 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-MfdurCOx7A_LGmOF1OI-r4-255:-MffLulW1UmkYFw31GD5:bcufdt2) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4f3d9c809b55174cc72af817b9145575598b7456/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc#L255)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

The `PerThread` timer may be overkill here.  Consider just using a steady clock if you are not interested in CPU time.  Or use the `PerProcess` timer and report th [...]

2021-07-28 12:36 UTC, coryan requested changes
>  But then we are not getting the advantage of concurrent batches going to different shards.

Maybe we should consider keeping a mutation batcher per shard / split.  Or maybe just deliver the mutations in order. I think there is a large search space for optimization here.

> Reviewed 7 of 10 files at r1, 1 of 1 files at r2, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-:-Mfh5cQ_BjU2fop6QkDU:bvgsaxo)* status: all files reviewed, 4 unresolved discussions (waiting on @dbolduc)

___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, line 206 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-MfdurCOx7A_LGmOF1OI-r4-206:-Mfh34ib6ly_QiEyqa7G:bfwv67) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/4f3d9c809b55174cc72af817b9145575598b7456/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc#L206)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: I think almost everywhere else we write `i != end`.
___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, line 135 at r5](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-Mfh1YJt7wCL_gAcRWJF:-Mfh1YJt7wCL_gAcRWJG:bxu73ys) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/77585fba61ad42030b01223b593036e6e52cd743/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc#L135)):*
> ```cpp
>     std::string table_id_chars =
>         "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_";
>     table_id = "table-" + Sample(generator, 8, table_id_chars);
> ```

I see your self-test creates a table.  Over time these can leak: this program may crash or timeout before having a chance to delete the table.  In other programs that create persistent resources as part of the integration test we try to name the resources something like `foo-YYYY-MM-DD-${random_stuff}` and then delete them if they are older than 2 days.
___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, line 154 at r5](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-Mfh23zx4HxZ38LYj7nH:-Mfh23zx4HxZ38LYj7nI:b-zeqpwg) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/77585fba61ad42030b01223b593036e6e52cd743/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc#L154)):*
> ```cpp
>         return 1;
>       }
>       std::cout << table.status() << std::endl;
> ```

I was suggesting that the table name should always be printed, because the error won't tell you what failed, just the type of error.
___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, line 186 at r5](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-Mfh4B_6CTOvKehxbBxA:-Mfh4B_6CTOvKehxbBxB:bw24xgq) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/77585fba61ad42030b01223b593036e6e52cd743/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc#L186)):*
> ```cpp
>   // Start the MutationBatcher thread
>   CompletionQueue cq;
>   std::thread cq_runner([&cq] { cq.Run(); });
> ```

While you have N threads generating mutations, you only have 1 thread sending RPCs and handling responses to the RPCs. That may be less than ideal.

Consider:

```cc
std::vector<std::vector> background(options->background_threads);
std::generate_n(background.begin(), background.size(), [&cq] { return std::thread{[](CompletionQueue q) { q.Run(); }, cq}; });
```
___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_options.cc, line 139 at r5](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-Mfh3Po415eOUNhDtq7r:-Mfh3Po415eOUNhDtq7s:bvi2uf) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/77585fba61ad42030b01223b593036e6e52cd743/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_options.cc#L139)):*
> ```cpp
>     return make_status(os);
>   }
>   if (options.batch_size <= 0 || options.batch_size > 100000) {
> ```

is there a constant somewhere you can use instead of this number?  Otherwise, consider a comment. You and I know where 100,000 comes from, other folks may not.


<!-- Sent from Reviewable.io -->

2021-07-30 16:42 UTC, dbolduc reviewed
The design has changed significantly in this latest commit. I have seen up to a 6x improvement in throughput relative to the previous design. The big differences are that:
1) There is now 1 mutation batcher used per thread.
2) Initial splits are provided to the table
3) The number of background threads used to run the batchers is now configurable. (now it can be > 1)
4) I no longer write to `atomic<int> fails`, `atomic<int> successes` on every response from the server. This was really dumb.

I think ~3x of the speedup is attributable to having multiple splits and batchers. This allows the server to process the requests efficiently because:
1) Each individual batch belongs to a single shard (if your thread count = shard count. otherwise there are edge cases, but they are inconsequential)
2) Batches can be send to different shards at the same time, allowing the backend to parallelize the work in each shard.

I think ~2x of the speedup came from correcting the poor use of atomics, based on some empirical data I collected.

#### Weird things still

* Our deadline timer is run using the batcher background threads. I think this is fine, because we don't care so much about results that timeout anyways. But maybe it should have it's own dedicated thread?
* `GrpcBackgroundThreadPoolSizeOption` is still set to the value of `--max-batches`. Even though there could be N batchers that each have their own max batches in flight limit.... I think this value is now wrong. But I do not know what it should be. I guess it could be yet another configuration parameter? 

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-:-Mfs2GBC6-wxug44gKxB:b89cj6t)* status: 4 of 10 files reviewed, 4 unresolved discussions (waiting on @coryan)

___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, line 135 at r5](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-Mfh1YJt7wCL_gAcRWJF:-Mfrswzp5GRO1ht_PjIY:b-rgkg66) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/77585fba61ad42030b01223b593036e6e52cd743/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc#L135)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I see your self-test creates a table.  Over time these can leak: this program may crash or timeout before having a chance to delete the table.  In other programs that create persistent resources as part of the integration test we try to name the resources something like `foo-YYYY-MM-DD-${random_stuff}` and then delete them if they are older than 2 days.
</blockquote></details>

Ah. This makes sense. Fixed.

I notice that our [other benchmarks](https://github.com/googleapis/google-cloud-cpp/blob/1295b30097a21451f4b7cf0582660989b91200d7/google/cloud/bigtable/benchmarks/setup.cc#L47-L51) do not exactly match [the pattern](https://github.com/googleapis/google-cloud-cpp/blob/1295b30097a21451f4b7cf0582660989b91200d7/google/cloud/bigtable/testing/random_names.cc#L25) we look for when we [clean up stale tables](https://github.com/googleapis/google-cloud-cpp/blob/1295b30097a21451f4b7cf0582660989b91200d7/google/cloud/bigtable/testing/cleanup_stale_resources.cc#L25-L44). (None of them use the prefix "tbl"). 

The exact prefix of the table was a [requirement](https://github.com/googleapis/google-cloud-cpp/issues/189) many years ago. We could make the regex more general.... but I think we should just update the other benchmarks to use the "tbl" prefix. They needed to be cleaned up, anyway.
___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, line 154 at r5](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-Mfh23zx4HxZ38LYj7nH:-MfryqYDD03UDkAH2_Ro:bt2vr1s) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/77585fba61ad42030b01223b593036e6e52cd743/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc#L154)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I was suggesting that the table name should always be printed, because the error won't tell you what failed, just the type of error.
</blockquote></details>

Fixed?
___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, line 186 at r5](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-Mfh4B_6CTOvKehxbBxA:-MfryvK4DAK3zoMBiiBw:b-jk23nl) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/77585fba61ad42030b01223b593036e6e52cd743/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc#L186)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

While you have N threads generating mutations, you only have 1 thread sending RPCs and handling responses to the RPCs. That may be less than ideal.

Consider:

```cc
std::vector<std::vector> background(options->background_threads);
std::generate_n(background.begin(), background.size(), [&cq] { return std::thread{[](CompletionQueue q) { q.Run(); }, cq}; });
```

</blockquote></details>

We discussed this offline. I have added the configuration option `--batcher-thread-count` to address this.
___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_options.cc, line 139 at r5](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-Mfh3Po415eOUNhDtq7r:-Mfrz9fh7CK3ohMsrfyT:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/77585fba61ad42030b01223b593036e6e52cd743/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_options.cc#L139)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

is there a constant somewhere you can use instead of this number?  Otherwise, consider a comment. You and I know where 100,000 comes from, other folks may not.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-30 20:14 UTC, coryan approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> I expect we will need to iterate on this over time, but looks good, thanks!

> Reviewed 5 of 6 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-:-Mft2QQN8ZypC7JLeBB_:b-j0qsqa)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dbolduc)

___
*[google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc, line 135 at r5](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7070#-Mfh1YJt7wCL_gAcRWJF:-Mft1t1u5lmJRmEFt2Bq:b-5xouc0) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/77585fba61ad42030b01223b593036e6e52cd743/google/cloud/bigtable/benchmarks/mutation_batcher_throughput_benchmark.cc#L135)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

Ah. This makes sense. Fixed.

I notice that our [other benchmarks](https://github.com/googleapis/google-cloud-cpp/blob/1295b30097a21451f4b7cf0582660989b91200d7/google/cloud/bigtable/benchmarks/setup.cc#L47-L51) do not exactly match [the pattern](https://github.com/googleapis/google-cloud-cpp/blob/1295b30097a21451f4b7cf0582660989b91200d7/google/cloud/bigtable/testing/random_names.cc#L25) we look for when we [clean up stale tables](https://github.com/googleapis/google-cloud-cpp/blob/1295b30097a21451f4b7cf0582660989b91200d7/google/cloud/bigtable/testing/cleanup_stale_resources.cc#L25-L44). (None of them use the prefix "tbl"). 

The exact prefix of the table was a [requirement](https://github.com/googleapis/google-cloud-cpp/issues/189) many years ago. We could make the regex more general.... but I think we should just update the other benchmarks to use the "tbl" prefix. They needed to be cleaned up, anyway.
</blockquote></details>

SGTM, please file a bug to fix the other benchmarks and tests.


<!-- Sent from Reviewable.io -->

2021-07-30 20:48 UTC, merged