feat(generator): selectively generate async methods for certain RPCs
googleapis/google-cloud-cpp pull request #7540
Opened 2021-10-31 07:03 UTC by dbolduc

Fixes #7531 

If it helps the reviewer, I grouped individual commits by `class`. (so most commits have a generator, a golden header/source, and a golden unit test).

I made no attempt to place the `AsyncFoo` methods next to their `Foo` counterparts.

2021-10-31 17:01 UTC, coryan requested changes
Some nits and a question below.

2021-10-31 17:01 UTC, coryan commented on generator/internal/stub_generator.cc
> +            // clang-format on
nit: move `clang-format on` to before the raw string.

2021-11-01 01:26 UTC, dbolduc reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7540)* status: 0 of 36 files reviewed, 4 unresolved discussions (waiting on @coryan)

___
*[generator/internal/codegen_utils.cc, line 91 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7540#-MnK9NE9O-3Q377R55DC-r2-91:-MnNtKdd8qpxnYgthbNC:b3zlulx) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b15a77592bc0c58f5a2a5bcff4f30e5b12d72cd5/generator/internal/codegen_utils.cc#L91)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: `in` is not super descriptive, maybe `desired_args` ? Or maybe `grouped_arg` for `in` and `group_name` for `out`?
</blockquote></details>

`single_arg` -> `grouped_arg` ?
___
*[generator/internal/codegen_utils_test.cc, line 264 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7540#-MnK9NE9O-3Q377R55DD-r2-264:-MnNnoxy6WqPbnPhyank:bxsvnzl) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b15a77592bc0c58f5a2a5bcff4f30e5b12d72cd5/generator/internal/codegen_utils_test.cc#L264)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Maybe a test with both `omit` and `async`?  Which got me thinking, what should be the semantics of `omit_rpc=Foo,gen_async_rpc=Foo` ?
</blockquote></details>

I did not consider what would happen if `Foo` was included in both. I think what gives us the most control is to generate the async call for `Foo` and omit the synchronous one. I don't know why we would only want to offer an async version of a call... but we could if we wanted to. (This happens to be what the code does now. I added a note in `generator_config.proto` to make this more clear).

Test added.
___
*[generator/internal/service_code_generator.cc, line 66 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7540#-MnK9NE9O-3Q377R55DI-r2-66:-MnO0IYv4zy_P-dWMZ-P:b6ca4hm) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b15a77592bc0c58f5a2a5bcff4f30e5b12d72cd5/generator/internal/service_code_generator.cc#L66)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: feels like this should be:

```cc
auto split_arg = [this](std::string const& arg) -> std::set<std::string> {
  auto l = service_vars_.find(arg);
  if (l == service_vars_.end()) return {};
  return absl::StrSplit(l->second, ',');
};
  auto const omitted_rpcs = split_arg("omitted_rpcs");
  auto const gen_async_rpcs = split_arg("gen_async_rpcs");
```

But it might need some tuning because I am not sure how `absl::StrSplit` works in this case.

</blockquote></details>

Yes, your suggestion is much cleaner.
___
*[generator/internal/service_code_generator.cc, line 101 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7540#-MnK9NE9O-3Q377R55DI-r2-101:-MnO0M1b2ZaLgjApoJkf:byg433c) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b15a77592bc0c58f5a2a5bcff4f30e5b12d72cd5/generator/internal/service_code_generator.cc#L101)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Hmmm... now it looks like that lambda should be a member function.
</blockquote></details>

Refactored.
___
*[generator/internal/stub_generator.cc, line 118 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7540#-MnK9NE9O-3Q377R55DK-r2-118:-MnNn15G7dfraMHcn6M7:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b15a77592bc0c58f5a2a5bcff4f30e5b12d72cd5/generator/internal/stub_generator.cc#L118)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: consider using a raw string (`R"""(`) here.
</blockquote></details>

Done.
___
*[generator/internal/stub_generator.cc, line 369 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7540#-MnK9NE9O-3Q377R55DK-r2-369:-MnNnfUJ1u3212Jc8HfV:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b15a77592bc0c58f5a2a5bcff4f30e5b12d72cd5/generator/internal/stub_generator.cc#L369)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: move `clang-format on` to before the raw string.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-01 01:41 UTC, coryan approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 28 of 36 files at r1, 2 of 2 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7540#-:-MnO97-k0vuBvP5w-y9J:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dbolduc)

___
*[generator/internal/codegen_utils.cc, line 91 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7540#-MnK9NE9O-3Q377R55DC-r2-91:-MnO8OozA-C2fJhq_NJv:b-80tlqk) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/b15a77592bc0c58f5a2a5bcff4f30e5b12d72cd5/generator/internal/codegen_utils.cc#L91)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

`single_arg` -> `grouped_arg` ?
</blockquote></details>

Sure.


<!-- Sent from Reviewable.io -->

2021-11-01 03:41 UTC, merged