feat(generator): support service-qualified names in RPC lists
googleapis/google-cloud-cpp pull request #7586
Opened 2021-11-12 20:44 UTC by devbww

Allow `<service>.<method>` names in the `omitted_rpcs` and
`gen_async_rpcs` lists (in addition to just `<method>`) for
cases where two services defined in the same file share an
RPC name, but we want to treat the RPCs differently.

This isn't anything we need now, but is something I considered
during the recent `omitted_services` change, and it seemed best
to provide the groundwork while I had it in mind.

2021-11-12 21:54 UTC, scotthart requested changes
To get some test coverage of this, perhaps go into generator/integration_tests/generator_integration_test.cc and service qualify either of "Omitted1" or "Omitted2" in the fixture SetUp.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7586#-:-MoL7s4QAs9m4ElVWXEs:b69wvb7)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @scotthart)



<!-- Sent from Reviewable.io -->

2021-11-12 23:31 UTC, devbww reviewed
Good idea.  Thanks!

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7586#-:-MoLUNm30Y0_r3nLGzI1:b9w69b3)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @scotthart)



<!-- Sent from Reviewable.io -->

2021-11-13 01:49 UTC, dbolduc approved these changes

2021-11-13 02:59 UTC, scotthart approved these changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7586)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @devbww)



<!-- Sent from Reviewable.io -->

2021-11-13 03:27 UTC, merged