impl: add RestRequest class
googleapis/google-cloud-cpp pull request #7832
Opened 2022-01-06 21:18 UTC by scotthart

2022-01-06 22:48 UTC, coryan requested changes
A bunch of nits and things for you to consider, but otherwise looks great.

2022-01-06 22:48 UTC, coryan commented on google/cloud/internal/rest_request.cc
> +// Copyright 2021 Google LLC
nit: it is now 2022.

2022-01-06 22:48 UTC, coryan commented on google/cloud/internal/rest_request.cc
> +//     http://www.apache.org/licenses/LICENSE-2.0
nit: we are now using `https://www...`

2022-01-06 22:48 UTC, coryan commented on google/cloud/internal/rest_request.h
> +// Copyright 2021 Google LLC
same nits in the boilerplate.

2022-01-06 22:48 UTC, coryan commented on google/cloud/internal/rest_request_test.cc
> +// Copyright 2021 Google LLC
ditto.

2022-01-06 22:48 UTC, coryan commented on google/cloud/internal/rest_request.h
> +class RestRequest {
Can we have some documentation, even for ourselves, saying that this class is for?  When would I use it?  What does it represent?

2022-01-06 22:48 UTC, coryan commented on google/cloud/internal/rest_request.h
> +  // Adding a duplicate param and or value results in both the new and original
nit: blank line before the next overload set?

2022-01-06 22:48 UTC, coryan commented on google/cloud/internal/rest_request.h
> +  std::string const& path() const;
Any reason not to inline these functions?  They seem pretty small.

2022-01-06 22:48 UTC, coryan commented on google/cloud/internal/rest_request.h
> +  RestRequest(std::string path, HttpHeaders headers);
Given the modifiers to add headers and parameters, do you need these constructors?  Do you think they will be commonly used?

2022-01-06 22:48 UTC, coryan commented on google/cloud/internal/rest_request.h
> +  RestRequest(RestRequest const&) = default;
Do you need to spell these out?  I would have hoped the compiler generated them for you?

2022-01-06 22:48 UTC, coryan commented on google/cloud/internal/rest_request.h
> +  RestRequest& AddQueryParameter(std::pair<std::string, std::string> parameter);
If you are planning to return `RestRequest&` you may want to consider `&&` overloads so `RestRequest().AddQueryParameter(...).AddHeader(...)` returns a rvalue reference.

2022-01-06 23:19 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7832)* status: 0 of 6 files reviewed, 10 unresolved discussions (waiting on @coryan and @scotthart)

___
*[google/cloud/internal/rest_request.cc, line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7832#-MslFUZPzGi4831VerpD-r1-1:-MslfpT2Cgeanf8RUvRz:b2cctl) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/6bea6b6b5ca3f911f22cadd907361e64af93808d/google/cloud/internal/rest_request.cc#L1)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: it is now 2022.
</blockquote></details>

So these files existed in a public branch on my fork back in 2021. I wasn't sure whether or not to bump them to 2022.


<!-- Sent from Reviewable.io -->

2022-01-06 23:44 UTC, coryan commented
___
*[google/cloud/internal/rest_request.cc, line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7832#-MslFUZPzGi4831VerpD-r1-1:-Msll5IsD_ojBuc_UvFt:b-5wqdgg) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/6bea6b6b5ca3f911f22cadd907361e64af93808d/google/cloud/internal/rest_request.cc#L1)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

So these files existed in a public branch on my fork back in 2021. I wasn't sure whether or not to bump them to 2022.
</blockquote></details>

I am not a lawyer, nor do I play one on TV.  My intuition is that we should label them based on the date the file gets merged into the repo, but that is just an intuition.  Your call.


<!-- Sent from Reviewable.io -->

2022-01-07 18:08 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7832)* status: 0 of 6 files reviewed, 7 unresolved discussions (waiting on @coryan)

___
*[google/cloud/internal/rest_request.h, line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7832#-MslFUZPzGi4831VerpE-r1-1:-MspiaHpAYUlqlCjDQpy:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/6bea6b6b5ca3f911f22cadd907361e64af93808d/google/cloud/internal/rest_request.h#L1)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

same nits in the boilerplate.
</blockquote></details>

Done.
___
*[google/cloud/internal/rest_request.h, line 30 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7832#-MslFUZPzGi4831VerpE-r1-30:-Mspi_iwBV6Xfb3S43Uh:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/6bea6b6b5ca3f911f22cadd907361e64af93808d/google/cloud/internal/rest_request.h#L30)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Can we have some documentation, even for ourselves, saying that this class is for?  When would I use it?  What does it represent?
</blockquote></details>

Done.
___
*[google/cloud/internal/rest_request.h, line 37 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7832#-MslFUZPzGi4831VerpE-r1-37:-Mspi_3K3EBF3b8eh48z:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/6bea6b6b5ca3f911f22cadd907361e64af93808d/google/cloud/internal/rest_request.h#L37)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Given the modifiers to add headers and parameters, do you need these constructors?  Do you think they will be commonly used?
</blockquote></details>

Done.
___
*[google/cloud/internal/rest_request.h, line 41 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7832#-MslFUZPzGi4831VerpE-r1-41:-MspiVk98VTDwYGvN_3M:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/6bea6b6b5ca3f911f22cadd907361e64af93808d/google/cloud/internal/rest_request.h#L41)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Do you need to spell these out?  I would have hoped the compiler generated them for you?
</blockquote></details>

Done.
___
*[google/cloud/internal/rest_request.h, line 46 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7832#-MslFUZPzGi4831VerpE-r1-46:-MspiVRTB3IOuRxPjlB1:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/6bea6b6b5ca3f911f22cadd907361e64af93808d/google/cloud/internal/rest_request.h#L46)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Any reason not to inline these functions?  They seem pretty small.
</blockquote></details>

Done.
___
*[google/cloud/internal/rest_request.h, line 58 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7832#-MslFUZPzGi4831VerpE-r1-58:-MspiUSw8x5E8dVvRr1R:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/6bea6b6b5ca3f911f22cadd907361e64af93808d/google/cloud/internal/rest_request.h#L58)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

If you are planning to return `RestRequest&` you may want to consider `&&` overloads so `RestRequest().AddQueryParameter(...).AddHeader(...)` returns a rvalue reference.
</blockquote></details>

Done.
___
*[google/cloud/internal/rest_request_test.cc, line 1 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7832#-MslFUZPzGi4831VerpF-r1-1:-MspiShu2Hp4w2oVspWD:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/6bea6b6b5ca3f911f22cadd907361e64af93808d/google/cloud/internal/rest_request_test.cc#L1)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-07 18:11 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7832)* status: 0 of 6 files reviewed, 7 unresolved discussions (waiting on @coryan)

___
*[google/cloud/internal/rest_request.h, line 37 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7832#-MslFUZPzGi4831VerpE-r1-37:-Mspj9H7DiO-_66bImy_:bf6g727) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/6bea6b6b5ca3f911f22cadd907361e64af93808d/google/cloud/internal/rest_request.h#L37)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Commonly? I'm not certain, but if you have a collection of these its easier to call one of these constructors rather than write some loop.


<!-- Sent from Reviewable.io -->

2022-01-07 18:15 UTC, coryan approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7832)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @coryan)



<!-- Sent from Reviewable.io -->

2022-01-07 20:28 UTC, merged