feat(retail): generate library
googleapis/google-cloud-cpp pull request #7972
Opened 2022-01-15 19:46 UTC by scotthart

2022-01-15 19:58 UTC, coryan requested changes
Unfortunately you will need to rebase and regenerate.  Even if the builds pass, the post-merge builds will probably break.

2022-01-15 19:58 UTC, coryan commented on google/cloud/retail/internal/catalog_stub_factory.h
> +#include "google/cloud/retail/catalog_connection.h"
I just merged a change that removes this `#include`.  You will need to rebase, run `ci/cloudbuild/build.sh -t generate-libraries-pr` and merge any changes.

2022-01-15 19:58 UTC, coryan commented on external/googleapis/CMakeLists.txt
> +    "google/api/httpbody.proto"
I would have separated this to a different PR, but no worries.

2022-01-19 16:40 UTC, scotthart reviewed
Rebased and regenerated

> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7972#-:-MtnCQSu5Zg-Gs7N6N65:b7epm5q)* status: 0 of 148 files reviewed, 1 unresolved discussion (waiting on @coryan and @scotthart)



<!-- Sent from Reviewable.io -->

2022-01-19 17:05 UTC, coryan requested changes
> Reviewed 123 of 148 files at r1, 25 of 25 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7972)* status: all files reviewed, 2 unresolved discussions (waiting on @scotthart)

___
*[external/googleapis/CMakeLists.txt, line 529 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7972#-MtnGY5rEM7cfqAXTTCu:-MtnGY5s92C80oTXfRL3:blkbekb) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/193fb8b48610b31ead4875dfa8eb07296ce89b16/external/googleapis/CMakeLists.txt#L529)):*
> ```CMake
>            " google_cloud_cpp_api_field_behavior_protos"
>            " google_cloud_cpp_api_http_protos"
>            " google_cloud_cpp_api_httpbody_protos"
> ```

This list is for backwards compatibility, we do not need to add new libraries to it.  Please remove.
___
*[google/cloud/retail/quickstart/README.md, line 160 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7972#-MtnHune2dRxs90dHtpV:-MtnHune2dRxs90dHtpW:b-6gip5v) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/193fb8b48610b31ead4875dfa8eb07296ce89b16/google/cloud/retail/quickstart/README.md#L160)):*
> ```Markdown
> 
> [bazel-install]: https://docs.bazel.build/versions/main/install.html
> [quickstart-link]: https://cloud.google.com/retail/docs/quickstart
> ```

This link is broken, maybe: https://cloud.google.com/retail/docs/setting-up ??



_Code quote:_
```Markdown
 https://cloud.google.com/retail/docs/quickstart
```


<!-- Sent from Reviewable.io -->

2022-01-19 17:52 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7972)* status: 146 of 148 files reviewed, 2 unresolved discussions (waiting on @coryan)

___
*[external/googleapis/CMakeLists.txt, line 529 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7972#-MtnGY5rEM7cfqAXTTCu:-MtnT1HO9FbM2cwHl3cz:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/193fb8b48610b31ead4875dfa8eb07296ce89b16/external/googleapis/CMakeLists.txt#L529)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This list is for backwards compatibility, we do not need to add new libraries to it.  Please remove.
</blockquote></details>

Done.
___
*[google/cloud/retail/quickstart/README.md, line 160 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7972#-MtnHune2dRxs90dHtpV:-MtnT1tzBbC4V--JQBiw:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/193fb8b48610b31ead4875dfa8eb07296ce89b16/google/cloud/retail/quickstart/README.md#L160)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This link is broken, maybe: https://cloud.google.com/retail/docs/setting-up ??
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-19 22:38 UTC, coryan approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7972#-:-MtoUVt07_ymkItZYScI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @scotthart)



<!-- Sent from Reviewable.io -->

2022-01-20 01:43 UTC, merged