feat(container): generate library
googleapis/google-cloud-cpp pull request #8109
Opened 2022-01-26 00:35 UTC by scotthart

2022-01-26 05:08 UTC, dbolduc requested changes
just some changes to the quickstart

2022-01-26 05:08 UTC, dbolduc commented on google/cloud/container/quickstart/quickstart.cc
> +      container::MakeClusterManagerConnection(/* EDIT HERE */));
delete `/* EDIT HERE */`

2022-01-26 05:08 UTC, dbolduc commented on google/cloud/container/quickstart/quickstart.cc
> +  auto const project = google::cloud::Project(argv[1]);
looks like we want `project + "/locations/-"`

https://github.com/googleapis/google-cloud-cpp/blob/8a68ee4c1d8d16d81496dd25fb2e47b20cbf6b72/google/cloud/container/cluster_manager_client.h#L93-L96

2022-01-26 05:08 UTC, dbolduc commented on google/cloud/container/quickstart/quickstart.cc
> +  }
if you want to save some lines:
```cc
if (!response) throw std::runtime_error(response.status().message());
for (auto c : response->clusters()) {
  std::cout << c.DebugString() << "\n";
}
```

2022-01-26 18:40 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8109)* status: 0 of 42 files reviewed, 3 unresolved discussions (waiting on @dbolduc)

___
*[google/cloud/container/quickstart/quickstart.cc, line 28 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8109#-MuInrRp0AXhDJEmVFjW-r2-28:-MuMfyaT0pMFibEujKhq:bwohspi) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8a68ee4c1d8d16d81496dd25fb2e47b20cbf6b72/google/cloud/container/quickstart/quickstart.cc#L28)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

delete `/* EDIT HERE */`
</blockquote></details>

Thanks. I thought I had fixed the quickstart before I set this PR aside, but apparently not.
___
*[google/cloud/container/quickstart/quickstart.cc, line 30 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8109#-MuInrRp0AXhDJEmVFjW-r2-30:-MuMg98H4AvIBmywb3h5:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8a68ee4c1d8d16d81496dd25fb2e47b20cbf6b72/google/cloud/container/quickstart/quickstart.cc#L30)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

looks like we want `project + "/locations/-"`

https://github.com/googleapis/google-cloud-cpp/blob/8a68ee4c1d8d16d81496dd25fb2e47b20cbf6b72/google/cloud/container/cluster_manager_client.h#L93-L96
</blockquote></details>

Done.
___
*[google/cloud/container/quickstart/quickstart.cc, line 38 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8109#-MuInrRp0AXhDJEmVFjW-r2-38:-MuMgA5q5FQO3INkB5Kl:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8a68ee4c1d8d16d81496dd25fb2e47b20cbf6b72/google/cloud/container/quickstart/quickstart.cc#L38)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

if you want to save some lines:
```cc
if (!response) throw std::runtime_error(response.status().message());
for (auto c : response->clusters()) {
  std::cout << c.DebugString() << "\n";
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-26 18:47 UTC, dbolduc approved these changes

2022-01-26 18:49 UTC, dbolduc commented on google/cloud/container/quickstart/quickstart.cc
> +  }
FYI: I do not see this change, but who cares.

2022-01-26 18:51 UTC, coryan commented
@scotthart I added a magic word so merging this PR will automatically close the corresponding bug.

2022-01-26 19:05 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8109)* status: 0 of 42 files reviewed, 3 unresolved discussions (waiting on @coryan and @dbolduc)

___
*[google/cloud/container/quickstart/quickstart.cc, line 38 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8109#-MuInrRp0AXhDJEmVFjW-r2-38:-MuMlm3WCUmNGlW1AmuM:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/8a68ee4c1d8d16d81496dd25fb2e47b20cbf6b72/google/cloud/container/quickstart/quickstart.cc#L38)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I do.  But if @scotthart would rather merge this and fix it in a follow up PR that is fine by me.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-29 15:11 UTC, coryan commented
@scotthart looks like you need to rebase this PR and fix the conflicts.

2022-01-29 23:33 UTC, coryan approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 34 of 42 files at r1, 1 of 1 files at r2, 2 of 2 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8109#-:-MucAzrp9Prfyw6fHyN_:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @dbolduc)



<!-- Sent from Reviewable.io -->

2022-01-29 23:34 UTC, coryan commented
/gcbrun

2022-01-31 17:43 UTC, coryan commented
@scotthart Looks like another round of rebase and regeneration is needed?

2022-01-31 19:22 UTC, merged