feat(bigtable): support x-goog-user-project
googleapis/google-cloud-cpp pull request #8324
Opened 2022-02-09 23:34 UTC by coryan

Part of the work for #8284

2022-02-09 23:45 UTC, dbolduc requested changes
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8324)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @coryan and @dbolduc)

___
*[google/cloud/bigtable/data_client.cc, line 116 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8324#-MvVrOep27B3nlJ_qt2e:-MvVrOep27B3nlJ_qt2f:bdu4uci) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/14848cc77efa49f43636c09c029dcc0f4a73e999/google/cloud/bigtable/data_client.cc#L116)):*
> ```cpp
>   ReadRows(grpc::ClientContext* context,
>            btproto::ReadRowsRequest const& request) override {
>     return impl_.Stub()->ReadRows(context, request);
> ```

I think we need one here.
___
*[google/cloud/bigtable/internal/defaults_test.cc, line 164 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8324#-MvVrYHYBp3kbceZUmII:-MvVrYHYBp3kbceZUmIJ:b-mv2oah) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/14848cc77efa49f43636c09c029dcc0f4a73e999/google/cloud/bigtable/internal/defaults_test.cc#L164)):*
> ```cpp
> 
>   env = ScopedEnvironment("GOOGLE_CLOUD_CPP_USER_PROJECT", "env-project");
>   options = Options{}.set<UserProjectOption>("env-project");
> ```

s/env-project/test-project/

to make sure the user supplied options gets overridden by the env var


<!-- Sent from Reviewable.io -->

2022-02-10 00:03 UTC, dbolduc approved these changes
Thanks for this

2022-02-10 00:03 UTC, dbolduc commented on google/cloud/bigtable/internal/defaults_test.cc
> +  auto options = DefaultInstanceAdminOptions(
I would be fine with there just being one test, which calls `DefaultOptions( ... )`, instead of a test for each service... but your call.

2022-02-10 00:45 UTC, dbolduc commented
Can you please undo the changes to `TableAdminClient`? None of those methods will exist in the next release

2022-02-10 00:46 UTC, coryan reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8324)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @coryan and @dbolduc)

___
*[google/cloud/bigtable/data_client.cc, line 116 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8324#-MvVrOep27B3nlJ_qt2e:-MvVvHp_7DVpSeexRi6M:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/14848cc77efa49f43636c09c029dcc0f4a73e999/google/cloud/bigtable/data_client.cc#L116)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

I think we need one here.
</blockquote></details>

Done.
___
*[google/cloud/bigtable/internal/defaults_test.cc, line 164 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8324#-MvVrYHYBp3kbceZUmII:-MvVvJh9Aqxfgwm0Gqem:b-f89diz) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/14848cc77efa49f43636c09c029dcc0f4a73e999/google/cloud/bigtable/internal/defaults_test.cc#L164)):*
<details><summary><i>Previously, dbolduc (Darren Bolduc) wrote…</i></summary><blockquote>

s/env-project/test-project/

to make sure the user supplied options gets overridden by the env var
</blockquote></details>

Fixed. Also fixed the test to be useful. And also added tests for admin and instance admin.


<!-- Sent from Reviewable.io -->

2022-02-10 00:48 UTC, coryan commented
> Can you please undo the changes to `TableAdminClient`? None of those methods will exist in the next release

But they exist now?  People can pull code from `main`.  And you may win the lottery and not complete the work.

2022-02-10 01:26 UTC, dbolduc commented
> > Can you please undo the changes to `TableAdminClient`? None of those methods will exist in the next release
> 
> But they exist now? People can pull code from `main`. And you may win the lottery and not complete the work.

Ok fine. When the time comes, I will delete this with pleasure.

2022-02-10 12:14 UTC, merged