feat(cloudprofiler): generate library
googleapis/google-cloud-cpp pull request #8425
Opened 2022-02-20 02:15 UTC by dbolduc

Fixes #8179 

The quickstart runs, but it doesn't actually do anything.

2022-02-20 19:01 UTC, coryan requested changes
For other services with "cloud" in the name we decided that `google/cloud/profiler` was cloudy enough.  Please rename the library to avoid excessive cloudiness.

2022-02-21 17:45 UTC, dbolduc commented on google/cloud/cloudprofiler/README.md
> +Profiler does not yet offer profiling of C++ libraries. The
Done.

2022-02-21 17:45 UTC, dbolduc commented on google/cloud/cloudprofiler/doc/main.dox
> +Profiler does not yet offer profiling of C++ libraries. The
Done.

2022-02-21 17:45 UTC, dbolduc commented
> For other services with "cloud" in the name we decided that `google/cloud/profiler` was cloudy enough. Please rename the library to avoid excessive cloudiness.

Done.

2022-02-21 21:18 UTC, coryan approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 43 of 43 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8425#-:-MwT8UKaABOqSbsgduH3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dbolduc)



<!-- Sent from Reviewable.io -->

2022-02-21 22:13 UTC, merged