feat(pubsublite): multipartition publisher
googleapis/google-cloud-cpp pull request #8528
Opened 2022-03-10 07:45 UTC by 18suresha

This PR implements a multipartition publisher

2022-03-31 21:10 UTC, dpcollins-google requested changes
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: 0 of 27 files reviewed, 7 unresolved discussions (waiting on @18suresha and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 39 at r8](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzWld0a0WCe7JeEPaav:-MzWld0a0WCe7JeEPaaw:b-48a6kb) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/79a64a3af4682adb2c05c63b73bf826e4db4ef5e/google/cloud/pubsublite/internal/multipartition_publisher.cc#L39)):*
> ```cpp
>       topic_{std::move(topic)},
>       cancel_token_{alarm_registry.RegisterAlarm(
>           std::chrono::milliseconds{60 * 1000},
> ```

std::chrono::seconds{60} should upconvert



_Code quote:_
```cpp
std::chrono::milliseconds
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 46 at r8](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzWmYaI-aQVAw37DjWC:-MzWmYaI-aQVAw37DjWD:b1seqnu) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/79a64a3af4682adb2c05c63b73bf826e4db4ef5e/google/cloud/pubsublite/internal/multipartition_publisher.cc#L46)):*
> ```cpp
>   if (!shutdown.is_ready()) {
>     GCP_LOG(WARNING) << "`Shutdown` must be called and finished before object "
>                         "goes out of scope.";
> ```

Shutdown() doesn't have any logic apart from calling Shutdown() on the composite, so I think you don't need a body for the destructor.



_Code quote:_
```cpp
  future<void> shutdown = Shutdown();
  if (!shutdown.is_ready()) {
    GCP_LOG(WARNING) << "`Shutdown` must be called and finished before object "
                        "goes out of scope.";
    assert(false);
  }
  shutdown.get();
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 66 at r8](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzWmtOd3waO53HMFaqL:-MzWmtOd3waO53HMFaqM:b-xxcne4) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/79a64a3af4682adb2c05c63b73bf826e4db4ef5e/google/cloud/pubsublite/internal/multipartition_publisher.cc#L66)):*
> ```cpp
>     auto num_partitions = f.get();
>     if (!num_partitions.ok()) {
>       GCP_LOG(INFO) << "Reading number of partitions for " << topic_.FullName()
> ```

Should probably be WARNING



_Code quote:_
```cpp
INFO
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 74 at r8](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzWnC9GCwHDJqYVd_RV:-MzWnC9GCwHDJqYVd_RW:b-2yojdr) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/79a64a3af4682adb2c05c63b73bf826e4db4ef5e/google/cloud/pubsublite/internal/multipartition_publisher.cc#L74)):*
> ```cpp
>       partition_publishers_.push_back(
>           publisher_factory_(partition_publishers_.size()));
>       service_composite_.AddServiceObject(partition_publishers_.back().get());
> ```

nit, probably won't be an issue, but you should avoid calling AddServiceObject under lock. Instead, push the pointers to a vector, and add outside of the lock.



_Code quote:_
```cpp
service_composite_.AddServiceObject(partition_publishers_.back().get());
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 94 at r8](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzWn_4d6sDN3n_s-EK3:-MzWn_4d6sDN3n_s-EK4:b5e1rqp) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/79a64a3af4682adb2c05c63b73bf826e4db4ef5e/google/cloud/pubsublite/internal/multipartition_publisher.cc#L94)):*
> ```cpp
>                                                 partition_publishers_.size()));
>   // TODO(18suresha) handle invalid partition?
>   return partition_publishers_[partition]->Publish(m).then(
> ```

just make this .get(partition) instead of [partition], then it's a hard error if the routing policy is implemented incorrectly



_Code quote:_
```cpp
[partition]
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 95 at r8](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzWnnqlBtzVIKYrd7Vm:-MzWnnqlBtzVIKYrd7Vn:b-imvzbl) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/79a64a3af4682adb2c05c63b73bf826e4db4ef5e/google/cloud/pubsublite/internal/multipartition_publisher.cc#L95)):*
> ```cpp
>   // TODO(18suresha) handle invalid partition?
>   return partition_publishers_[partition]->Publish(m).then(
>       [=](future<StatusOr<Cursor>> publish_future) {
> ```

you only bind partition, with one bind probably best to make this clear


<!-- Sent from Reviewable.io -->

2022-04-01 03:30 UTC, 18suresha reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: 0 of 27 files reviewed, 7 unresolved discussions (waiting on @18suresha and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 46 at r8](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzWmYaI-aQVAw37DjWC:-MzYA3BUAd_x_xs4S4TE:bjqqene) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/79a64a3af4682adb2c05c63b73bf826e4db4ef5e/google/cloud/pubsublite/internal/multipartition_publisher.cc#L46)):*
<details><summary><i>Previously, dpcollins-google wrote…</i></summary><blockquote>

Shutdown() doesn't have any logic apart from calling Shutdown() on the composite, so I think you don't need a body for the destructor.
</blockquote></details>

I ended up adding more logic to the destructor because of `cancel_token_`


<!-- Sent from Reviewable.io -->

2022-04-01 05:50 UTC, 18suresha reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: 0 of 27 files reviewed, 7 unresolved discussions (waiting on @18suresha and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 46 at r8](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzWmYaI-aQVAw37DjWC:-MzYf58z5T5mldN7iMoy:b-k7c9lw) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/79a64a3af4682adb2c05c63b73bf826e4db4ef5e/google/cloud/pubsublite/internal/multipartition_publisher.cc#L46)):*
<details><summary><i>Previously, 18suresha (Adarsh Suresh) wrote…</i></summary><blockquote>

I ended up adding more logic to the destructor because of `cancel_token_`
</blockquote></details>

nvm that logic was unnecessary 


<!-- Sent from Reviewable.io -->

2022-04-01 13:59 UTC, dpcollins-google requested changes
> Reviewed 2 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: 2 of 27 files reviewed, 14 unresolved discussions (waiting on @18suresha and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher.h, line 39 at r12](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mz_OUl77bBYUegwwUKH:-Mz_OUl77bBYUegwwUKI:blxu53g) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1a261329636c1bede12cd8409cd9bad629b7ec2e/google/cloud/pubsublite/internal/multipartition_publisher.h#L39)):*
> ```objc
>     : public Publisher<google::cloud::pubsublite::MessageMetadata> {
>  public:
>   MultipartitionPublisher(
> ```

don't elide parameter names in headers



_Code quote:_
```objc
 MultipartitionPublisher(
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.h, line 40 at r12](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mz_ONrb2sCyikU67wpB:-Mz_ONrb2sCyikU67wpC:b-eb0qej) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1a261329636c1bede12cd8409cd9bad629b7ec2e/google/cloud/pubsublite/internal/multipartition_publisher.h#L40)):*
> ```objc
>  public:
>   MultipartitionPublisher(
>       std::function<std::unique_ptr<PartitionPublisher>(std::int64_t)>,
> ```

give this a name with a type alias in the private section.



_Code quote:_
```objc
std::function<std::unique_ptr<PartitionPublisher>(std::int64_t)>
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.h, line 45 at r12](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mz_O48cCYpyY6xpODAb:-Mz_O48cCYpyY6xpODAc:b-35dk9h) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1a261329636c1bede12cd8409cd9bad629b7ec2e/google/cloud/pubsublite/internal/multipartition_publisher.h#L45)):*
> ```objc
>       google::cloud::pubsublite::Topic);
> 
>   ~MultipartitionPublisher() override = default;
> ```

not needed, remove this line of code



_Code quote:_
```objc
~MultipartitionPublisher() override = default;
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.h, line 71 at r12](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mz_OdBe9sBRWSMWhezH:-Mz_OdBe9sBRWSMWhezI:bjv9vk1) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1a261329636c1bede12cd8409cd9bad629b7ec2e/google/cloud/pubsublite/internal/multipartition_publisher.h#L71)):*
> ```objc
>       partition_publishers_;  // ABSL_GUARDED_BY(mu_)
>   std::shared_ptr<google::cloud::pubsublite::AdminServiceConnection>
>       admin_connection_;  // ABSL_GUARDED_BY(mu_)
> ```

why does this need to be guarded? You never change this and its thread safe. Should be const (the pointer that is)



_Code quote:_
```objc
  std::shared_ptr<google::cloud::pubsublite::AdminServiceConnection>
      admin_connection_;  // ABSL_GUARDED_BY(mu_)
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.h, line 73 at r12](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mz_OjwO2mnqN8uBY7-i:-Mz_OjwO2mnqN8uBY7-j:bfev39b) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1a261329636c1bede12cd8409cd9bad629b7ec2e/google/cloud/pubsublite/internal/multipartition_publisher.h#L73)):*
> ```objc
>       admin_connection_;  // ABSL_GUARDED_BY(mu_)
>   ServiceComposite service_composite_;
>   std::unique_ptr<RoutingPolicy> routing_policy_;  // ABSL_GUARDED_BY(mu_)
> ```

pointer should be const, doesn't need to be guarded



_Code quote:_
```objc
td::unique_ptr<RoutingPolicy>
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 107 at r12](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mz_Ox1XE3KLhbAZ_SFM:-Mz_Ox1XE3KLhbAZ_SFN:bomw12e) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1a261329636c1bede12cd8409cd9bad629b7ec2e/google/cloud/pubsublite/internal/multipartition_publisher.cc#L107)):*
> ```cpp
>     PubSubMessage m) {
>   std::lock_guard<std::mutex> g{mu_};
>   if (partition_publishers_.empty()) {
> ```

interesting. everywhere else in the library we say that the only errors are permanent ones, but here we bail out to a condition the user can't wait on.

I think we should instead buffer messages, in order, with their futures until we get the first set of partitions. Not sure what the best way to structure that is though?



_Code quote:_
```cpp
  if (partition_publishers_.empty()) {
    return make_ready_future(StatusOr<MessageMetadata>{
        Status{StatusCode::kFailedPrecondition,
               "Publishers haven't been created yet."}});
  }
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 116 at r12](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mz_PWtA2cZbfBjnabd2:-Mz_PWtA2cZbfBjnabd3:b69mhsk) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1a261329636c1bede12cd8409cd9bad629b7ec2e/google/cloud/pubsublite/internal/multipartition_publisher.cc#L116)):*
> ```cpp
>           ? routing_policy_->Route(
>                 static_cast<std::uint32_t>(partition_publishers_.size()))
>           : routing_policy_->Route(m.key(), static_cast<std::uint32_t>(
> ```

can you perform the routing and the downcall without holding the lock? This is a single fan-in point, so it would be good to avoid locking for longer than necessary. Something like the following:

```
std::int32_t partition_count;
{
  std::lock_guard<std::mutex> g{mu_};
  partition_count = publishers_.size();
  ... handle it being 0 ...
}
std::int32_t partition = <route logic>
Publisher<Cursor>* publisher;
{
  std::lock_guard<std::mutex> g{mu_};
  publisher = publishers_.at(partition).get();
}
... publish ...
```



_Code quote:_
```cpp
  std::int64_t partition =
      m.key().empty()
          ? routing_policy_->Route(
                static_cast<std::uint32_t>(partition_publishers_.size()))
          : routing_policy_->Route(m.key(), static_cast<std::uint32_t>(
                                                partition_publishers_.size()));
```


<!-- Sent from Reviewable.io -->

2022-04-01 15:57 UTC, dpcollins-google requested changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: 2 of 27 files reviewed, 8 unresolved discussions (waiting on @18suresha and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher.h, line 39 at r15](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mz_pp8oD7uwnEQKysP2:-Mz_pp8oD7uwnEQKysP3:b-54b44b) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/fd325dd614dc0e46f3759c84cb8a1cafe4a1acf3/google/cloud/pubsublite/internal/multipartition_publisher.h#L39)):*
> ```objc
>     : public Publisher<google::cloud::pubsublite::MessageMetadata> {
>  private:
>   using Partition = std::int64_t;
> ```

can you put this alias in an internal file somewhere, and be consistent with it? i.e., lets always use std::uint32_t when we need a Partition.



_Code quote:_
```objc
std::int64_t;
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.h, line 91 at r15](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mz_p7NN74urBr0_JcSO:-Mz_p7NN74urBr0_JcSP:bu36one) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/fd325dd614dc0e46f3759c84cb8a1cafe4a1acf3/google/cloud/pubsublite/internal/multipartition_publisher.h#L91)):*
> ```objc
>   google::cloud::pubsublite::v1::GetTopicPartitionsRequest
>       topic_partitions_request_;
>   std::vector<PublishState> initial_publish_buffer_;  // ABSL_GUARDED_BY(mu_)
> ```

nit. move up to below updating_partitions



_Code quote:_
```objc
std::vector<PublishState> initial_publish_buffer_;  // ABSL_GUARDED_BY(mu_)
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 38 at r8](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzWmEFh7QvPOSoXKiXW:-Mz_pQ6b59rQs7oEOWqW:b-fouy6e) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/79a64a3af4682adb2c05c63b73bf826e4db4ef5e/google/cloud/pubsublite/internal/multipartition_publisher.cc#L38)):*
<details><summary><i>Previously, dpcollins-google wrote…</i></summary><blockquote>

Hmm I think you need to fence this to not do anything until Start() is called.
</blockquote></details>

Please fix, check that the state of the composite is OK before continuing in this callback. Also, don't use std::bind, just use a lambda.
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 68 at r15](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mz_pdqE5dTmKbPyJzHs:-Mz_pdqE5dTmKbPyJzHt:bchnrsm) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/fd325dd614dc0e46f3759c84cb8a1cafe4a1acf3/google/cloud/pubsublite/internal/multipartition_publisher.cc#L68)):*
> ```cpp
> }
> 
> void MultipartitionPublisher::CreatePublishers() {
> ```

nit. TriggerPublisherCreation?


<!-- Sent from Reviewable.io -->

2022-04-01 19:36 UTC, dpcollins-google requested changes
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: 2 of 27 files reviewed, 10 unresolved discussions (waiting on @18suresha and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher.h, line 63 at r17](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mza_e4h7aN3n-FRK0dD:-Mza_e4h7aN3n-FRK0dE:b6bz35r) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/12d4d465a58659fab527bbc2e07b4cfa0053f265/google/cloud/pubsublite/internal/multipartition_publisher.h#L63)):*
> ```objc
>  private:
>   struct PublishState {
>     std::uint32_t num_partitions;
> ```

please remove, change RouteAndPublish to 



_Code quote:_
```objc
std::uint32_t num_partitions;
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.h, line 65 at r17](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mzac-8k7by8RTuoOWCm:-Mzac-8k7by8RTuoOWCn:b126k7d) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/12d4d465a58659fab527bbc2e07b4cfa0053f265/google/cloud/pubsublite/internal/multipartition_publisher.h#L65)):*
> ```objc
>     std::uint32_t num_partitions;
>     google::cloud::pubsublite::v1::PubSubMessage message;
>     std::shared_ptr<
> ```

you should initialize this in the struct. `publish_promise = std::make_shared<promise<StatusOr<google::cloud::pubsublite::MessageMetadata>>>()`

Specifically, Publish never initializes this.



_Code quote:_
```objc
    std::shared_ptr<
        promise<StatusOr<google::cloud::pubsublite::MessageMetadata>>>
        publish_promise;
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.h, line 83 at r17](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzaT60G-fe6HrDpmTm6:-MzaT60G-fe6HrDpmTm7:bg5pmke) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/12d4d465a58659fab527bbc2e07b4cfa0053f265/google/cloud/pubsublite/internal/multipartition_publisher.h#L83)):*
> ```objc
>       partition_publishers_;                          // ABSL_GUARDED_BY(mu_)
>   bool updating_partitions_ = false;                  // ABSL_GUARDED_BY(mu_)
>   std::vector<PublishState> initial_publish_buffer_;  // ABSL_GUARDED_BY(mu_)
> ```

add a comment on what this is and why its needed?



_Code quote:_
```objc
 std::vector<PublishState> initial_publish_buffer_;  // ABSL_GUARDED_BY(mu_)
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.h, line 90 at r17](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzaTSAW8mLqGq6VTj5f:-MzaTSAW8mLqGq6VTj5g:bbenzgo) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/12d4d465a58659fab527bbc2e07b4cfa0053f265/google/cloud/pubsublite/internal/multipartition_publisher.h#L90)):*
> ```objc
>   std::unique_ptr<RoutingPolicy> const routing_policy_;
>   google::cloud::pubsublite::Topic const topic_;
>   google::cloud::pubsublite::v1::GetTopicPartitionsRequest
> ```

nit. use an immediately executing inline lambda and make this const. In the constructor:
```
topic_partitions_request_{[&]{
    google::cloud::pubsublite::v1::GetTopicPartitionsRequest request;
    *request.mutable_topic() = topic_;
    return request;
}()}
```



_Code quote:_
```objc
  google::cloud::pubsublite::v1::GetTopicPartitionsRequest
      topic_partitions_request_;
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 47 at r17](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzaTs2Y4vkz3QZNcTn-:-MzaTs2Y4vkz3QZNcTn0:bqon9sc) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/12d4d465a58659fab527bbc2e07b4cfa0053f265/google/cloud/pubsublite/internal/multipartition_publisher.cc#L47)):*
> ```cpp
>   cancel_token_ =
>       alarm_registry_->RegisterAlarm(std::chrono::seconds{60}, [this]() {
>         if (!service_composite_.status().ok()) return;
> ```

Can you move the alarm creation back to the constructor now that you have this and get rid of the alarm_registry_ member variable?



_Code quote:_
```cpp
if (!service_composite_.status().ok()) return;
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 56 at r17](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzaULmHE6FE4DBSv3KA:-MzaULmIDySCD5q0B-Qa:blv8k3q) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/12d4d465a58659fab527bbc2e07b4cfa0053f265/google/cloud/pubsublite/internal/multipartition_publisher.cc#L56)):*
> ```cpp
> 
> future<StatusOr<std::uint32_t>> MultipartitionPublisher::GetNumPartitions() {
>   future<StatusOr<TopicPartitions>> topic_partitions_request;
> ```

no need to do this in 2 parts. just do:

`return admin_connection_->AsyncGetTopicPartitions(topic_partitions_request_).then(...);`



_Code quote:_
```cpp
  future<StatusOr<TopicPartitions>> topic_partitions_request;
  topic_partitions_request =
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 59 at r17](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzaUfdh4uJ9fU_IsxI6:-MzaUfdh4uJ9fU_IsxI7:b-59lxho) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/12d4d465a58659fab527bbc2e07b4cfa0053f265/google/cloud/pubsublite/internal/multipartition_publisher.cc#L59)):*
> ```cpp
>   topic_partitions_request =
>       admin_connection_->AsyncGetTopicPartitions(topic_partitions_request_);
>   return topic_partitions_request.then([](future<StatusOr<TopicPartitions>> f) {
> ```

add a trailing return type then you can get rid of the wrapping StatusOr<std::uint32_t> everywhere

`[](future<StatusOr<TopicPartitions>> f) -> StatusOr<Partition> {`
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 92 at r17](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzaZfXH7okc0xvd5jPr:-MzaZfXH7okc0xvd5jPs:b-c5yege) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/12d4d465a58659fab527bbc2e07b4cfa0053f265/google/cloud/pubsublite/internal/multipartition_publisher.cc#L92)):*
> ```cpp
>     std::vector<std::unique_ptr<PartitionPublisher>> new_partition_publishers;
>     bool was_empty = partition_publishers_.empty();
>     for (std::uint64_t i = partition_publishers_.size(); i < *num_partitions;
> ```

you can't access this outside of the lock. You need to cache the size.

```
Partition current_partitions;
{
      std::lock_guard<std::mutex> g{mu_};
      current_partitions = partition_publishers_.size();
      if (updating_partitions_ || current_partitions == *num_partitions) {
        return;
      }
      updating_partitions_ = true;
    }
```



_Code quote:_
```cpp
partition_publishers_
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 106 at r17](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzaagNaCoPkuXFMphgx:-MzaagNaCoPkuXFMphgy:bm1zmv7) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/12d4d465a58659fab527bbc2e07b4cfa0053f265/google/cloud/pubsublite/internal/multipartition_publisher.cc#L106)):*
> ```cpp
>       }
>       updating_partitions_ = false;
>       if (was_empty) {
> ```

I wouldn't bother with the was_empty check, it will just be a simple loop. slight restructuring nit:

```
    std::vector<PublishState> initial_publish_buffer;
    {
      std::lock_guard<std::mutex> g{mu_};
      for (auto& partition_publisher : new_partition_publishers) {
        partition_publishers_.push_back(std::move(partition_publisher));
      }
      updating_partitions_ = false;
      initial_publish_buffer.swap(initial_publish_buffer_);
    }
    for (auto& state : initial_publish_buffer) {
      state.num_partitions = *num_partitions;
      RouteAndPublish(state);
    }
```



_Code quote:_
```cpp
was_empty
```


<!-- Sent from Reviewable.io -->

2022-04-04 18:27 UTC, dpcollins-google requested changes
> Reviewed 1 of 8 files at r21, 2 of 10 files at r22.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: 4 of 32 files reviewed, 19 unresolved discussions (waiting on @18suresha and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher.h, line 64 at r27](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mzpk0C52HopRdC_cBDF:-Mzpk0C52HopRdC_cBDG:b-8lqavb) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/452480bdc7829a3c23a2df5084626fd530eb6aa7/google/cloud/pubsublite/internal/multipartition_publisher.h#L64)):*
> ```objc
>     Partition num_partitions;
>     google::cloud::pubsublite::v1::PubSubMessage message;
>     std::shared_ptr<
> ```

Can we 1) restructure this to be just:

promise<StatusOr<google::cloud::pubsublite::MessageMetadata>>> publish_promise;

2) Change RouteAndPublish to accept one of these by value and std::move it in
3) Change the last few lines of Publish from

```
  RouteAndPublish(state);
  return state.publish_promise->get_future();
```

to

```
auto to_return = state.publish_promise.get_future();
RouteAndPublish(std::move(state));
return to_return;
```

4) change RouteAndPublish to move the promise to a shared_ptr like:

```
auto shared_promise = std::make_shared<promise<StatusOr<google::cloud::pubsublite::MessageMetadata>>>>(std::move(state.publish_promise));
```



_Code quote:_
```objc
    std::shared_ptr<
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 50 at r27](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzpoTIbDDaYX9TY8SZl:-MzpoTIbDDaYX9TY8SZm:b-34ozas) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/452480bdc7829a3c23a2df5084626fd530eb6aa7/google/cloud/pubsublite/internal/multipartition_publisher.cc#L50)):*
> ```cpp
>           })} {}
> 
> future<Status> MultipartitionPublisher::Start() {
> ```

I think you need to add back the explicit destructor that calls our shutdown method, since you need to clean up the messages in the buffer



_Code quote:_
```cpp
future<Status> MultipartitionPublisher::Start() {
  TriggerPublisherCreation();
  return service_composite_.Start();
}
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 60 at r27](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mzpj5fe9dK78lMU9o2u:-Mzpj5fe9dK78lMU9o2v:b6xkjtr) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/452480bdc7829a3c23a2df5084626fd530eb6aa7/google/cloud/pubsublite/internal/multipartition_publisher.cc#L60)):*
> ```cpp
>         auto partitions = f.get();
>         if (!partitions) return partitions.status();
>         if (partitions->partition_count() >= UINT32_MAX) {
> ```

nit. this might read better as std::numeric_limits<Partition>::max()



_Code quote:_
```cpp
UINT32_MAX
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 64 at r27](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzpjOWE5X1FuJJKkBy6:-MzpjOWE5X1FuJJKkBy7:bllbuwl) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/452480bdc7829a3c23a2df5084626fd530eb6aa7/google/cloud/pubsublite/internal/multipartition_publisher.cc#L64)):*
> ```cpp
>               StatusCode::kFailedPrecondition,
>               absl::StrCat("Returned partition count is too big: ",
>                            std::to_string(partitions->partition_count()))};
> ```

not needed, StrCat handles numbers



_Code quote:_
```cpp
std::to_string(
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 83 at r27](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzpjXjZ6qeCdRWdEvEL:-MzpjXjZ6qeCdRWdEvEM:b-rombhr) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/452480bdc7829a3c23a2df5084626fd530eb6aa7/google/cloud/pubsublite/internal/multipartition_publisher.cc#L83)):*
> ```cpp
>       std::lock_guard<std::mutex> g{mu_};
>       if (updating_partitions_ ||
>           partition_publishers_.size() == *num_partitions) {
> ```

nit just calculate this once. Move current_num_partitions above this.



_Code quote:_
```cpp
partition_publishers_.size()
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 83 at r27](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzpmuUg34DsF3LPWB3B:-MzpmuUg34DsF3LPWB3C:b-enl0y1) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/452480bdc7829a3c23a2df5084626fd530eb6aa7/google/cloud/pubsublite/internal/multipartition_publisher.cc#L83)):*
> ```cpp
>       std::lock_guard<std::mutex> g{mu_};
>       if (updating_partitions_ ||
>           partition_publishers_.size() == *num_partitions) {
> ```

should be >= to handle races. For example, consider the following case:

1) Call Start, make GetNumPartitions call, slow
2) Change partition count from 2 to 4
3) Alarm calls GetNumPartitions, fast, returns 4, initializes
4) Start call returns with 2, <bad things>



_Code quote:_
```cpp
partition_publishers_.size() ==
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 141 at r27](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mzpp7WJBhjGKOZGkSwc:-Mzpp7WJBhjGKOZGkSwd:by1dyag) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/452480bdc7829a3c23a2df5084626fd530eb6aa7/google/cloud/pubsublite/internal/multipartition_publisher.cc#L141)):*
> ```cpp
>   state.message = std::move(m);
>   {
>     std::lock_guard<std::mutex> g{mu_};
> ```

You need to handle the case where we've failed. Currently, if we fail before initialization, you just put the message into the buffer and the future will never be completed. Please also add a test for this case.



_Code quote:_
```cpp
std::lock_guard<std::mutex> g{mu_};
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 162 at r27](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzpojFwCJJTRNKIyzTm:-MzpojFwCJJTRNKIyzTn:bt3zplo) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/452480bdc7829a3c23a2df5084626fd530eb6aa7/google/cloud/pubsublite/internal/multipartition_publisher.cc#L162)):*
> ```cpp
> }
> 
> future<void> MultipartitionPublisher::Shutdown() {
> ```

After cancel_token_ = nullptr, also needs to finish any outstanding publish futures with "shutting down" errors



_Code quote:_
```cpp
future<void> MultipartitionPublisher::Shutdown() {
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 54 at r27](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzpoLu16Hcyt5cnyLqT:-MzpoLu16Hcyt5cnyLqU:b-k8vd3x) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/452480bdc7829a3c23a2df5084626fd530eb6aa7/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L54)):*
> ```cpp
> auto const kAlarmDuration = std::chrono::milliseconds{std::chrono::seconds{60}};
> 
> class SinglePublisherTest : public ::testing::Test {
> ```

wrong name
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 89 at r27](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzplP7B5mOjfWZ3AWiA:-MzplP7B5mOjfWZ3AWiB:bcnewo4) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/452480bdc7829a3c23a2df5084626fd530eb6aa7/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L89)):*
> ```cpp
>   StrictMock<MockFunction<std::unique_ptr<Publisher<Cursor>>(Partition)>>
>       partition_publisher_factory_;
>   StrictMock<MockPartitionPublisher>& partition_publisher_ref_;
> ```

I think you need, at a minimum, 2 of these to test the routing behavior. partition_publisher_0_, partition_publisher_1_



_Code quote:_
```cpp
StrictMock<MockPartitionPublisher>& partition_publisher_ref_;
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 92 at r27](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzpldmX2Ksqc1qPU782:-MzpldmX2Ksqc1qPU783:b-oi0q4k) ([raw file](https://github.com/googlea [...]

2022-04-05 03:18 UTC, dpcollins-google requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: 4 of 32 files reviewed, 19 unresolved discussions (waiting on @18suresha and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher.h, line 25 at r34](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mzrasyo1NCIP0qNgz9w:-Mzrasyo1NCIP0qNgz9x:buzc58k) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/275fce6d7f01ab2fd1af4457ca2f5481c8fe1c2e/google/cloud/pubsublite/internal/multipartition_publisher.h#L25)):*
> ```objc
> #include "google/cloud/pubsublite/message_metadata.h"
> #include "google/cloud/pubsublite/topic.h"
> #include "absl/functional/function_ref.h"
> ```

unused?



_Code quote:_
```objc
#include "absl/functional/function_ref.h"
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 52 at r27](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzpISZCOR5EkGv0Ndo9-r27-52:-MzrbQnhAE-b5TWGSE4k:b-9suy7p) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/452480bdc7829a3c23a2df5084626fd530eb6aa7/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L52)):*
<details><summary><i>Previously, dpcollins-google wrote…</i></summary><blockquote>

nit. constants should be `constexpr [type] [name]{[init]};` if possible
</blockquote></details>

`constexpr std::chrono::milliseconds kAlarmDuration{std::chrono::seconds{60}};`
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 56 at r34](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzrbhtI-h4u7t8asBRk:-MzrbhtI-h4u7t8asBRl:bnf4gns) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/275fce6d7f01ab2fd1af4457ca2f5481c8fe1c2e/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L56)):*
> ```cpp
>     std::chrono::milliseconds{std::chrono::seconds{60}};
> 
> Topic ExampleTopic(std::string const& project, std::string const& location,
> ```

just hardcode these. This function doesn't need any arguments



_Code quote:_
```cpp
Topic ExampleTopic(std::string const& project, std::string const& location,
                   std::string const& name) {
  return Topic{project, location, name};
}
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 61 at r34](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzrbmCC0NbB_vcbxjK_:-MzrbmCC0NbB_vcbxjKa:bgad094) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/275fce6d7f01ab2fd1af4457ca2f5481c8fe1c2e/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L61)):*
> ```cpp
> }
> 
> GetTopicPartitionsRequest ExamplePartitionsRequest(Topic const& topic) {
> ```

ditto, hardcode that this is the result of GetExampleTopic



_Code quote:_
```cpp
Topic const& topic
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 168 at r34](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzrdRn9Ez8Qlo-BAQUL:-MzrdRn9Ez8Qlo-BAQUM:b57sm9e) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/275fce6d7f01ab2fd1af4457ca2f5481c8fe1c2e/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L168)):*
> ```cpp
>   EXPECT_CALL(partition_publisher_factory_, Call(0))
>       .WillOnce(Return(ByMove(absl::WrapUnique(&partition_publisher_0_))));
>   promise<Status> partition_publisher_start;
> ```

please just call this publisher_start_0 and the other one publisher_start_1

The <no number> -> 1 naming scheme is confusing



_Code quote:_
```cpp
partition_publisher_start
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 177 at r34](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mzrd4ep5e29frWH2CjF:-Mzrd4ep5e29frWH2CjG:bsk8dgo) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/275fce6d7f01ab2fd1af4457ca2f5481c8fe1c2e/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L177)):*
> ```cpp
>       .WillOnce(Return(ByMove(partition_publisher_start1.get_future())));
> 
>   // satisfy on_alarm_ future first
> ```

`// satisfy on_alarm_ future first, with one more partition than start future`



_Code quote:_
```cpp
// satisfy on_alarm_ future first
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 195 at r34](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzrfqOO74xTfR0TPonw:-MzrfqOO74xTfR0TPonx:bk6dsq7) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/275fce6d7f01ab2fd1af4457ca2f5481c8fe1c2e/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L195)):*
> ```cpp
> 
> TEST_F(MultipartitionPublisherTest,
>        PublisherCreatedFromAlarmGoodAfterInvalidValueFromStart) {
> ```

I wonder whether this behavior is right. In java, we fail the client if the first poll fails (https://github.com/googleapis/java-pubsublite/blob/a45a179c71c8c0e220c2ea9f711c8ff5e37908d4/google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatcherImpl.java#L98), perhaps we should do the same thing here if the first poll results in an error?
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 317 at r34](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mzrf1ag1owzJYVDDqgF:-Mzrf1ag1owzJYVDDqgG:b-ol5r5m) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/275fce6d7f01ab2fd1af4457ca2f5481c8fe1c2e/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L317)):*
> ```cpp
>       .WillOnce(Return(ByMove(partition_publisher_start_1.get_future())));
> 
>   EXPECT_CALL(routing_policy_, Route(2)).WillOnce(Return(0));
> ```

nit. usually you should test things that have indices other than 0. Lets test routing to partition 1 for the first and 0 for the second
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 329 at r34](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzrfFTi4iIRca14pgUr:-MzrfFTi4iIRca14pgUs:b-87yu9v) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/275fce6d7f01ab2fd1af4457ca2f5481c8fe1c2e/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L329)):*
> ```cpp
>   num_partitions.set_value(ExamplePartitionsResponse(2));
> 
>   Cursor m0_cursor;
> ```

nit pick random numbers, you never need to mention this number again.



_Code quote:_
```cpp
  Cursor m0_cursor;
  m0_cursor.set_offset(0);
  Cursor m1_cursor;
  m1_cursor.set_offset(1);
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 350 at r34](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MzrfQmtBlvMjrxW1_97:-MzrfQmtBlvMjrxW1_98:bpe3qm1) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/275fce6d7f01ab2fd1af4457ca2f5481c8fe1c2e/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L350)):*
> ```cpp
>   future<StatusOr<MessageMetadata>> message2 =
>       multipartition_publisher_->Publish(m2);
>   EXPECT_EQ(*message2.get(), (MessageMetadata{0, m2_cursor}));
> ```

this is a different test- get rid of it from here



_Code quote:_
```cpp
  PubSubMessage m2;
  *m2.mutable_key() = "key";
  *m2.mutable_data() = "data2";
  EXPECT_CALL(routing_policy_, Route(m2.key(), 2)).WillOnce(Return(0));
  Cursor m2_cursor;
  m2_cursor.set_offset(2);
  EXPECT_CALL(partition_publisher_0_, Publish(IsProtoEqual(m2)))
      .WillOnce(Return(ByMove(make_ready_future(StatusOr<Cursor>(m2_cursor)))));
  future<StatusOr<MessageMetadata>> message2 =
      multipartition_publisher_->Publish(m2);
  EXPECT_EQ(*message2.get(), (MessageMetadata{0, m2_cursor}));
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 405 at r34](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mzrdqf673zOJmAF5rWC:-Mzrdqf673zOJmAF5rWD:b25or64) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/275fce6d7f01ab2fd1af4457ca2f5481c8fe1c2e/google/cloud/pubsublit [...]

2022-04-05 12:45 UTC, dpcollins-google requested changes
> Reviewed 1 of 3 files at r35, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: 5 of 32 files reviewed, 9 unresolved discussions (waiting on @18suresha and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 33 at r36](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MztfyqG1j4vlz56aoMR:-MztfyqH7rkuZt2L_m7K:b-r3f26z) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/758e77cf9c2ab0defd0c803545b8850a5bbb158a/google/cloud/pubsublite/internal/multipartition_publisher.cc#L33)):*
> ```cpp
> MultipartitionPublisher::MultipartitionPublisher(
>     PartitionPublisherFactory publisher_factory,
>     std::shared_ptr<AdminServiceConnection> admin_connection,
> ```

I don't think this class is memory safe wrt its admin_connection futures. It can still have futures outstanding when Shutdown is called. It needs to chain any outstanding admin futures into its shutdown future.

You can also use this to ensure there is only one admin future outstanding at a time, and get rid of the tests for races between the alarm and Start call.
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 50 at r36](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mzthizo571bM5rDH70-:-Mzthizo571bM5rDH700:b-5alr9u) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/758e77cf9c2ab0defd0c803545b8850a5bbb158a/google/cloud/pubsublite/internal/multipartition_publisher.cc#L50)):*
> ```cpp
> 
> MultipartitionPublisher::~MultipartitionPublisher() {
>   SatisfyInitialPublishBuffer(
> ```

get rid of SatisfyInitialPublishBuffer, have this call Shutdown() instead and inline SatisfyInitialPublishBuffer into that method.



_Code quote:_
```cpp
  SatisfyInitialPublishBuffer(
      Status{StatusCode::kFailedPrecondition,
             "Multipartition publisher destructed before publishers created"});
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 67 at r36](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MztiVi53J8hF3HwOpEt:-MztiVi53J8hF3HwOpEu:b-b4pyu3) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/758e77cf9c2ab0defd0c803545b8850a5bbb158a/google/cloud/pubsublite/internal/multipartition_publisher.cc#L67)):*
> ```cpp
>         if (!partitions) return partitions.status();
>         if (partitions->partition_count() >=
>             std::numeric_limits<std::uint32_t>::max()) {
> ```

Partition



_Code quote:_
```cpp
<std::uint32_t
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 77 at r36](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MztjM3T093CXIjmrQPe:-MztjM3T093CXIjmrQPf:bt0ovbb) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/758e77cf9c2ab0defd0c803545b8850a5bbb158a/google/cloud/pubsublite/internal/multipartition_publisher.cc#L77)):*
> ```cpp
> 
> void MultipartitionPublisher::TriggerPublisherCreation() {
>   GetNumPartitions().then([this](future<StatusOr<Partition>> f) {
> ```

this lambda is long. Can you make this a member function:

```
void HandleNumPartitions(Partition num_partitions);
```

Then restructure the code:

```
[this](future<StatusOr<Partition>> f) {
  if (!service_composite_.status().ok()) return;
  auto num_partitions = f.get();
  if (num_partitions.ok()) return HandleNumPartitions(*num_partitions);
  // Handle error case
  ...
}
```



_Code quote:_
```cpp
[this](future<StatusOr<Partition>> f) {
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 88 at r36](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mzting8BICiFs6_eJUo:-Mzting8BICiFs6_eJUp:bqe6lh7) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/758e77cf9c2ab0defd0c803545b8850a5bbb158a/google/cloud/pubsublite/internal/multipartition_publisher.cc#L88)):*
> ```cpp
>         // fail client if first poll fails
>         return service_composite_.Abort(
>             Status{StatusCode::kFailedPrecondition,
> ```

don't drop the status from the admin server. `return service_composite_.Abort(num_partitions.status());`



_Code quote:_
```cpp
            Status{StatusCode::kFailedPrecondition,
                   "First num partitions poll failed."});
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 97 at r36](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mztj4AeEvrnEj8hp2Ub:-Mztj4AeEvrnEj8hp2Uc:b-b5oqh4) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/758e77cf9c2ab0defd0c803545b8850a5bbb158a/google/cloud/pubsublite/internal/multipartition_publisher.cc#L97)):*
> ```cpp
>     }
>     Partition current_num_partitions;
>     bool composite_ok = service_composite_.status().ok();
> ```

just `if (!service_composite_.status().ok()) return;`

Also move this up to the very first line.



_Code quote:_
```cpp
bool composite_ok = service_composite_.status().ok();
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 204 at r36](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MztkDoo2ITB6AExAO61:-MztkDop3opbfqZ9PHU4:bqw8eu0) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/758e77cf9c2ab0defd0c803545b8850a5bbb158a/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L204)):*
> ```cpp
>   num_partitions_0.set_value(ExamplePartitionsResponse(
>       std::numeric_limits<std::uint32_t>::max() +
>       static_cast<std::int64_t>(1)));  // out of bounds
> ```

its not needed to static_cast literals



_Code quote:_
```cpp
static_cast<std::int64_t>(1)
```


<!-- Sent from Reviewable.io -->

2022-04-05 14:58 UTC, 18suresha reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: 5 of 32 files reviewed, 9 unresolved discussions (waiting on @18suresha and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 204 at r36](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-MztkDoo2ITB6AExAO61:-MzuDTLK-P8Dah0q4On5:b-1mihff) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/758e77cf9c2ab0defd0c803545b8850a5bbb158a/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L204)):*
<details><summary><i>Previously, dpcollins-google wrote…</i></summary><blockquote>

its not needed to static_cast literals
</blockquote></details>

I originally did this without casting, but the tests failed. I think it's because `std::numeric_limits<Partition>::max()` returns an `std::uint32_t` and `1` on its own is a data type of size `<=` `std::uint32_t` so it results in overflow and becomes `0`?
When I printed out the argument when the tests were failing, it was `0`.


<!-- Sent from Reviewable.io -->

2022-04-06 13:05 UTC, dpcollins-google commented
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 207 at r46](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-Mzw_EHd7vCzcNqjMWi7:-MzyyG_r2PIf-7b0bc_G:b-cqb87q) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/fb723ce616c8b93c15b4302786e784123b1ab09d/google/cloud/pubsublite/internal/multipartition_publisher.cc#L207)):*
<details><summary><i>Previously, dpcollins-google wrote…</i></summary><blockquote>

TriggerPublisherCreation doesn't check this before emplacing the future, so this is a race. You need to check whether it is shutdown under lock, otherwise you have this race:

1) thread 1 checks if composite is shutdown in TriggerPublisherCreation
2) thread 2 calls Shutdown, shuts down composite
3) thread 2 gets mutex, sees no outstanding request
4) thread 1 gets mutex, emplaces outstanding request

Note you don't need to call Shutdown() under lock.
</blockquote></details>

Actually sorry, this comment is just wrong. Since the cancel_token_ has already been destroyed, there are no new calls to TriggerPublisherCreation, so the ordering here is only necessary for the early exit in the alarm case. You can just remove the comment, no other changes are needed


<!-- Sent from Reviewable.io -->

2022-04-07 17:22 UTC, coryan requested changes
When I said I would reject PRs over 1,000 lines it was not meant as a challenge for you to get as close to that as possible.  That meant "1,000 lines is obviously too many, I won't even bother looking".

Generally, try to keep your PRs around 200 lines of code, maybe 400 with the tests.

> Reviewed 6 of 14 files at r2, 9 of 17 files at r3, 2 of 2 files at r4, 1 of 6 files at r7, 1 of 5 files at r10, 1 of 1 files at r11, 1 of 10 files at r22, 4 of 7 files at r27, 1 of 2 files at r38, 1 of 2 files at r45, 1 of 1 files at r47, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-:-N-3xQmRCHn7rFEanEBa:b8567bp)* status: all files reviewed, 19 unresolved discussions (waiting on @18suresha and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 67 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3cJvO4-X9Fg16bxVO:-N-3cJvO4-X9Fg16bxVP:b-dlob2q) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher.cc#L67)):*
> ```cpp
> future<StatusOr<Partition>> MultipartitionPublisher::GetNumPartitions() {
>   return admin_connection_->AsyncGetTopicPartitions(topic_partitions_request_)
>       .then([](future<StatusOr<TopicPartitions>> f) -> StatusOr<Partition> {
> ```

`Partition` seems like a bad name, I read it and I think "this must be the name of a partition, or its description".  Only when I see the implementation I realize "this is a count, ugh".  `std::int<whatever>_t` seems like a better name, or `PartitionCount`.
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 69 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3bsFV-jh33Wm8_LPg:-N-3bsFV-jh33Wm8_LPh:bsdy69n) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher.cc#L69)):*
> ```cpp
>       .then([](future<StatusOr<TopicPartitions>> f) -> StatusOr<Partition> {
>         auto partitions = f.get();
>         if (!partitions) return partitions.status();
> ```

`return std::move(partitions).status();`
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 72 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3ciTN26_nx9jpEwyw:-N-3ciTO2zqCj9gyPXAo:b4e5vdp) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher.cc#L72)):*
> ```cpp
>         if (partitions->partition_count() >=
>             std::numeric_limits<Partition>::max()) {
>           return Status{StatusCode::kFailedPrecondition,
> ```

This is not a `kFailedPrecondition`, if anything, it indicates an internal problem in the service or library.  
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 92 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3dGut-BrSZP4T1P4f:-N-3dGut-BrSZP4T1P4g:b-1fmob3) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher.cc#L92)):*
> ```cpp
>   for (Partition i = current_num_partitions; i < num_partitions; ++i) {
>     new_partition_publishers.push_back(
>         publisher_factory_(static_cast<Partition>(i)));
> ```

This cast is useless?  
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 99 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3deIA09XKc_yyXqYE:-N-3deIA09XKc_yyXqYF:b-6cxkyl) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher.cc#L99)):*
> ```cpp
>     std::lock_guard<std::mutex> g{mu_};
>     for (auto& partition_publisher : new_partition_publishers) {
>       partition_publishers_.push_back(std::move(partition_publisher));
> ```

```cc
std::move(new_partition_publishers.begin(), new_partition_publishers.end(), std::back_inserter(partition_publishers__));
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 117 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3tkh-CuUdg2QJ-bOj:-N-3tkh-CuUdg2QJ-bOk:bgbhi7f) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher.cc#L117)):*
> ```cpp
>   GetNumPartitions()
>       .then([this](future<StatusOr<Partition>> f) {
>         if (!service_composite_.status().ok()) return;
> ```

In this project we just write `if (!service_composite_)`
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 155 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3upTy0q2SytuEhKyA:-N-3upTzBnjfN2Pxh_7T:bdzhafr) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher.cc#L155)):*
> ```cpp
>     publisher = partition_publishers_.at(partition).get();
>   }
>   auto shared_promise = std::make_shared<promise<StatusOr<MessageMetadata>>>(
> ```

I think this is a case where you want to create you own callable:

```cc
struct OnPublish {
  promise<StatusOr<MessageData>> p;
  Partition partition;
  void operator()(future<StatusOr<Cursor>> f) {
            auto publish_response = f.get();
            if (!publish_response) {
              return p.set_value(std::move(publish_response).status());
            }
            p.set_value(
                MessageMetadata{partition, *std::move(publish_response)});

  }
};

publisher->Publish(std::move(state.message)).then(OnPublish{std::move(state.publish_promise, partition});
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 162 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3vgoc7ZOyqMl6JMaM:-N-3vgod8_4dAZWh6ymx:b-yqzprn) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher.cc#L162)):*
> ```cpp
>             auto publish_response = publish_future.get();
>             if (!publish_response) {
>               return shared_promise->set_value(publish_response.status());
> ```

Note I inserted a `std::move()` above.
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 165 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3vjqCD7qX-vYmy9t6:-N-3vjqCD7qX-vYmy9t7:brxxwf7) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher.cc#L165)):*
> ```cpp
>             }
>             shared_promise->set_value(
>                 MessageMetadata{partition, std::move(*publish_response)});
> ```

I think you want `*std::move(publish_response)`.
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 184 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3wlMMBw5F-bHAtzxa:-N-3wlMMBw5F-bHAtzxb:b-64195v) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher.cc#L184)):*
> ```cpp
>   }
> 
>   auto to_return = state.publish_promise.get_future();
> ```

nit: maybe `RouteAndPublish()` should return the future?  Then you could write `return RouteAndPublish(std::move(state));`
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 192 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3x3ax0KI5zUkX63Dy:-N-3x3ax0KI5zUkX63Dz:b-z7srqj) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/mu [...]

2022-04-07 20:08 UTC, 18suresha reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: all files reviewed, 19 unresolved discussions (waiting on @18suresha, @coryan, and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 117 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3tkh-CuUdg2QJ-bOj:-N-4Ysza85J6ZiDBY6E4:b-csetzj) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher.cc#L117)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

In this project we just write `if (!service_composite_)`
</blockquote></details>

`ServiceComposite` doesn't have `operator bool()` overloaded though?
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 155 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3upTy0q2SytuEhKyA:-N-4Yy7TB54qoA3dfE4k:b-rrlpqv) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher.cc#L155)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think this is a case where you want to create you own callable:

```cc
struct OnPublish {
  promise<StatusOr<MessageData>> p;
  Partition partition;
  void operator()(future<StatusOr<Cursor>> f) {
            auto publish_response = f.get();
            if (!publish_response) {
              return p.set_value(std::move(publish_response).status());
            }
            p.set_value(
                MessageMetadata{partition, *std::move(publish_response)});

  }
};

publisher->Publish(std::move(state.message)).then(OnPublish{std::move(state.publish_promise, partition});
```

</blockquote></details>

yea wow this looks a lot better, thanks!
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 184 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3wlMMBw5F-bHAtzxa:-N-4Z37xDU7P_A24eZqp:b-fnby74) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher.cc#L184)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

nit: maybe `RouteAndPublish()` should return the future?  Then you could write `return RouteAndPublish(std::move(state));`
</blockquote></details>

the issue with this is if `Publish` is called before any `PartitionPublisher`s are created, then we need to hold off on calling `RouteAndPublish` for those messages until `PartitionPublisher`s are available (seen in `HandleNumPartitions`), so we can't immediately `return RouteAndPublish` within `Publish`
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 192 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3x3ax0KI5zUkX63Dy:-N-4cQ3z28ZwqXbF0rGM:b-s3mo2m) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher.cc#L192)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Any chance of a callback during these `Flush()` calls?  Why not?  Please add that explanation in a comment.
</blockquote></details>

`Flush` just calls into `PartitionPublisher::Flush` which just executes an async loop of writing batches of messages, so as far as I can tell there is not a chance
Though, we changed `Flush` to call `PartitionPublisher::Flush` outside of a lock just to be safe
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 104 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3zAfGCSVsb9OoEF4N:-N-4cw9C8SL9hfDpobuz:b-ticpbs) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L104)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I am not sure what is wrong, but if you find yourself writing such code something is (very) wrong.  Please fix.
</blockquote></details>

reorganized the test harnesses so that we don't have to explicitly call `delete`


<!-- Sent from Reviewable.io -->

2022-04-07 20:10 UTC, 18suresha reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: 30 of 33 files reviewed, 19 unresolved discussions (waiting on @18suresha, @coryan, and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 469 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-41PKr6oAuRhLsguzB:-N-4dS_b6PoC-JHNwLHf:bsupp4z) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L469)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

What are these magic numbers?
</blockquote></details>

they're just random values for `Cursor` that don't have any significance


<!-- Sent from Reviewable.io -->

2022-04-07 20:45 UTC, 18suresha reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: 30 of 33 files reviewed, 19 unresolved discussions (waiting on @18suresha, @coryan, and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 67 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3cJvO4-X9Fg16bxVO:-N-4lQqY-Qp5zCgpxOKv:bs5c72m) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher.cc#L67)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

`Partition` seems like a bad name, I read it and I think "this must be the name of a partition, or its description".  Only when I see the implementation I realize "this is a count, ugh".  `std::int<whatever>_t` seems like a better name, or `PartitionCount`.
</blockquote></details>

the "name" of a `Partition` is essentially an index, though I can see how it's not representative or readable in context of the number of partitions, changed it to `std::uint32_t` where appropriate 


<!-- Sent from Reviewable.io -->

2022-04-07 20:56 UTC, 18suresha commented
> When I said I would reject PRs over 1,000 lines it was not meant as a challenge for you to get as close to that as possible. That meant "1,000 lines is obviously too many, I won't even bother looking".

Oh sorry didn't mean for the LOC count in this PR to come off like that. I just interpreted 1k as a standard threshold to follow.

2022-04-07 22:17 UTC, coryan requested changes
> Reviewed 3 of 3 files at r48, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: all files reviewed, 11 unresolved discussions (waiting on @18suresha and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher.h, line 69 at r48](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-4lq7kE9KQnicxpzP7:-N-4lq7kE9KQnicxpzP8:b6cy0ss) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/346a7c5f0ae4820875abf8db36204a597bce8e50/google/cloud/pubsublite/internal/multipartition_publisher.h#L69)):*
> ```objc
>   };
> 
>   struct OnPublish {
> ```

You could have defined this struct inside the one function where it is used.  Your call.
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 69 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3bsFV-jh33Wm8_LPg:-N-4mOUs7DYAceCphrr3:b9lkf5i) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher.cc#L69)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

`return std::move(partitions).status();`
</blockquote></details>

Almost `std::move(partitions.status()` does not do the same thing as `std::move(partitions).status()`.  The first (and your original code) calls this:

https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/status_or.h#L252

The second calls this:

https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/status_or.h#L253
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 117 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3tkh-CuUdg2QJ-bOj:-N-4e8_1A1B2YQcI95TV:bgaqjyw) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher.cc#L117)):*
<details><summary><i>Previously, 18suresha (Adarsh Suresh) wrote…</i></summary><blockquote>

`ServiceComposite` doesn't have `operator bool()` overloaded though?
</blockquote></details>

Oh, I thought that was a `StatusOr<>`, never mind me.
___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 184 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3wlMMBw5F-bHAtzxa:-N-4nDn_8yIzRKNej-Wq:b-gsh5sd) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher.cc#L184)):*
<details><summary><i>Previously, 18suresha (Adarsh Suresh) wrote…</i></summary><blockquote>

the issue with this is if `Publish` is called before any `PartitionPublisher`s are created, then we need to hold off on calling `RouteAndPublish` for those messages until `PartitionPublisher`s are available (seen in `HandleNumPartitions`), so we can't immediately `return RouteAndPublish` within `Publish`
</blockquote></details>

I do not follow.  You could just do this:

```cc
future<StatusOr<MessageMetadata> RouteAndPublish(PublishState state) {
  auto result = state.publish_promise.get_future();

  ... same code as before ...

  return result;
}

future<StatusOr<MessageMetadata>> Publish(...) {
...
return RouteAndPublish(std::move(state));
}
```
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 469 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-41PKr6oAuRhLsguzB:-N-4eteP8BuLSDCkU1wG:b-vnxu0l) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L469)):*
<details><summary><i>Previously, 18suresha (Adarsh Suresh) wrote…</i></summary><blockquote>

they're just random values for `Cursor` that don't have any significance
</blockquote></details>

Consider using `42` which is the answer to life the universe and everything, and most folks know it is used as a placeholder.  Or better yet set a constant used in the whole file:

```cc
auto constexpr kOffsetPlaceholder = 42;
```

somewhere at the top of this file and use it everywhere.
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 55 at r48](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-4oBwR7prM1wAl2NPm:-N-4oBwR7prM1wAl2NPn:b-ae7x3g) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/346a7c5f0ae4820875abf8db36204a597bce8e50/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L55)):*
> ```cpp
> constexpr std::chrono::milliseconds kAlarmDuration{std::chrono::seconds{60}};
> constexpr std::uint64_t kOutOfBoundsPartition =
>     static_cast<std::uint64_t>(std::numeric_limits<Partition>::max()) + 1;
> ```

I thought `Partition` was becoming `std::uint32_t`?  Is there an alias we need to remove somewhere?
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 185 at r48](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-4om7A6eryR8PMF1wf:-N-4om7A6eryR8PMF1wg:bf17hxb) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/346a7c5f0ae4820875abf8db36204a597bce8e50/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L185)):*
> ```cpp
> 
>   EXPECT_CALL(partition_publisher_factory_, Call(0))
>       .WillOnce(Return(ByMove(absl::WrapUnique(&partition_publisher_0_))));
> ```

Hmm... this is mildly horrifying too.  And I say "mildly" because I have written worse code.  Is it at all possible to avoid these references to pointers that are mysteriously owned by something?
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 517 at r48](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-55LE02oopVdAf6ViY:-N-55LE1CzrK_bqxalc_:bsmi00u) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/346a7c5f0ae4820875abf8db36204a597bce8e50/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L517)):*
> ```cpp
>   EXPECT_CALL(routing_policy_, Route(m1.key(), 2)).WillOnce(Return(1));
>   Cursor m1_cursor;
>   m1_cursor.set_offset(876);
> ```

This (and any other) placeholder needs fixing too.


<!-- Sent from Reviewable.io -->

2022-04-08 00:25 UTC, 18suresha reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: 30 of 33 files reviewed, 11 unresolved discussions (waiting on @18suresha, @coryan, and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 184 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3wlMMBw5F-bHAtzxa:-N-5SZek3b4gLrIKiL7E:bdinjdg) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher.cc#L184)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I do not follow.  You could just do this:

```cc
future<StatusOr<MessageMetadata> RouteAndPublish(PublishState state) {
  auto result = state.publish_promise.get_future();

  ... same code as before ...

  return result;
}

future<StatusOr<MessageMetadata>> Publish(...) {
...
return RouteAndPublish(std::move(state));
}
```


</blockquote></details>

looking at this code path in `Publish`
```
PublishState state;
  state.message = std::move(m);
  {
    std::lock_guard<std::mutex> g{mu_};
    // performing this under lock to guarantee that all of
    // `initial_publish_buffer_` is flushed when publishers are created
    if (partition_publishers_.empty()) {
      initial_publish_buffer_.push_back(std::move(state));
      return initial_publish_buffer_.back().publish_promise.get_future();
    }
    ...
  }
```
we return the future of the promise in `state` if there are no publishers

in `HandleNumPartitions`, we do
```
{
    std::lock_guard<std::mutex> g{mu_};
    std::move(new_partition_publishers.begin(), new_partition_publishers.end(),
              std::back_inserter(partition_publishers_)); // not important for this example
    initial_publish_buffer.swap(initial_publish_buffer_);
  }
  for (auto& state : initial_publish_buffer) {
    state.num_partitions = num_partitions;
    RouteAndPublish(std::move(state));
  }
```
once there are publishers ready

so we can't always `return RouteAndPublish(...)` in `Publish` because of the case when we haven't provisioned any publishers and we have to just return the future of `state`'s promise instead
this also means that we can't have `RouteAndPublish` grab the future since we grab it here `return initial_publish_buffer_.back().publish_promise.get_future();`
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 55 at r48](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-4oBwR7prM1wAl2NPm:-N-5UQzDCLF7RFhJcZ7k:bbqx2s5) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/346a7c5f0ae4820875abf8db36204a597bce8e50/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L55)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I thought `Partition` was becoming `std::uint32_t`?  Is there an alias we need to remove somewhere?
</blockquote></details>

what I meant was that wherever we use `Partition` to represent something like the number of partitions, I changed it to `std::uint32_t`
though I still kept it as `Partition` in other places because a `Partition` is identified by its index (ex. you have `10` partitions labeled `0,...,9`
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 185 at r48](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-4om7A6eryR8PMF1wf:-N-5Y0XPE4p8QHL6FQ1f:b74tf7r) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/346a7c5f0ae4820875abf8db36204a597bce8e50/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L185)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Hmm... this is mildly horrifying too.  And I say "mildly" because I have written worse code.  Is it at all possible to avoid these references to pointers that are mysteriously owned by something?
</blockquote></details>

we could store raw pointers to dynamically allocated `PartitionPublisher`s, call `absl::WrapUnique` on those raw pointers, and dereference them in `EXPECT_CALL`s but I don't think that's better than using references


<!-- Sent from Reviewable.io -->

2022-04-08 00:28 UTC, 18suresha reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: 30 of 33 files reviewed, 11 unresolved discussions (waiting on @18suresha, @coryan, and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 185 at r48](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-4om7A6eryR8PMF1wf:-N-5ZRpB2aOX9d7MLrWg:b-smaol0) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/346a7c5f0ae4820875abf8db36204a597bce8e50/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L185)):*
<details><summary><i>Previously, 18suresha (Adarsh Suresh) wrote…</i></summary><blockquote>

we could store raw pointers to dynamically allocated `PartitionPublisher`s, call `absl::WrapUnique` on those raw pointers, and dereference them in `EXPECT_CALL`s but I don't think that's better than using references
</blockquote></details>

other than that, I don't think there's a cleaner way to maintain access to something that is uniquely owned by another entity


<!-- Sent from Reviewable.io -->

2022-04-08 12:49 UTC, coryan requested changes
> Reviewed 2 of 3 files at r49, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: 32 of 33 files reviewed, 5 unresolved discussions (waiting on @18suresha, @coryan, and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher.cc, line 184 at r47](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-3wlMMBw5F-bHAtzxa:-N-8D7hlBchuPxx-ZfCC:bb6sh2i) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/5935a71c096246067a5ab48d084d840b0c6c4b58/google/cloud/pubsublite/internal/multipartition_publisher.cc#L184)):*
<details><summary><i>Previously, 18suresha (Adarsh Suresh) wrote…</i></summary><blockquote>

looking at this code path in `Publish`
```
PublishState state;
  state.message = std::move(m);
  {
    std::lock_guard<std::mutex> g{mu_};
    // performing this under lock to guarantee that all of
    // `initial_publish_buffer_` is flushed when publishers are created
    if (partition_publishers_.empty()) {
      initial_publish_buffer_.push_back(std::move(state));
      return initial_publish_buffer_.back().publish_promise.get_future();
    }
    ...
  }
```
we return the future of the promise in `state` if there are no publishers

in `HandleNumPartitions`, we do
```
{
    std::lock_guard<std::mutex> g{mu_};
    std::move(new_partition_publishers.begin(), new_partition_publishers.end(),
              std::back_inserter(partition_publishers_)); // not important for this example
    initial_publish_buffer.swap(initial_publish_buffer_);
  }
  for (auto& state : initial_publish_buffer) {
    state.num_partitions = num_partitions;
    RouteAndPublish(std::move(state));
  }
```
once there are publishers ready

so we can't always `return RouteAndPublish(...)` in `Publish` because of the case when we haven't provisioned any publishers and we have to just return the future of `state`'s promise instead
this also means that we can't have `RouteAndPublish` grab the future since we grab it here `return initial_publish_buffer_.back().publish_promise.get_future();`
</blockquote></details>

Ack.
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 55 at r48](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-4oBwR7prM1wAl2NPm:-N-8BwK58HBusSa8wulN:b-nzm7kl) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/346a7c5f0ae4820875abf8db36204a597bce8e50/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L55)):*
<details><summary><i>Previously, 18suresha (Adarsh Suresh) wrote…</i></summary><blockquote>

what I meant was that wherever we use `Partition` to represent something like the number of partitions, I changed it to `std::uint32_t`
though I still kept it as `Partition` in other places because a `Partition` is identified by its index (ex. you have `10` partitions labeled `0,...,9`
</blockquote></details>

This is terribly confusing :shrug: 
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 185 at r48](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-4om7A6eryR8PMF1wf:-N-8CIgiDmLfzsvSNX-f:b-a6xckn) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/346a7c5f0ae4820875abf8db36204a597bce8e50/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L185)):*
> other than that, I don't think there's a cleaner way to maintain access to something that is uniquely owned by another entity

Don't make it uniquely owned... This is the same argument we have been having.  @dpcollins-google  I am not buying the tradeoffs anymore, we need to get that fixed.


<!-- Sent from Reviewable.io -->

2022-04-08 15:02 UTC, 18suresha reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: 30 of 33 files reviewed, 5 unresolved discussions (waiting on @18suresha, @coryan, and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 55 at r48](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-4oBwR7prM1wAl2NPm:-N-8UPyFDDnJ-lnx9sY2:b-gu2nq5) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/346a7c5f0ae4820875abf8db36204a597bce8e50/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L55)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

This is terribly confusing :shrug: 
</blockquote></details>

ah sorry I'll try again

there are two scenarios:
1. `Partition` refers to an actual partition
For example, one can have the conversation:
person 0: "Which partition does this message route to?"
person 1: "It routes to partition `1`."
With this in mind, we can see that in source code, a partition is just an index (we effectively have a `std::vector` of `Partition`s and we refer to each one by its index in the `std::vector`).
we can see this use case here
```
for (Partition i = current_num_partitions; i < num_partitions; ++i) {
  new_partition_publishers.push_back(publisher_factory_(i));
  service_composite_.AddServiceObject(new_partition_publishers.back().get());
}
```
in `HandleNumPartitions`

2. `Partition` refers to the number of partitions for a given `Topic` which was the original implementation
`GetNumPartitions` returns the number of partitions for a given `Topic`. Its signature was originally `future<StatusOr<Partition>> MultipartitionPublisher::GetNumPartitions()` 
though after your comment, I figured that since <number of partitions> doesn't have the same meaning as referring to a partition, I changed the signature to `future<StatusOr<std::uint32_t>> MultipartitionPublisher::GetNumPartitions()`

The reason for having the `Partition` alias in the first place is so that we can consistently maintain the data type across different files
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 185 at r48](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-4om7A6eryR8PMF1wf:-N-8gly1C3koTR4aZSXM:b-n9tkhd) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/346a7c5f0ae4820875abf8db36204a597bce8e50/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L185)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

> other than that, I don't think there's a cleaner way to maintain access to something that is uniquely owned by another entity

Don't make it uniquely owned... This is the same argument we have been having.  @dpcollins-google  I am not buying the tradeoffs anymore, we need to get that fixed.
</blockquote></details>

changed


<!-- Sent from Reviewable.io -->

2022-04-08 15:06 UTC, 18suresha reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: 30 of 33 files reviewed, 5 unresolved discussions (waiting on @18suresha, @coryan, and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 55 at r48](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-4oBwR7prM1wAl2NPm:-N-8hSUR1RNNJyUvG5Fg:bnuhzwk) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/346a7c5f0ae4820875abf8db36204a597bce8e50/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L55)):*
<details><summary><i>Previously, 18suresha (Adarsh Suresh) wrote…</i></summary><blockquote>

ah sorry I'll try again

there are two scenarios:
1. `Partition` refers to an actual partition
For example, one can have the conversation:
person 0: "Which partition does this message route to?"
person 1: "It routes to partition `1`."
With this in mind, we can see that in source code, a partition is just an index (we effectively have a `std::vector` of `Partition`s and we refer to each one by its index in the `std::vector`).
we can see this use case here
```
for (Partition i = current_num_partitions; i < num_partitions; ++i) {
  new_partition_publishers.push_back(publisher_factory_(i));
  service_composite_.AddServiceObject(new_partition_publishers.back().get());
}
```
in `HandleNumPartitions`

2. `Partition` refers to the number of partitions for a given `Topic` which was the original implementation
`GetNumPartitions` returns the number of partitions for a given `Topic`. Its signature was originally `future<StatusOr<Partition>> MultipartitionPublisher::GetNumPartitions()` 
though after your comment, I figured that since <number of partitions> doesn't have the same meaning as referring to a partition, I changed the signature to `future<StatusOr<std::uint32_t>> MultipartitionPublisher::GetNumPartitions()`

The reason for having the `Partition` alias in the first place is so that we can consistently maintain the data type across different files
</blockquote></details>

* I figured that since <number of partitions> doesn't have the same meaning as referring to a partition


<!-- Sent from Reviewable.io -->

2022-04-08 15:07 UTC, 18suresha reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: 30 of 33 files reviewed, 5 unresolved discussions (waiting on @18suresha, @coryan, and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 55 at r48](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-4oBwR7prM1wAl2NPm:-N-8hhPi22WYLHTLhlgw:b-r995aw) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/346a7c5f0ae4820875abf8db36204a597bce8e50/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L55)):*
<details><summary><i>Previously, 18suresha (Adarsh Suresh) wrote…</i></summary><blockquote>

* I figured that since <number of partitions> doesn't have the same meaning as referring to a partition
</blockquote></details>

\* I figured that since \<number of partitions\> doesn't have the same meaning as referring to a partition


<!-- Sent from Reviewable.io -->

2022-04-08 15:22 UTC, coryan requested changes
> Reviewed 3 of 3 files at r50, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: all files reviewed, 5 unresolved discussions (waiting on @18suresha and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 55 at r48](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-4oBwR7prM1wAl2NPm:-N-8hv_3-_lxLnDLefoV:bht0g3b) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/346a7c5f0ae4820875abf8db36204a597bce8e50/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L55)):*
<details><summary><i>Previously, 18suresha (Adarsh Suresh) wrote…</i></summary><blockquote>

\* I figured that since \<number of partitions\> doesn't have the same meaning as referring to a partition
</blockquote></details>

What I think is confusing is that the code refers to the same type as `Partition` sometimes and as `std::int32_t` some other times.  It indicates that `Partition` is not a good name.  I am sure it is clear enough for you, but reading the code the first time I was surprised to find that `Partition` was just an integer... I would think `std::int32_t partition` is clear enough, I am not sure why saying `Partition partition` is any more clear.  The alias seems superfluous and just confuses (some) folks.  I think we should remove it, but check with @dpcollins-google maybe I am just not understanding this enough.
___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 170 at r50](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-8kNwG-7aTQnmWl6Aw:-N-8kNwG-7aTQnmWl6Ax:bpazvb8) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e5c6eac115a3335bde2196e4035acf58d59c3e52/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L170)):*
> ```cpp
>  protected:
>   MultipartitionPublisherTest()
>       : partition_publisher_0_{std::make_shared<
> ```

Seems like your life would be easier  if you just created these in each test function, you are not saving much now that each function has that comment and calls to `Mock::VerifyAndClearExpectations`.


<!-- Sent from Reviewable.io -->

2022-04-08 15:50 UTC, 18suresha reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: all files reviewed, 5 unresolved discussions (waiting on @18suresha, @coryan, and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 170 at r50](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-8kNwG-7aTQnmWl6Aw:-N-8rKUu2x1xQePXxlCw:b-aybn5n) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e5c6eac115a3335bde2196e4035acf58d59c3e52/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L170)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Seems like your life would be easier  if you just created these in each test function, you are not saving much now that each function has that comment and calls to `Mock::VerifyAndClearExpectations`.
</blockquote></details>

I don't follow why it would be easier? Isn't the test harness DRYing up the instantiation?


<!-- Sent from Reviewable.io -->

2022-04-08 15:50 UTC, 18suresha reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: all files reviewed, 5 unresolved discussions (waiting on @18suresha, @coryan, and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 55 at r48](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-4oBwR7prM1wAl2NPm:-N-8rgosAGfRyd6mXIYE:b-t3p1nm) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/346a7c5f0ae4820875abf8db36204a597bce8e50/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L55)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

What I think is confusing is that the code refers to the same type as `Partition` sometimes and as `std::int32_t` some other times.  It indicates that `Partition` is not a good name.  I am sure it is clear enough for you, but reading the code the first time I was surprised to find that `Partition` was just an integer... I would think `std::int32_t partition` is clear enough, I am not sure why saying `Partition partition` is any more clear.  The alias seems superfluous and just confuses (some) folks.  I think we should remove it, but check with @dpcollins-google maybe I am just not understanding this enough.
</blockquote></details>

removed alias in this PR


<!-- Sent from Reviewable.io -->

2022-04-08 19:12 UTC, coryan commented
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 170 at r50](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-8kNwG-7aTQnmWl6Aw:-N-9WTS673npwlxiPY-V:bth1auz) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e5c6eac115a3335bde2196e4035acf58d59c3e52/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L170)):*
<details><summary><i>Previously, 18suresha (Adarsh Suresh) wrote…</i></summary><blockquote>

I don't follow why it would be easier? Isn't the test harness DRYing up the instantiation?
</blockquote></details>

You may be "DRYing" the instantiations, but then repeat this cleanup fragment over and over:

```cc
  // https://stackoverflow.com/questions/10286514/why-is-googlemock-leaking-my-shared-ptr
  EXPECT_TRUE(Mock::VerifyAndClearExpectations(partition_publisher_0_.get()));
  EXPECT_TRUE(Mock::VerifyAndClearExpectations(partition_publisher_1_.get()));
```

The tradeoff is not obvious, and the increased distance (in code lines) from where the mocks are created to where they are used is a downside. 

Maybe a helper function that returned both mocks would be fine (if it removed the need to copy that fragment over and over)?

Creating two mocks is not a particularly interesting piece of "knowledge", repeating it in each test case would not be the end of the world.

Maybe move the cleanup fragment to a `TearDown()` function?

If I was doing this, I think I would just initialize the mocks in each test case, but I would be fine if the cleanup was refactored too.

:information_source: as originally published, DRY says "Every piece of knowledge must have a single, unambiguous, authoritative representation within a system". Code duplication is not the problem that DRY is talking about (it is "a" problem, but not "the" problem).


<!-- Sent from Reviewable.io -->

2022-04-08 19:38 UTC, 18suresha reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528)* status: 30 of 33 files reviewed, 5 unresolved discussions (waiting on @18suresha, @coryan, and @dpcollins-google)

___
*[google/cloud/pubsublite/internal/multipartition_publisher_test.cc, line 170 at r50](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-N-8kNwG-7aTQnmWl6Aw:-N-9ehOc0AZ8FylMTTeu:b-6lv0im) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e5c6eac115a3335bde2196e4035acf58d59c3e52/google/cloud/pubsublite/internal/multipartition_publisher_test.cc#L170)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

You may be "DRYing" the instantiations, but then repeat this cleanup fragment over and over:

```cc
  // https://stackoverflow.com/questions/10286514/why-is-googlemock-leaking-my-shared-ptr
  EXPECT_TRUE(Mock::VerifyAndClearExpectations(partition_publisher_0_.get()));
  EXPECT_TRUE(Mock::VerifyAndClearExpectations(partition_publisher_1_.get()));
```

The tradeoff is not obvious, and the increased distance (in code lines) from where the mocks are created to where they are used is a downside. 

Maybe a helper function that returned both mocks would be fine (if it removed the need to copy that fragment over and over)?

Creating two mocks is not a particularly interesting piece of "knowledge", repeating it in each test case would not be the end of the world.

Maybe move the cleanup fragment to a `TearDown()` function?

If I was doing this, I think I would just initialize the mocks in each test case, but I would be fine if the cleanup was refactored too.

:information_source: as originally published, DRY says "Every piece of knowledge must have a single, unambiguous, authoritative representation within a system". Code duplication is not the problem that DRY is talking about (it is "a" problem, but not "the" problem).
</blockquote></details>

the cleanup fragment is now solely in `~MultipartitionPublisherTest()`
(when I first added `VerifyAndClearExpectations` I'd forgotten that in context of inheritance, destructors execute in reverse order, so didn't design it this way then)


<!-- Sent from Reviewable.io -->

2022-04-08 19:45 UTC, coryan approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

Perfect score, 1,000 lines :joy: :joy: 

> Reviewed 2 of 2 files at r51, 1 of 1 files at r52, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8528#-:-N-9hAcqEjmfc4m2uEh5:b-z15cfk)* status: all files reviewed, 4 unresolved discussions (waiting on @18suresha and @dpcollins-google)



<!-- Sent from Reviewable.io -->

2022-04-08 20:05 UTC, merged