feature(pubsublite): async topic partition count reader
googleapis/google-cloud-cpp pull request #8611
Opened 2022-03-28 19:51 UTC by 18suresha

This PR implements an asynchronous method for retrieving the number of partitions for a Pub/Sub Lite topic.

2022-03-29 13:46 UTC, dpcollins-google commented on google/cloud/pubsublite/topic.h
> +  friend bool operator==(Topic const& a, Topic const& b);
just implement these inline.

2022-03-29 13:47 UTC, dpcollins-google commented on google/cloud/pubsublite/internal/topic_partition_count_reader.h
> +  virtual future<StatusOr<std::uint64_t>> Read(
nit. make this `std::int64_t` to match the proto value type

2022-03-29 13:48 UTC, dpcollins-google commented on google/cloud/pubsublite/internal/topic_partition_count_reader.h
> +  virtual future<StatusOr<std::uint64_t>> Read(
Alternatively, make this `std::uint32_t` to match the needed bounds and check that the value is within those bounds.

2022-03-31 17:32 UTC, dpcollins-google commented on google/cloud/pubsublite/internal/topic_partition_count_reader.h
> +      google::cloud::pubsublite::Topic) = 0;
Add a name for the parameter. `topic`

2022-03-31 17:34 UTC, dpcollins-google commented on google/cloud/pubsublite/internal/topic_partition_count_reader_impl.cc
> +    return StatusOr<std::uint32_t>{
i.e. CHECK(partitions->partition_count() < UINT32_MAX);

2022-03-31 17:35 UTC, dpcollins-google commented on google/cloud/pubsublite/internal/topic_partition_count_reader_impl.cc
> +  std::thread t{[connection, p, topic, req]() {
just = here to capture everything referenced by value

2022-03-31 17:36 UTC, dpcollins-google commented on google/cloud/pubsublite/internal/topic_partition_count_reader_impl_test.cc
> +  auto p = std::make_shared<promise<void>>();
please give this a reasonable name. "request_continue"

2022-03-31 17:37 UTC, dpcollins-google commented on google/cloud/pubsublite/internal/topic_partition_count_reader_impl_test.cc
> +  auto p = std::make_shared<promise<void>>();
no need to use shared_ptr in tests, just put it on the stack and capture everything by reference
[&](GetTopicPartitionsRequest...

2022-03-31 18:32 UTC, dpcollins-google approved these changes

2022-03-31 21:36 UTC, coryan requested changes
If this is blocking other work we can talk about adding it as-is, with the understanding we will fix it soon-ish.  If it is not blocking other work, I would prefer to add `AsyncGeTopicPartitions()` to the admin APIs, it should be a matter of configuring the generator and rerunning it.

> Reviewed 3 of 4 files at r6, 1 of 1 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8611#-:-MzWtbdxE1HPIcMOoRDE:bann514)* status: all files reviewed, 10 unresolved discussions (waiting on @18suresha)

___
*[google/cloud/pubsublite/internal/topic_partition_count_reader_impl.cc, line 42 at r8](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8611#-MzWsvyr7mG7IJbnWKkL:-MzWsvyr7mG7IJbnWKkM:b3sbqrh) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1e3dc0807a007149c14d72552945d4c1c35b39ff/google/cloud/pubsublite/internal/topic_partition_count_reader_impl.cc#L42)):*
> ```cpp
>   // `this`
>   std::thread t{[=]() {
>     auto partition_count = connection->GetTopicPartitions(req);
> ```

If you need to, we can change the generator to create an `AsyncGetTopicPartitions()` which returns `future<StatusOr<...>>`.
___
*[google/cloud/pubsublite/internal/topic_partition_count_reader_impl.cc, line 45 at r8](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8611#-MzWsjCD8RntDy5Jcu8I:-MzWsjCD8RntDy5Jcu8J:b-lrqzaj) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/1e3dc0807a007149c14d72552945d4c1c35b39ff/google/cloud/pubsublite/internal/topic_partition_count_reader_impl.cc#L45)):*
> ```cpp
>     result->set_value(std::move(partition_count));
>   }};
>   t.detach();
> ```

detached threads are evil.  Can we avoid this?  Event `std::async()` with all its problems is better.


<!-- Sent from Reviewable.io -->

2022-04-01 01:45 UTC, 18suresha commented
Closed due to https://github.com/googleapis/google-cloud-cpp/pull/8640

2022-04-01 01:45 UTC, closed without merging