impl(bigtable): add MockRowReader
googleapis/google-cloud-cpp pull request #8912
Opened 2022-05-07 12:57 UTC by dbolduc

Most of the work for #8797 

Still TODO is to add a public factory function to our mock library. I am not going to do this until the DataConnection is ready for use. I did add the documentation now though.

2022-05-07 15:36 UTC, coryan requested changes

2022-05-07 15:36 UTC, coryan commented on google/cloud/bigtable/CMakeLists.txt
> +    internal/mock_row_reader_impl.h
That introduces testing code to the "production" library.  Please add to this library instead:

https://github.com/googleapis/google-cloud-cpp/blob/baa88cfb6a923db88c433cda0e76d612195baa04/google/cloud/bigtable/CMakeLists.txt#L263

2022-05-07 15:36 UTC, coryan commented on google/cloud/bigtable/internal/mock_row_reader_impl.h
> +    if (!sor) return sor.status();
nit: `return std::move(sor).status()`

2022-05-07 15:36 UTC, coryan commented on google/cloud/bigtable/row_reader.cc
> +namespace bigtable_internal {
This does not belong in the public library either.  Please move to the `testing` library.

2022-05-07 15:36 UTC, coryan commented on google/cloud/bigtable/row_reader.h
> +/**
Ditto.

2022-05-12 17:21 UTC, dbolduc commented
I am closing this for now because
* I am slightly changing the API of the base class (`RowReaderImpl`) in #8948 
* I want to discuss the approach with the team.

2022-05-12 17:21 UTC, closed without merging