refactor(storage): read object to use rest library
googleapis/google-cloud-cpp pull request #9197
Opened 2022-06-07 21:52 UTC by scotthart

2022-06-07 23:24 UTC, coryan requested changes
A few small nits, and I think you can remove a TODO. Looking good overall.

2022-06-07 23:24 UTC, coryan commented on google/cloud/internal/curl_impl.cc
> +  received_headers_.emplace(":curl-peer", handle_.GetPeer());
I recently removed this as part of #9162, please do not introduce it again.

2022-06-07 23:24 UTC, coryan commented on google/cloud/storage/internal/object_requests.cc
> +std::string ReadObjectRangeRequest::RangeHeaderValue() const {
nit: this could have been a separate PR.

2022-06-07 23:24 UTC, coryan commented on google/cloud/storage/client.cc
>      return CreateDefaultInternalClient(opts,
Did you intend to use `rest_opts` somewhere?

2022-06-07 23:24 UTC, coryan commented on google/cloud/storage/tests/object_media_integration_test.cc
> +  // TODO(9201): RestClient does not encounter the CURL error [28] Timeout
I think my previous comment about the unused `rest_opts` explains this.

2022-06-07 23:24 UTC, coryan commented on google/cloud/storage/internal/rest_client.cc
> +  return std::unique_ptr<ObjectReadSource>(
Why no `absl::make_unique<>` here?

2022-06-07 23:42 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9197)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @coryan and @scotthart)

___
*[`google/cloud/internal/curl_impl.cc` line 633 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9197#-N4-8rlWpMqzOCo0Fzdv-r1-633:-N4-XmzE6NTwhNqry0_9:b-keeub7) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/273600d14bd948e4b94d77cc63fd7371aae1dad6/google/cloud/internal/curl_impl.cc#L633)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I recently removed this as part of #9162, please do not introduce it again.
</blockquote></details>

So I initially rebased without adding the curl-peer header, but that caused a failure in ObjectReadHeadersIntegrationTest_NoDuplicatePeers, so I added it back in, which results in the test passing.
___
*[`google/cloud/storage/client.cc` line 100 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9197#-N4-8rlWpMqzOCo0Fzdw-r1-100:-N4-XhtU61sQ_7n7fbpj:b-834n6i) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/273600d14bd948e4b94d77cc63fd7371aae1dad6/google/cloud/storage/client.cc#L100)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Did you intend to use `rest_opts` somewhere?
</blockquote></details>

Oops.
___
*[`google/cloud/storage/internal/rest_client.cc` line 647 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9197#-N4-8rlWpMqzOCo0Fzdz-r1-647:-N4-XPjl2rVONiiYkwVZ:b-q26htx) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/273600d14bd948e4b94d77cc63fd7371aae1dad6/google/cloud/storage/internal/rest_client.cc#L647)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

Why no `absl::make_unique<>` here?
</blockquote></details>

Because the return type is `StatusOr<std::unique_ptr<ObjectReadSource>>` and `absl::make_unique<RestObjectReadSource>()` covariant issues.
___
*[`google/cloud/storage/tests/object_media_integration_test.cc` line 612 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9197#-N4-8rlWpMqzOCo0Fze0-r1-612:-N4-Y8HH6rLk_zKhQTUH:bdafnxm) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/273600d14bd948e4b94d77cc63fd7371aae1dad6/google/cloud/storage/tests/object_media_integration_test.cc#L612)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

I think my previous comment about the unused `rest_opts` explains this.
</blockquote></details>

Indeed it does, nice catch.


<!-- Sent from Reviewable.io -->

2022-06-08 00:01 UTC, coryan approved these changes
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9197)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @scotthart)

___
*[`google/cloud/internal/curl_impl.cc` line 633 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9197#-N4-8rlWpMqzOCo0Fzdv-r1-633:-N4-amQR9kqVVIrBTw6y:b-koshnl) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/273600d14bd948e4b94d77cc63fd7371aae1dad6/google/cloud/internal/curl_impl.cc#L633)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

So I initially rebased without adding the curl-peer header, but that caused a failure in ObjectReadHeadersIntegrationTest_NoDuplicatePeers, so I added it back in, which results in the test passing.
</blockquote></details>

Ack.  Well if the test passes we are Okay.  Sorry I introduced that bug.
___
*[`google/cloud/storage/internal/rest_client.cc` line 647 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9197#-N4-8rlWpMqzOCo0Fzdz-r1-647:-N4-bDcD4GJGw3vJ1w86:b8v2pct) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/273600d14bd948e4b94d77cc63fd7371aae1dad6/google/cloud/storage/internal/rest_client.cc#L647)):*
<details><summary><i>Previously, scotthart (Scott Hart) wrote…</i></summary><blockquote>

Because the return type is `StatusOr<std::unique_ptr<ObjectReadSource>>` and `absl::make_unique<RestObjectReadSource>()` covariant issues.
</blockquote></details>

Ack, thanks.


<!-- Sent from Reviewable.io -->

2022-06-08 17:48 UTC, devbww commented on google/cloud/internal/curl_options.h
> + * @note Setting this value to 0 results disables connection pooling.
s/results //

2022-06-08 17:48 UTC, devbww commented on google/cloud/storage/options.h
> + * @note Setting this value to 0 results disables connection pooling.
Ditto.

2022-06-08 17:50 UTC, scotthart reviewed
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9197)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @coryan and @devbww)

___
*[`google/cloud/internal/curl_options.h` line 65 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9197#-N43LtZlBuDn4oCGs1Pb-r4-65:-N43RADs5CgdRL7cA15B:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/24724b93058a5af43555b01b018de1ff6ee616a2/google/cloud/internal/curl_options.h#L65)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

s/results //
</blockquote></details>

Done.
___
*[`google/cloud/storage/options.h` line 105 at r4](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9197#-N43LtZlBuDn4oCGs1Pc-r4-105:-N43RAcXBood5g6OVzi8:b-896fix) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/24724b93058a5af43555b01b018de1ff6ee616a2/google/cloud/storage/options.h#L105)):*
<details><summary><i>Previously, devbww (Bradley White) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-08 18:09 UTC, coryan approved these changes
> Reviewed 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9197)* status: all files reviewed, 2 unresolved discussions (waiting on @devbww)



<!-- Sent from Reviewable.io -->

2022-06-08 18:42 UTC, merged